/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/principals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listPrincipals"];
    put?: never;
    post: operations["createUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/principals/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get?: never;
    put: operations["updateUser"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/service-tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createServiceToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/service-tokens/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["revokeServiceToken"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/environments/{id}/grants": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get: operations["getEnvironmentGrants"];
    put: operations["replaceEnvironmentGrants"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/environments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listEnvironments"];
    put?: never;
    post: operations["createEnvironment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/environments/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get: operations["getEnvironment"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/environments/{id}/state": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get: operations["getEnvironmentState"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/environments/{id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get: operations["environmentEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/environments/{id}/actions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["environmentAction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/environments/{id}/changes": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["changeEnvironment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/environments/{id}/view": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get?: never;
    put: operations["saveView"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/environments/{id}/draft": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get?: never;
    put: operations["saveDraft"];
    post?: never;
    delete: operations["discardDraft"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/environments/{id}/blueprints": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["saveEnvironmentBlueprint"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/blueprints": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listBlueprints"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/blueprints/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get: operations["getBlueprint"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/blueprints/{id}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get: operations["listBlueprintVersions"];
    put?: never;
    post: operations["saveBlueprintVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/blueprint-versions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get: operations["getBlueprintVersion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/environments/{id}/assets/{assetId}/actions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
        assetId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["assetAction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/environments/{id}/assets/{assetId}/console": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
        assetId: string;
      };
      cookie?: never;
    };
    /** @description WebSocket. Binary messages carry terminal or RFB bytes; terminal text messages contain ConsoleResize. */
    get: operations["assetConsole"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/operations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listOperations"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/operations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get: operations["getOperation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/operations/{id}/retry": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["retryOperation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listTemplates"];
    put?: never;
    post: operations["createTemplate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/nodes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listNodes"];
    put?: never;
    post: operations["registerNode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/identity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getIdentity"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    ConsoleKind: "terminal" | "serial" | "vnc";
    ConsoleResize: {
      cols: number;
      rows: number;
    };
    /** @enum {string} */
    Permission:
      | "read"
      | "operate"
      | "compose"
      | "manage"
      | "session"
      | "file"
      | "observe"
      | "network"
      | "access";
    ScopeGrant: {
      /** @enum {string} */
      scopeKind: "project" | "environment" | "asset";
      scopeId: string;
      permissions: components["schemas"]["Permission"][];
    };
    RolePreset: {
      /** @enum {string} */
      key: "viewer" | "operator" | "manager";
      name: string;
      permissions: components["schemas"]["Permission"][];
    };
    Principal: {
      id: string;
      name: string;
      /** @enum {string} */
      kind: "user" | "token";
      administrator: boolean;
      disabled: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      expiresAt?: string;
    };
    CreateUser: {
      name: string;
      /** Format: password */
      password: string;
    };
    UpdateUser: {
      name: string;
      /** Format: password */
      password?: string;
      disabled: boolean;
    };
    CreateServiceToken: {
      name: string;
      grants: components["schemas"]["ScopeGrant"][];
      /** Format: date-time */
      expiresAt?: string;
    };
    IssuedServiceToken: {
      principal: components["schemas"]["Principal"];
      token: string;
    };
    EnvironmentGrant: {
      principalId: string;
      assetIds?: string[];
      permissions: components["schemas"]["Permission"][];
    };
    EnvironmentSharing: {
      grants: components["schemas"]["EnvironmentGrant"][];
      inherited: components["schemas"]["EnvironmentGrant"][];
      subjects: components["schemas"]["Principal"][];
      ownerId?: string;
    };
    Identity: {
      id: string;
      name: string;
      administrator: boolean;
      roles?: components["schemas"]["RolePreset"][];
      grants?: components["schemas"]["ScopeGrant"][];
    };
    Login: {
      name: string;
      /** Format: password */
      password: string;
    };
    Resources: {
      cpu: number;
      /** Format: int64 */
      memoryMiB: number;
      /** Format: int64 */
      diskGiB: number;
    };
    Hardware: {
      /** @enum {string} */
      firmware: "bios" | "uefi";
      machine: string;
      /** @enum {string} */
      diskBus: "ide" | "sata" | "scsi" | "virtio";
      diskController?: string;
      /** @enum {string} */
      nicModel: "virtio" | "e1000" | "e1000e" | "rtl8139" | "vmxnet3";
      cpuModel?: string;
      secureBoot?: boolean;
      tpm?: boolean;
      guestAgent?: boolean;
      firmwareCode?: string;
      firmwareVars?: string;
    };
    Volume: {
      id: string;
      mountPath: string;
      /** Format: int64 */
      sizeGiB: number;
      retain?: boolean;
    };
    TemplateDisk: {
      id: string;
      /** Format: int64 */
      sizeGiB: number;
      /** @enum {string} */
      bus: "ide" | "sata" | "scsi" | "virtio";
      bootOrder: number;
      controllerModel?: string;
      controllerIndex?: number;
      controllerUnit?: number;
    };
    Template: {
      id: string;
      name: string;
      kind: components["schemas"]["TemplateKind"];
      os: string;
      version: number;
      source: string;
      /** @enum {string} */
      format?:
        "oci" | "docker" | "qcow2" | "raw" | "vmdk" | "ova" | "ovf" | "iso";
      resources: components["schemas"]["Resources"];
      hardware?: components["schemas"]["Hardware"];
      disks?: components["schemas"]["TemplateDisk"][];
      nicModels?: string[];
      /**
       * @default none
       * @enum {string}
       */
      initialization: "none" | "cloud-init" | "cloudbase-init";
      volumes?: components["schemas"]["Volume"][];
      /** @enum {string} */
      state?: "importing" | "ready" | "failed";
      error?: string;
    };
    Network: {
      id: string;
      name: string;
      cidr: string;
      gateway?: string;
      dnsAssetId?: string;
      dnsServers?: string[];
      mtu?: number;
    };
    Interface: {
      id: string;
      networkId: string;
      mac: string;
      address: string;
      primary: boolean;
    };
    Asset: {
      id: string;
      name: string;
      templateId: string;
      resources: components["schemas"]["Resources"];
      interfaces: components["schemas"]["Interface"][];
      volumes?: components["schemas"]["Volume"][];
      parameters?: {
        [key: string]: string;
      };
      guest?: components["schemas"]["GuestSettings"];
    };
    GuestSettings: {
      hostname?: string;
      username?: string;
      sshAuthorizedKeys?: string[];
    };
    Route: {
      networkId: string;
      destination: string;
      nextHop: string;
    };
    Policy: {
      id: string;
      networkId: string;
      /** @enum {string} */
      direction: "ingress" | "egress" | "both";
      /** @enum {string} */
      action: "allow" | "deny" | "shape";
      protocol?: string;
      source?: string;
      destination?: string;
      delayMs?: number;
      lossPercent?: number;
      bandwidthKbps?: number;
    };
    EnvironmentSpec: {
      assets: components["schemas"]["Asset"][];
      networks: components["schemas"]["Network"][];
      routes?: components["schemas"]["Route"][];
      policies?: components["schemas"]["Policy"][];
    };
    Point: {
      x: number;
      y: number;
    };
    CanvasView: {
      positions?: {
        [key: string]: components["schemas"]["Point"];
      };
      collapsed?: string[];
    };
    Draft: {
      baseRevision: number;
      spec: components["schemas"]["EnvironmentSpec"];
    };
    Environment: {
      permissions?: components["schemas"]["Permission"][];
      assetPermissions?: {
        [key: string]: components["schemas"]["Permission"][];
      };
      id: string;
      projectId: string;
      name: string;
      externalReference?: string;
      blueprintVersionId?: string;
      revision: number;
      status: components["schemas"]["EnvironmentStatus"];
      spec: components["schemas"]["EnvironmentSpec"];
      appliedSpec?: components["schemas"]["EnvironmentSpec"];
      view: components["schemas"]["CanvasView"];
      draft?: components["schemas"]["Draft"];
      operationId?: string;
      error?: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** @enum {string} */
    TemplateKind: "container" | "vm";
    /** @enum {string} */
    EnvironmentStatus:
      | "draft"
      | "deploying"
      | "running"
      | "stopped"
      | "suspended"
      | "changing"
      | "destroying"
      | "destroyed"
      | "failed"
      | "unknown";
    EnvironmentSummary: {
      id: string;
      projectId: string;
      name: string;
      externalReference?: string;
      revision: number;
      status: components["schemas"]["EnvironmentStatus"];
      assetCount: number;
      networkCount: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    AssetState: {
      assetId: string;
      instanceId: string;
      nodeId: string;
      state: string;
      error?: string;
      /** Format: date-time */
      observedAt: string;
    };
    EnvironmentState: {
      id: string;
      status: string;
      revision: number;
      assets: components["schemas"]["AssetState"][];
      operation?: components["schemas"]["Operation"];
      /** Format: date-time */
      updatedAt: string;
    };
    Operation: {
      id: string;
      environmentId?: string;
      kind: string;
      /** @enum {string} */
      state:
        "queued" | "running" | "succeeded" | "failed" | "partially_applied";
      phase: string;
      completed: number;
      total: number;
      error?: string;
      results?: components["schemas"]["ExecutionResult"][];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    Node: {
      id: string;
      name: string;
      endpoint: string;
      capacity: components["schemas"]["Resources"];
      reserved: components["schemas"]["Resources"];
      capabilities: string[];
      vmHardware?: components["schemas"]["VmHardware"];
      slots: number;
      /** Format: date-time */
      observedAt: string;
      state?: string;
      override?: components["schemas"]["Resources"];
    };
    ResolvedInterface: {
      id: string;
      networkId: string;
      mac: string;
      address: string;
      prefix: number;
      primary: boolean;
      portName: string;
      mtu: number;
      gateway?: string;
      dns?: string[];
    };
    AssetExecution: {
      asset: components["schemas"]["Asset"];
      template: components["schemas"]["Template"];
      instanceId: string;
      previousInstanceId?: string;
      interfaces: components["schemas"]["ResolvedInterface"][];
    };
    NodePlan: {
      operationId: string;
      environmentId: string;
      /** @enum {string} */
      phase:
        | "network"
        | "policies"
        | "prepare"
        | "update"
        | "start"
        | "stop"
        | "force-stop"
        | "suspend"
        | "resume"
        | "destroy"
        | "cleanup-volumes"
        | "remove-network"
        | "inspect";
      assets: components["schemas"]["AssetExecution"][];
      spec: components["schemas"]["EnvironmentSpec"];
    };
    ExecutionResult: {
      assetId: string;
      instanceId: string;
      state: string;
      error?: string;
      execution?: components["schemas"]["AssetExecution"];
      /** Format: date-time */
      observedAt: string;
    };
    NodeResult: {
      results: components["schemas"]["ExecutionResult"][];
      error?: string;
    };
    NodeInfo: {
      id: string;
      name: string;
      capacity: components["schemas"]["Resources"];
      capabilities: string[];
      slots: number;
      vmHardware?: components["schemas"]["VmHardware"];
    };
    VmHardware: {
      machines: components["schemas"]["VmMachine"][];
      cpuModes: string[];
      cpuModels: string[];
      nicModels: string[];
      diskControllers: string[];
    };
    VmMachine: {
      name: string;
      aliases: string[];
      maxVcpus: number;
      firmware: string[];
      secureBoot: boolean;
      tpm2: boolean;
      diskBuses: string[];
      firmwareFiles: string[];
    };
    CreateEnvironment: {
      name: string;
      projectId?: string;
      externalReference?: string;
      blueprintVersionId?: string;
      clientRequestId?: string;
      run?: boolean;
      spec?: components["schemas"]["EnvironmentSpec"];
    };
    SaveBlueprint: {
      name: string;
      expectedRevision: number;
      spec: components["schemas"]["EnvironmentSpec"];
    };
    SaveBlueprintVersion: {
      environmentId: string;
      expectedRevision: number;
      spec: components["schemas"]["EnvironmentSpec"];
    };
    Blueprint: {
      id: string;
      projectId: string;
      name: string;
      latestVersionId: string;
      latestVersion: number;
      assetCount: number;
      networkCount: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    BlueprintVersionSummary: {
      id: string;
      blueprintId: string;
      version: number;
      assetCount: number;
      networkCount: number;
      /** Format: date-time */
      createdAt: string;
    };
    BlueprintVersion: components["schemas"]["BlueprintVersionSummary"] & {
      spec: components["schemas"]["EnvironmentSpec"];
      view: components["schemas"]["CanvasView"];
      sourceEnvironmentId: string;
      sourceRevision: number;
    };
    ActionRequest: {
      /** @enum {string} */
      action:
        | "start"
        | "stop"
        | "force-stop"
        | "reboot"
        | "suspend"
        | "resume"
        | "rebuild"
        | "destroy";
      expectedRevision?: number;
      clientRequestId?: string;
    };
    ChangeRequest: {
      expectedRevision: number;
      spec: components["schemas"]["EnvironmentSpec"];
      apply: boolean;
      clientRequestId?: string;
    };
    ChangeItem: {
      id: string;
      name: string;
      /** @enum {string} */
      kind: "asset" | "network";
      /** @enum {string} */
      effect: "add" | "update" | "replace" | "remove";
      requiresStop?: boolean;
      dataEffect?: string;
    };
    ChangePreview: {
      revision: number;
      changes: components["schemas"]["ChangeItem"][];
    };
    NodeRegistration: {
      name: string;
      endpoint: string;
    };
    Problem: {
      status: number;
      title: string;
      detail: string;
    };
  };
  responses: {
    /** @description Accepted */
    Accepted: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Operation"];
      };
    };
  };
  parameters: {
    Id: string;
    Cursor: string;
    Limit: number;
    Search: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listPrincipals: {
    parameters: {
      query?: {
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
        search?: components["parameters"]["Search"];
        kind?: "user" | "token";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accounts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Principal"][];
        };
      };
    };
  };
  createUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUser"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Principal"];
        };
      };
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUser"];
      };
    };
    responses: {
      /** @description Updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createServiceToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateServiceToken"];
      };
    };
    responses: {
      /** @description Token returned once */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssuedServiceToken"];
        };
      };
    };
  };
  revokeServiceToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getEnvironmentGrants: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Environment sharing */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EnvironmentSharing"];
        };
      };
    };
  };
  replaceEnvironmentGrants: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EnvironmentGrant"][];
      };
    };
    responses: {
      /** @description Replaced */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listEnvironments: {
    parameters: {
      query?: {
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
        search?: components["parameters"]["Search"];
        status?: components["schemas"]["EnvironmentStatus"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Environment summaries */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EnvironmentSummary"][];
        };
      };
    };
  };
  createEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateEnvironment"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Environment"];
        };
      };
    };
  };
  getEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Environment */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Environment"];
        };
      };
    };
  };
  getEnvironmentState: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description State */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EnvironmentState"];
        };
      };
    };
  };
  environmentEvents: {
    parameters: {
      query?: never;
      header?: {
        "Last-Event-ID"?: number;
      };
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Committed environment events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": string;
        };
      };
    };
  };
  environmentAction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActionRequest"];
      };
    };
    responses: {
      202: components["responses"]["Accepted"];
    };
  };
  changeEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangeRequest"];
      };
    };
    responses: {
      /** @description Preview */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChangePreview"];
        };
      };
      202: components["responses"]["Accepted"];
    };
  };
  saveView: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CanvasView"];
      };
    };
    responses: {
      /** @description Saved */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  saveDraft: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Draft"];
      };
    };
    responses: {
      /** @description Saved */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  discardDraft: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Discarded */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  saveEnvironmentBlueprint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveBlueprint"];
      };
    };
    responses: {
      /** @description Saved */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Blueprint"];
        };
      };
    };
  };
  listBlueprints: {
    parameters: {
      query?: {
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
        search?: components["parameters"]["Search"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Environment blueprints */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Blueprint"][];
        };
      };
    };
  };
  getBlueprint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Blueprint */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Blueprint"];
        };
      };
    };
  };
  listBlueprintVersions: {
    parameters: {
      query?: {
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
      };
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Immutable blueprint versions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlueprintVersionSummary"][];
        };
      };
    };
  };
  saveBlueprintVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveBlueprintVersion"];
      };
    };
    responses: {
      /** @description Saved */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlueprintVersion"];
        };
      };
    };
  };
  getBlueprintVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Blueprint version */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlueprintVersion"];
        };
      };
    };
  };
  assetAction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
        assetId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActionRequest"];
      };
    };
    responses: {
      202: components["responses"]["Accepted"];
    };
  };
  assetConsole: {
    parameters: {
      query: {
        kind: components["schemas"]["ConsoleKind"];
      };
      header?: never;
      path: {
        id: components["parameters"]["Id"];
        assetId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Connected */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Asset has no running instance */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listOperations: {
    parameters: {
      query?: {
        environmentId?: string;
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Operations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Operation"][];
        };
      };
    };
  };
  getOperation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Operation"];
        };
      };
    };
  };
  retryOperation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      202: components["responses"]["Accepted"];
    };
  };
  listTemplates: {
    parameters: {
      query?: {
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
        search?: components["parameters"]["Search"];
        kind?: components["schemas"]["TemplateKind"];
        ids?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Templates */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Template"][];
        };
      };
    };
  };
  createTemplate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Template"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Template"];
        };
      };
    };
  };
  listNodes: {
    parameters: {
      query?: {
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
        search?: components["parameters"]["Search"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Nodes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Node"][];
        };
      };
    };
  };
  registerNode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NodeRegistration"];
      };
    };
    responses: {
      /** @description Registered */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Node"];
        };
      };
    };
  };
  getIdentity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Identity */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Identity"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Login"];
      };
    };
    responses: {
      /** @description Signed in */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Identity"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
