// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: access.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeAdministrators = `-- name: ActiveAdministrators :one
SELECT count(*) FROM principals WHERE kind='user' AND administrator AND NOT disabled
`

func (q *Queries) ActiveAdministrators(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, activeAdministrators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEnvironmentGrants = `-- name: DeleteEnvironmentGrants :exec
DELETE FROM grants WHERE (scope_kind='environment' AND scope_id=$1) OR (scope_kind='asset' AND scope_id LIKE $1||'/%')
`

func (q *Queries) DeleteEnvironmentGrants(ctx context.Context, scopeID string) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentGrants, scopeID)
	return err
}

const deletePrincipalCredentials = `-- name: DeletePrincipalCredentials :exec
DELETE FROM credentials WHERE principal_id=$1
`

func (q *Queries) DeletePrincipalCredentials(ctx context.Context, principalID string) error {
	_, err := q.db.Exec(ctx, deletePrincipalCredentials, principalID)
	return err
}

const deletePrincipalGrants = `-- name: DeletePrincipalGrants :exec
DELETE FROM grants WHERE principal_id=$1
`

func (q *Queries) DeletePrincipalGrants(ctx context.Context, principalID string) error {
	_, err := q.db.Exec(ctx, deletePrincipalGrants, principalID)
	return err
}

const disablePrincipal = `-- name: DisablePrincipal :exec
UPDATE principals SET disabled=true WHERE id=$1
`

func (q *Queries) DisablePrincipal(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, disablePrincipal, id)
	return err
}

const getPrincipal = `-- name: GetPrincipal :one
SELECT id, name, kind, password_hash, administrator, disabled, created_at FROM principals WHERE id=$1
`

func (q *Queries) GetPrincipal(ctx context.Context, id string) (Principal, error) {
	row := q.db.QueryRow(ctx, getPrincipal, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.PasswordHash,
		&i.Administrator,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const listEnvironmentGrants = `-- name: ListEnvironmentGrants :many
SELECT g.principal_id, g.scope_kind, g.scope_id, g.permissions,p.name,p.kind FROM grants g JOIN principals p ON p.id=g.principal_id
WHERE (g.scope_kind='environment' AND g.scope_id=$1) OR (g.scope_kind='asset' AND g.scope_id LIKE $1||'/%')
ORDER BY p.name,g.scope_kind,g.scope_id
`

type ListEnvironmentGrantsRow struct {
	PrincipalID string
	ScopeKind   string
	ScopeID     string
	Permissions []string
	Name        string
	Kind        string
}

func (q *Queries) ListEnvironmentGrants(ctx context.Context, scopeID string) ([]ListEnvironmentGrantsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentGrants, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentGrantsRow{}
	for rows.Next() {
		var i ListEnvironmentGrantsRow
		if err := rows.Scan(
			&i.PrincipalID,
			&i.ScopeKind,
			&i.ScopeID,
			&i.Permissions,
			&i.Name,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrincipals = `-- name: ListPrincipals :many
SELECT p.id,p.name,p.kind,p.administrator,p.disabled,p.created_at,
 (SELECT max(c.expires_at) FROM credentials c WHERE c.principal_id=p.id AND p.kind='token')::timestamptz AS expires_at FROM principals p
WHERE ($1::text='' OR p.kind=$1)
AND ($2::text='' OR p.name ILIKE '%'||$2||'%')
AND ($3::text='' OR p.id>$3)
ORDER BY p.id LIMIT $4
`

type ListPrincipalsParams struct {
	Kind      string
	Search    string
	Cursor    string
	PageLimit int32
}

type ListPrincipalsRow struct {
	ID            string
	Name          string
	Kind          string
	Administrator bool
	Disabled      bool
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) ListPrincipals(ctx context.Context, arg ListPrincipalsParams) ([]ListPrincipalsRow, error) {
	rows, err := q.db.Query(ctx, listPrincipals,
		arg.Kind,
		arg.Search,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrincipalsRow{}
	for rows.Next() {
		var i ListPrincipalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Administrator,
			&i.Disabled,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectGrants = `-- name: ListProjectGrants :many
SELECT g.principal_id, g.scope_kind, g.scope_id, g.permissions,p.name,p.kind FROM grants g JOIN principals p ON p.id=g.principal_id
WHERE g.scope_kind='project' AND g.scope_id=$1 ORDER BY p.name
`

type ListProjectGrantsRow struct {
	PrincipalID string
	ScopeKind   string
	ScopeID     string
	Permissions []string
	Name        string
	Kind        string
}

func (q *Queries) ListProjectGrants(ctx context.Context, scopeID string) ([]ListProjectGrantsRow, error) {
	rows, err := q.db.Query(ctx, listProjectGrants, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectGrantsRow{}
	for rows.Next() {
		var i ListProjectGrantsRow
		if err := rows.Scan(
			&i.PrincipalID,
			&i.ScopeKind,
			&i.ScopeID,
			&i.Permissions,
			&i.Name,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharingSubjects = `-- name: ListSharingSubjects :many
SELECT id,name,kind,administrator,disabled,created_at FROM principals ORDER BY name,id
`

type ListSharingSubjectsRow struct {
	ID            string
	Name          string
	Kind          string
	Administrator bool
	Disabled      bool
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListSharingSubjects(ctx context.Context) ([]ListSharingSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listSharingSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharingSubjectsRow{}
	for rows.Next() {
		var i ListSharingSubjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Administrator,
			&i.Disabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPrincipal = `-- name: LockPrincipal :one
SELECT id, name, kind, password_hash, administrator, disabled, created_at FROM principals WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockPrincipal(ctx context.Context, id string) (Principal, error) {
	row := q.db.QueryRow(ctx, lockPrincipal, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.PasswordHash,
		&i.Administrator,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const lockPrincipals = `-- name: LockPrincipals :many
SELECT id, name, kind, password_hash, administrator, disabled, created_at FROM principals WHERE id=ANY($1::text[]) ORDER BY id FOR UPDATE
`

func (q *Queries) LockPrincipals(ctx context.Context, dollar_1 []string) ([]Principal, error) {
	rows, err := q.db.Query(ctx, lockPrincipals, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Principal{}
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.PasswordHash,
			&i.Administrator,
			&i.Disabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS(SELECT 1 FROM projects WHERE id=$1)
`

func (q *Queries) ProjectExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, projectExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE principals SET name=$2,password_hash=COALESCE($3,password_hash),disabled=$4,administrator=COALESCE($5::boolean,administrator) WHERE id=$1
`

type UpdateUserParams struct {
	ID            string
	Name          string
	PasswordHash  []byte
	Disabled      bool
	Administrator *bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.PasswordHash,
		arg.Disabled,
		arg.Administrator,
	)
	return err
}
