// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: backups.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backupInUse = `-- name: BackupInUse :one
SELECT EXISTS(SELECT 1 FROM operations WHERE payload->>'backupId'=$1::text AND scope_kind='environment'
AND (state IN ('queued','running') OR (phase IN ('rollback','cleanup') AND state IN ('failed','partially_applied'))))
`

func (q *Queries) BackupInUse(ctx context.Context, dollar_1 string) (bool, error) {
	row := q.db.QueryRow(ctx, backupInUse, dollar_1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const backupRepositoryInUse = `-- name: BackupRepositoryInUse :one
SELECT EXISTS(SELECT 1 FROM backups b JOIN operations own ON own.id=b.operation_id WHERE b.repository_id=$1
AND (b.environment_id IS NOT NULL OR own.state IN ('queued','running') OR EXISTS
(SELECT 1 FROM operations o WHERE o.payload->>'backupId'=b.id AND o.scope_kind='environment'
AND (o.state IN ('queued','running') OR (o.phase IN ('rollback','cleanup') AND o.state IN ('failed','partially_applied'))))))
`

func (q *Queries) BackupRepositoryInUse(ctx context.Context, repositoryID string) (bool, error) {
	row := q.db.QueryRow(ctx, backupRepositoryInUse, repositoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const completeBackup = `-- name: CompleteBackup :exec
UPDATE backups SET state=$2,result=$3,size_bytes=$4 WHERE id=$1
`

type CompleteBackupParams struct {
	ID        string
	State     string
	Result    []byte
	SizeBytes int64
}

func (q *Queries) CompleteBackup(ctx context.Context, arg CompleteBackupParams) error {
	_, err := q.db.Exec(ctx, completeBackup,
		arg.ID,
		arg.State,
		arg.Result,
		arg.SizeBytes,
	)
	return err
}

const completeBackupRepository = `-- name: CompleteBackupRepository :exec
UPDATE backup_repositories SET state=$2,native_id=$3 WHERE id=$1
`

type CompleteBackupRepositoryParams struct {
	ID       string
	State    string
	NativeID *string
}

func (q *Queries) CompleteBackupRepository(ctx context.Context, arg CompleteBackupRepositoryParams) error {
	_, err := q.db.Exec(ctx, completeBackupRepository, arg.ID, arg.State, arg.NativeID)
	return err
}

const createBackup = `-- name: CreateBackup :exec
INSERT INTO backups(id,environment_id,repository_id,name,definition,operation_id) VALUES($1,$2,$3,$4,$5,$6)
`

type CreateBackupParams struct {
	ID            string
	EnvironmentID *string
	RepositoryID  string
	Name          string
	Definition    []byte
	OperationID   string
}

func (q *Queries) CreateBackup(ctx context.Context, arg CreateBackupParams) error {
	_, err := q.db.Exec(ctx, createBackup,
		arg.ID,
		arg.EnvironmentID,
		arg.RepositoryID,
		arg.Name,
		arg.Definition,
		arg.OperationID,
	)
	return err
}

const createBackupRepository = `-- name: CreateBackupRepository :exec
INSERT INTO backup_repositories(id,node_id,name,location,credentials,operation_id) VALUES($1,$2,$3,$4,$5,$6)
`

type CreateBackupRepositoryParams struct {
	ID          string
	NodeID      string
	Name        string
	Location    string
	Credentials []byte
	OperationID *string
}

func (q *Queries) CreateBackupRepository(ctx context.Context, arg CreateBackupRepositoryParams) error {
	_, err := q.db.Exec(ctx, createBackupRepository,
		arg.ID,
		arg.NodeID,
		arg.Name,
		arg.Location,
		arg.Credentials,
		arg.OperationID,
	)
	return err
}

const deleteBackup = `-- name: DeleteBackup :exec
DELETE FROM backups WHERE id=$1
`

func (q *Queries) DeleteBackup(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBackup, id)
	return err
}

const deleteBackupRepository = `-- name: DeleteBackupRepository :exec
DELETE FROM backup_repositories WHERE id=$1
`

func (q *Queries) DeleteBackupRepository(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBackupRepository, id)
	return err
}

const deleteRepositoryCatalog = `-- name: DeleteRepositoryCatalog :exec
DELETE FROM backups WHERE repository_id=$1 AND environment_id IS NULL
`

func (q *Queries) DeleteRepositoryCatalog(ctx context.Context, repositoryID string) error {
	_, err := q.db.Exec(ctx, deleteRepositoryCatalog, repositoryID)
	return err
}

const getBackup = `-- name: GetBackup :one
SELECT id, environment_id, repository_id, name, definition, result, size_bytes, state, operation_id, created_at FROM backups WHERE id=$1
`

func (q *Queries) GetBackup(ctx context.Context, id string) (Backup, error) {
	row := q.db.QueryRow(ctx, getBackup, id)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.RepositoryID,
		&i.Name,
		&i.Definition,
		&i.Result,
		&i.SizeBytes,
		&i.State,
		&i.OperationID,
		&i.CreatedAt,
	)
	return i, err
}

const getBackupRepository = `-- name: GetBackupRepository :one
SELECT id, node_id, name, location, credentials, native_id, state, operation_id, created_at FROM backup_repositories WHERE id=$1
`

func (q *Queries) GetBackupRepository(ctx context.Context, id string) (BackupRepository, error) {
	row := q.db.QueryRow(ctx, getBackupRepository, id)
	var i BackupRepository
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Location,
		&i.Credentials,
		&i.NativeID,
		&i.State,
		&i.OperationID,
		&i.CreatedAt,
	)
	return i, err
}

const importRepositoryBackups = `-- name: ImportRepositoryBackups :exec
INSERT INTO backups(id,repository_id,name,definition,result,size_bytes,state,operation_id,created_at)
SELECT x.id,$1,x.name,x.definition,x.result,x.size_bytes,'ready',$2,x.created_at
FROM jsonb_to_recordset($3::jsonb) AS x(id text,name text,definition jsonb,result jsonb,size_bytes bigint,created_at timestamptz)
ON CONFLICT(id) DO NOTHING
`

type ImportRepositoryBackupsParams struct {
	RepositoryID string
	OperationID  string
	Records      []byte
}

func (q *Queries) ImportRepositoryBackups(ctx context.Context, arg ImportRepositoryBackupsParams) error {
	_, err := q.db.Exec(ctx, importRepositoryBackups, arg.RepositoryID, arg.OperationID, arg.Records)
	return err
}

const listBackupRepositories = `-- name: ListBackupRepositories :many
SELECT r.id, r.node_id, r.name, r.location, r.credentials, r.native_id, r.state, r.operation_id, r.created_at,o.error FROM backup_repositories r LEFT JOIN operations o ON o.id=r.operation_id ORDER BY r.created_at,r.id
`

type ListBackupRepositoriesRow struct {
	BackupRepository BackupRepository
	Error            *string
}

func (q *Queries) ListBackupRepositories(ctx context.Context) ([]ListBackupRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, listBackupRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackupRepositoriesRow{}
	for rows.Next() {
		var i ListBackupRepositoriesRow
		if err := rows.Scan(
			&i.BackupRepository.ID,
			&i.BackupRepository.NodeID,
			&i.BackupRepository.Name,
			&i.BackupRepository.Location,
			&i.BackupRepository.Credentials,
			&i.BackupRepository.NativeID,
			&i.BackupRepository.State,
			&i.BackupRepository.OperationID,
			&i.BackupRepository.CreatedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackups = `-- name: ListBackups :many
SELECT b.id,b.environment_id,b.repository_id,b.name,b.state,b.size_bytes,b.operation_id,b.created_at,o.error
FROM backups b JOIN operations o ON o.id=b.operation_id
WHERE ($1::text='' OR b.environment_id=$1::text)
AND ($2::text='' OR b.repository_id=$2::text)
AND ($3::text='' OR (b.created_at,b.id)<(SELECT created_at,id FROM backups WHERE id=$3))
ORDER BY b.created_at DESC,b.id DESC LIMIT $4
`

type ListBackupsParams struct {
	EnvironmentID string
	RepositoryID  string
	Cursor        string
	PageLimit     int32
}

type ListBackupsRow struct {
	ID            string
	EnvironmentID *string
	RepositoryID  string
	Name          string
	State         string
	SizeBytes     int64
	OperationID   string
	CreatedAt     pgtype.Timestamptz
	Error         *string
}

func (q *Queries) ListBackups(ctx context.Context, arg ListBackupsParams) ([]ListBackupsRow, error) {
	rows, err := q.db.Query(ctx, listBackups,
		arg.EnvironmentID,
		arg.RepositoryID,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackupsRow{}
	for rows.Next() {
		var i ListBackupsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.RepositoryID,
			&i.Name,
			&i.State,
			&i.SizeBytes,
			&i.OperationID,
			&i.CreatedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBackup = `-- name: LockBackup :one
SELECT id, environment_id, repository_id, name, definition, result, size_bytes, state, operation_id, created_at FROM backups WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockBackup(ctx context.Context, id string) (Backup, error) {
	row := q.db.QueryRow(ctx, lockBackup, id)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.RepositoryID,
		&i.Name,
		&i.Definition,
		&i.Result,
		&i.SizeBytes,
		&i.State,
		&i.OperationID,
		&i.CreatedAt,
	)
	return i, err
}

const lockBackupRepository = `-- name: LockBackupRepository :one
SELECT id, node_id, name, location, credentials, native_id, state, operation_id, created_at FROM backup_repositories WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockBackupRepository(ctx context.Context, id string) (BackupRepository, error) {
	row := q.db.QueryRow(ctx, lockBackupRepository, id)
	var i BackupRepository
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Location,
		&i.Credentials,
		&i.NativeID,
		&i.State,
		&i.OperationID,
		&i.CreatedAt,
	)
	return i, err
}

const lockRepositoryBackups = `-- name: LockRepositoryBackups :many
SELECT id FROM backups WHERE repository_id=$1 ORDER BY id FOR UPDATE
`

func (q *Queries) LockRepositoryBackups(ctx context.Context, repositoryID string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockRepositoryBackups, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackupCreating = `-- name: MarkBackupCreating :exec
UPDATE backups SET state='creating' WHERE id=$1
`

func (q *Queries) MarkBackupCreating(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markBackupCreating, id)
	return err
}

const markBackupDeleting = `-- name: MarkBackupDeleting :exec
UPDATE backups SET state='deleting',operation_id=$2 WHERE id=$1
`

type MarkBackupDeletingParams struct {
	ID          string
	OperationID string
}

func (q *Queries) MarkBackupDeleting(ctx context.Context, arg MarkBackupDeletingParams) error {
	_, err := q.db.Exec(ctx, markBackupDeleting, arg.ID, arg.OperationID)
	return err
}

const markBackupRepositoryConnecting = `-- name: MarkBackupRepositoryConnecting :exec
UPDATE backup_repositories SET state='connecting',operation_id=$2 WHERE id=$1
`

type MarkBackupRepositoryConnectingParams struct {
	ID          string
	OperationID *string
}

func (q *Queries) MarkBackupRepositoryConnecting(ctx context.Context, arg MarkBackupRepositoryConnectingParams) error {
	_, err := q.db.Exec(ctx, markBackupRepositoryConnecting, arg.ID, arg.OperationID)
	return err
}

const registerBackupTemplates = `-- name: RegisterBackupTemplates :exec
INSERT INTO templates(id,definition)
SELECT x->>'id',x FROM jsonb_array_elements($1::jsonb) x
ON CONFLICT(id) DO UPDATE SET definition=jsonb_set(templates.definition,'{artifactNodeId}',EXCLUDED.definition->'artifactNodeId')
WHERE templates.definition->>'version'=EXCLUDED.definition->>'version' AND templates.definition->>'state'='ready'
`

func (q *Queries) RegisterBackupTemplates(ctx context.Context, records []byte) error {
	_, err := q.db.Exec(ctx, registerBackupTemplates, records)
	return err
}

const setBackupRepositoryNativeID = `-- name: SetBackupRepositoryNativeID :exec
UPDATE backup_repositories SET native_id=$2 WHERE id=$1
`

type SetBackupRepositoryNativeIDParams struct {
	ID       string
	NativeID *string
}

func (q *Queries) SetBackupRepositoryNativeID(ctx context.Context, arg SetBackupRepositoryNativeIDParams) error {
	_, err := q.db.Exec(ctx, setBackupRepositoryNativeID, arg.ID, arg.NativeID)
	return err
}
