// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: blueprints.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlueprint = `-- name: CreateBlueprint :exec
INSERT INTO blueprints(id,project_id,owner_id,name) VALUES($1,$2,$3,$4)
`

type CreateBlueprintParams struct {
	ID        string
	ProjectID string
	OwnerID   *string
	Name      string
}

func (q *Queries) CreateBlueprint(ctx context.Context, arg CreateBlueprintParams) error {
	_, err := q.db.Exec(ctx, createBlueprint,
		arg.ID,
		arg.ProjectID,
		arg.OwnerID,
		arg.Name,
	)
	return err
}

const createBlueprintVersion = `-- name: CreateBlueprintVersion :one
INSERT INTO blueprint_versions(id,blueprint_id,version,spec,view,asset_count,network_count,source_environment_id,source_revision)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id, blueprint_id, version, spec, view, asset_count, network_count, source_environment_id, source_revision, created_at
`

type CreateBlueprintVersionParams struct {
	ID                  string
	BlueprintID         string
	Version             int32
	Spec                []byte
	View                []byte
	AssetCount          int32
	NetworkCount        int32
	SourceEnvironmentID string
	SourceRevision      int32
}

func (q *Queries) CreateBlueprintVersion(ctx context.Context, arg CreateBlueprintVersionParams) (BlueprintVersion, error) {
	row := q.db.QueryRow(ctx, createBlueprintVersion,
		arg.ID,
		arg.BlueprintID,
		arg.Version,
		arg.Spec,
		arg.View,
		arg.AssetCount,
		arg.NetworkCount,
		arg.SourceEnvironmentID,
		arg.SourceRevision,
	)
	var i BlueprintVersion
	err := row.Scan(
		&i.ID,
		&i.BlueprintID,
		&i.Version,
		&i.Spec,
		&i.View,
		&i.AssetCount,
		&i.NetworkCount,
		&i.SourceEnvironmentID,
		&i.SourceRevision,
		&i.CreatedAt,
	)
	return i, err
}

const getBlueprint = `-- name: GetBlueprint :one
SELECT b.id, b.project_id, b.owner_id, b.name, b.version, b.created_at, b.updated_at,v.id AS latest_version_id,v.asset_count,v.network_count FROM blueprints b
JOIN blueprint_versions v ON v.blueprint_id=b.id AND v.version=b.version WHERE b.id=$1
`

type GetBlueprintRow struct {
	ID              string
	ProjectID       string
	OwnerID         *string
	Name            string
	Version         int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	LatestVersionID string
	AssetCount      int32
	NetworkCount    int32
}

func (q *Queries) GetBlueprint(ctx context.Context, id string) (GetBlueprintRow, error) {
	row := q.db.QueryRow(ctx, getBlueprint, id)
	var i GetBlueprintRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LatestVersionID,
		&i.AssetCount,
		&i.NetworkCount,
	)
	return i, err
}

const getBlueprintVersion = `-- name: GetBlueprintVersion :one
SELECT v.id, v.blueprint_id, v.version, v.spec, v.view, v.asset_count, v.network_count, v.source_environment_id, v.source_revision, v.created_at,b.project_id,b.owner_id FROM blueprint_versions v JOIN blueprints b ON b.id=v.blueprint_id WHERE v.id=$1
`

type GetBlueprintVersionRow struct {
	ID                  string
	BlueprintID         string
	Version             int32
	Spec                []byte
	View                []byte
	AssetCount          int32
	NetworkCount        int32
	SourceEnvironmentID string
	SourceRevision      int32
	CreatedAt           pgtype.Timestamptz
	ProjectID           string
	OwnerID             *string
}

func (q *Queries) GetBlueprintVersion(ctx context.Context, id string) (GetBlueprintVersionRow, error) {
	row := q.db.QueryRow(ctx, getBlueprintVersion, id)
	var i GetBlueprintVersionRow
	err := row.Scan(
		&i.ID,
		&i.BlueprintID,
		&i.Version,
		&i.Spec,
		&i.View,
		&i.AssetCount,
		&i.NetworkCount,
		&i.SourceEnvironmentID,
		&i.SourceRevision,
		&i.CreatedAt,
		&i.ProjectID,
		&i.OwnerID,
	)
	return i, err
}

const listBlueprintVersions = `-- name: ListBlueprintVersions :many
SELECT v.id,v.blueprint_id,v.version,v.asset_count,v.network_count,v.created_at FROM blueprint_versions v
WHERE v.blueprint_id=$1 AND ($2::text='' OR v.version<(SELECT p.version FROM blueprint_versions p WHERE p.id=$2 AND p.blueprint_id=$1))
ORDER BY v.version DESC LIMIT $3
`

type ListBlueprintVersionsParams struct {
	BlueprintID string
	Cursor      string
	PageLimit   int32
}

type ListBlueprintVersionsRow struct {
	ID           string
	BlueprintID  string
	Version      int32
	AssetCount   int32
	NetworkCount int32
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListBlueprintVersions(ctx context.Context, arg ListBlueprintVersionsParams) ([]ListBlueprintVersionsRow, error) {
	rows, err := q.db.Query(ctx, listBlueprintVersions, arg.BlueprintID, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlueprintVersionsRow{}
	for rows.Next() {
		var i ListBlueprintVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.BlueprintID,
			&i.Version,
			&i.AssetCount,
			&i.NetworkCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlueprints = `-- name: ListBlueprints :many
SELECT b.id, b.project_id, b.owner_id, b.name, b.version, b.created_at, b.updated_at,v.id AS latest_version_id,v.asset_count,v.network_count FROM blueprints b
JOIN blueprint_versions v ON v.blueprint_id=b.id AND v.version=b.version
WHERE ($1::boolean OR b.owner_id=$2 OR EXISTS
 (SELECT 1 FROM grants g WHERE g.principal_id=$2 AND g.scope_kind='project' AND g.scope_id=b.project_id AND 'read'=ANY(g.permissions)))
AND ($3::text='' OR b.id<$3) ORDER BY b.id DESC LIMIT $4
`

type ListBlueprintsParams struct {
	IsAdmin     bool
	PrincipalID *string
	Cursor      string
	PageLimit   int32
}

type ListBlueprintsRow struct {
	ID              string
	ProjectID       string
	OwnerID         *string
	Name            string
	Version         int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	LatestVersionID string
	AssetCount      int32
	NetworkCount    int32
}

func (q *Queries) ListBlueprints(ctx context.Context, arg ListBlueprintsParams) ([]ListBlueprintsRow, error) {
	rows, err := q.db.Query(ctx, listBlueprints,
		arg.IsAdmin,
		arg.PrincipalID,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlueprintsRow{}
	for rows.Next() {
		var i ListBlueprintsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OwnerID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestVersionID,
			&i.AssetCount,
			&i.NetworkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBlueprintVersion = `-- name: NextBlueprintVersion :one
UPDATE blueprints SET version=version+1,updated_at=now() WHERE id=$1 RETURNING id, project_id, owner_id, name, version, created_at, updated_at
`

func (q *Queries) NextBlueprintVersion(ctx context.Context, id string) (Blueprint, error) {
	row := q.db.QueryRow(ctx, nextBlueprintVersion, id)
	var i Blueprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setEnvironmentBlueprint = `-- name: SetEnvironmentBlueprint :exec
UPDATE environments SET blueprint_version_id=$2 WHERE id=$1
`

type SetEnvironmentBlueprintParams struct {
	ID                 string
	BlueprintVersionID *string
}

func (q *Queries) SetEnvironmentBlueprint(ctx context.Context, arg SetEnvironmentBlueprintParams) error {
	_, err := q.db.Exec(ctx, setEnvironmentBlueprint, arg.ID, arg.BlueprintVersionID)
	return err
}
