// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: external.sql

package queries

import (
	"context"
)

const listExternalNetworks = `-- name: ListExternalNetworks :many
SELECT node_id, interface, vlan, environment_id, network_id FROM external_network_leases WHERE environment_id=$1 ORDER BY node_id,interface,vlan
`

func (q *Queries) ListExternalNetworks(ctx context.Context, environmentID string) ([]ExternalNetworkLease, error) {
	rows, err := q.db.Query(ctx, listExternalNetworks, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalNetworkLease{}
	for rows.Next() {
		var i ExternalNetworkLease
		if err := rows.Scan(
			&i.NodeID,
			&i.Interface,
			&i.Vlan,
			&i.EnvironmentID,
			&i.NetworkID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseExternalNetworks = `-- name: ReleaseExternalNetworks :exec
DELETE FROM external_network_leases WHERE environment_id=$1
AND NOT ((node_id||'/'||interface||'/'||vlan::text)=ANY($2::text[]))
`

type ReleaseExternalNetworksParams struct {
	EnvironmentID string
	Retained      []string
}

func (q *Queries) ReleaseExternalNetworks(ctx context.Context, arg ReleaseExternalNetworksParams) error {
	_, err := q.db.Exec(ctx, releaseExternalNetworks, arg.EnvironmentID, arg.Retained)
	return err
}

const reserveExternalNetwork = `-- name: ReserveExternalNetwork :one
INSERT INTO external_network_leases(node_id,interface,vlan,environment_id,network_id)
VALUES($1,$2,$3,$4,$5)
ON CONFLICT(node_id,interface,vlan) DO UPDATE SET network_id=EXCLUDED.network_id
WHERE external_network_leases.environment_id=EXCLUDED.environment_id
RETURNING node_id, interface, vlan, environment_id, network_id
`

type ReserveExternalNetworkParams struct {
	NodeID        string
	Interface     string
	Vlan          int32
	EnvironmentID string
	NetworkID     string
}

func (q *Queries) ReserveExternalNetwork(ctx context.Context, arg ReserveExternalNetworkParams) (ExternalNetworkLease, error) {
	row := q.db.QueryRow(ctx, reserveExternalNetwork,
		arg.NodeID,
		arg.Interface,
		arg.Vlan,
		arg.EnvironmentID,
		arg.NetworkID,
	)
	var i ExternalNetworkLease
	err := row.Scan(
		&i.NodeID,
		&i.Interface,
		&i.Vlan,
		&i.EnvironmentID,
		&i.NetworkID,
	)
	return i, err
}
