// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: guest.sql

package queries

import (
	"context"
)

const deleteGuestConnection = `-- name: DeleteGuestConnection :exec
DELETE FROM guest_connections WHERE principal_id=$1 AND environment_id=$2 AND asset_id=$3
`

type DeleteGuestConnectionParams struct {
	PrincipalID   string
	EnvironmentID string
	AssetID       string
}

func (q *Queries) DeleteGuestConnection(ctx context.Context, arg DeleteGuestConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteGuestConnection, arg.PrincipalID, arg.EnvironmentID, arg.AssetID)
	return err
}

const deleteUnusedGuestConnections = `-- name: DeleteUnusedGuestConnections :exec
DELETE FROM guest_connections g WHERE g.environment_id=$1 AND NOT EXISTS (
 SELECT 1 FROM environments e, jsonb_array_elements(COALESCE(e.applied_spec,e.spec)->'assets') a
 WHERE e.id=g.environment_id AND e.status<>'destroyed' AND a->>'id'=g.asset_id
)
`

func (q *Queries) DeleteUnusedGuestConnections(ctx context.Context, environmentID string) error {
	_, err := q.db.Exec(ctx, deleteUnusedGuestConnections, environmentID)
	return err
}

const getEnvironmentNetworkEndpoint = `-- name: GetEnvironmentNetworkEndpoint :one
SELECT n.endpoint FROM environments e JOIN nodes n ON n.id=e.network_node_id WHERE e.id=$1
`

func (q *Queries) GetEnvironmentNetworkEndpoint(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getEnvironmentNetworkEndpoint, id)
	var endpoint string
	err := row.Scan(&endpoint)
	return endpoint, err
}

const getGuestConnection = `-- name: GetGuestConnection :one
SELECT encrypted FROM guest_connections WHERE principal_id=$1 AND environment_id=$2 AND asset_id=$3
`

type GetGuestConnectionParams struct {
	PrincipalID   string
	EnvironmentID string
	AssetID       string
}

func (q *Queries) GetGuestConnection(ctx context.Context, arg GetGuestConnectionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getGuestConnection, arg.PrincipalID, arg.EnvironmentID, arg.AssetID)
	var encrypted []byte
	err := row.Scan(&encrypted)
	return encrypted, err
}

const putGuestConnection = `-- name: PutGuestConnection :exec
INSERT INTO guest_connections (principal_id,environment_id,asset_id,encrypted) VALUES ($1,$2,$3,$4)
ON CONFLICT (principal_id,environment_id,asset_id) DO UPDATE SET encrypted=EXCLUDED.encrypted
`

type PutGuestConnectionParams struct {
	PrincipalID   string
	EnvironmentID string
	AssetID       string
	Encrypted     []byte
}

func (q *Queries) PutGuestConnection(ctx context.Context, arg PutGuestConnectionParams) error {
	_, err := q.db.Exec(ctx, putGuestConnection,
		arg.PrincipalID,
		arg.EnvironmentID,
		arg.AssetID,
		arg.Encrypted,
	)
	return err
}
