// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: migration.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitAssetMigration = `-- name: CommitAssetMigration :execrows
UPDATE runtime_assets SET node_id=$3,execution=$4,state=$5,error=NULL,observed_at=$6,instance_id=$7::text
WHERE instance_id=$1 AND node_id=$2 AND current
`

type CommitAssetMigrationParams struct {
	InstanceID     string
	NodeID         string
	NodeID_2       string
	Execution      []byte
	State          string
	ObservedAt     pgtype.Timestamptz
	TargetInstance string
}

func (q *Queries) CommitAssetMigration(ctx context.Context, arg CommitAssetMigrationParams) (int64, error) {
	result, err := q.db.Exec(ctx, commitAssetMigration,
		arg.InstanceID,
		arg.NodeID,
		arg.NodeID_2,
		arg.Execution,
		arg.State,
		arg.ObservedAt,
		arg.TargetInstance,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const commitMigrationSpec = `-- name: CommitMigrationSpec :exec
UPDATE environments SET spec=$2,applied_spec=$3,revision=revision+1,updated_at=now() WHERE id=$1
`

type CommitMigrationSpecParams struct {
	ID          string
	Spec        []byte
	AppliedSpec []byte
}

func (q *Queries) CommitMigrationSpec(ctx context.Context, arg CommitMigrationSpecParams) error {
	_, err := q.db.Exec(ctx, commitMigrationSpec, arg.ID, arg.Spec, arg.AppliedSpec)
	return err
}

const moveMigratedVolume = `-- name: MoveMigratedVolume :exec
UPDATE persistent_volumes SET node_id=$2,storage_pool_id=$3 WHERE id=$1
`

type MoveMigratedVolumeParams struct {
	ID            string
	NodeID        string
	StoragePoolID string
}

func (q *Queries) MoveMigratedVolume(ctx context.Context, arg MoveMigratedVolumeParams) error {
	_, err := q.db.Exec(ctx, moveMigratedVolume, arg.ID, arg.NodeID, arg.StoragePoolID)
	return err
}

const pendingEnvironmentOperations = `-- name: PendingEnvironmentOperations :one
SELECT EXISTS(SELECT 1 FROM operations WHERE scope_kind='environment' AND scope_id=$1 AND state IN ('queued','running'))
`

func (q *Queries) PendingEnvironmentOperations(ctx context.Context, scopeID string) (bool, error) {
	row := q.db.QueryRow(ctx, pendingEnvironmentOperations, scopeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
