// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Blueprint struct {
	ID        string
	ProjectID string
	OwnerID   *string
	Name      string
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type BlueprintVersion struct {
	ID                  string
	BlueprintID         string
	Version             int32
	Spec                []byte
	View                []byte
	AssetCount          int32
	NetworkCount        int32
	SourceEnvironmentID string
	SourceRevision      int32
	CreatedAt           pgtype.Timestamptz
}

type Credential struct {
	Hash        []byte
	PrincipalID string
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Environment struct {
	ID                 string
	ProjectID          string
	OwnerID            *string
	Name               string
	ExternalReference  *string
	Revision           int32
	Status             string
	Spec               []byte
	AppliedSpec        []byte
	View               []byte
	Draft              []byte
	NetworkNodeID      *string
	OperationID        *string
	Error              *string
	ClientRequestID    *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	BlueprintVersionID *string
}

type Event struct {
	Cursor        int64
	EnvironmentID *string
	Kind          string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
}

type Grant struct {
	PrincipalID string
	ScopeKind   string
	ScopeID     string
	Permissions []string
}

type Node struct {
	ID               string
	Name             string
	Endpoint         string
	Info             []byte
	CapacityOverride []byte
	State            string
	ObservedAt       pgtype.Timestamptz
}

type Operation struct {
	ID               string
	EnvironmentID    *string
	ScopeKind        string
	ScopeID          string
	Kind             string
	AssetID          *string
	State            string
	Phase            string
	Payload          []byte
	Results          []byte
	Error            *string
	ExpectedRevision int32
	LeaseOwner       *string
	LeaseUntil       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ClientRequestID  *string
}

type Principal struct {
	ID            string
	Name          string
	Kind          string
	PasswordHash  []byte
	Administrator bool
	Disabled      bool
	CreatedAt     pgtype.Timestamptz
}

type Project struct {
	ID   string
	Name string
}

type RuntimeAsset struct {
	EnvironmentID string
	AssetID       string
	InstanceID    string
	NodeID        string
	Execution     []byte
	State         string
	Cpu           int32
	MemoryMib     int64
	DiskGib       int64
	Current       bool
	Error         *string
	ObservedAt    pgtype.Timestamptz
}

type Template struct {
	ID         string
	Definition []byte
	CreatedAt  pgtype.Timestamptz
}
