// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: observation.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyNodeObservation = `-- name: ApplyNodeObservation :exec
WITH previous_node AS MATERIALIZED (
 SELECT id,state FROM nodes WHERE id=$1::text
), node_ready AS (
 UPDATE nodes SET state='ready',observed_at=$2::timestamptz
 WHERE id=$1 RETURNING id
), reported AS MATERIALIZED (
 SELECT r."environmentId"::text AS environment_id,r."assetId"::text AS asset_id,r."instanceId"::text AS instance_id,r.state::text AS state,r.error::text AS error,r."observedAt"::timestamptz AS observed_at
 FROM jsonb_to_recordset($3::jsonb)
 AS r("environmentId" text,"assetId" text,"instanceId" text,state text,error text,"observedAt" timestamptz)
), observations AS (
 SELECT environment_id,asset_id,instance_id,state,error,observed_at FROM reported
 UNION ALL
 SELECT a.environment_id,a.asset_id,a.instance_id,'absent','节点上已不存在该实例',$2::timestamptz
 FROM runtime_assets a WHERE $4::boolean AND a.node_id=$1 AND a.current
 AND NOT EXISTS(SELECT 1 FROM reported r WHERE r.instance_id=a.instance_id AND r.asset_id=a.asset_id AND r.environment_id=a.environment_id)
), changed AS (
 UPDATE runtime_assets a SET state=r.state,error=r.error,observed_at=r.observed_at
 FROM observations r WHERE a.node_id=$1 AND a.current
 AND a.environment_id=r.environment_id AND a.asset_id=r.asset_id AND a.instance_id=r.instance_id
 AND a.observed_at<r.observed_at
 RETURNING a.environment_id
), affected AS (
 SELECT environment_id FROM changed
 UNION
 SELECT a.environment_id FROM runtime_assets a,previous_node n WHERE a.node_id=n.id AND a.current AND n.state<>'ready'
)
INSERT INTO events(environment_id,kind,payload)
SELECT environment_id,'runtime.changed',jsonb_build_object('nodeId',$1::text) FROM affected
`

type ApplyNodeObservationParams struct {
	NodeID     string
	ObservedAt pgtype.Timestamptz
	Results    []byte
	Snapshot   bool
}

func (q *Queries) ApplyNodeObservation(ctx context.Context, arg ApplyNodeObservationParams) error {
	_, err := q.db.Exec(ctx, applyNodeObservation,
		arg.NodeID,
		arg.ObservedAt,
		arg.Results,
		arg.Snapshot,
	)
	return err
}

const currentEventCursor = `-- name: CurrentEventCursor :one
SELECT COALESCE(max(cursor),0)::bigint FROM events WHERE environment_id=$1
`

func (q *Queries) CurrentEventCursor(ctx context.Context, environmentID *string) (int64, error) {
	row := q.db.QueryRow(ctx, currentEventCursor, environmentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listObservedNodes = `-- name: ListObservedNodes :many
SELECT id,endpoint FROM nodes ORDER BY id
`

type ListObservedNodesRow struct {
	ID       string
	Endpoint string
}

func (q *Queries) ListObservedNodes(ctx context.Context) ([]ListObservedNodesRow, error) {
	rows, err := q.db.Query(ctx, listObservedNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObservedNodesRow{}
	for rows.Next() {
		var i ListObservedNodesRow
		if err := rows.Scan(&i.ID, &i.Endpoint); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeAssetStates = `-- name: ListRuntimeAssetStates :many
SELECT a.environment_id,a.asset_id,a.instance_id,a.node_id,a.current,a.observed_at,
 CASE WHEN n.state='ready' THEN a.state ELSE 'unknown' END::text AS state,
 COALESCE(CASE WHEN n.state='ready' THEN a.error ELSE '节点连接已断开' END,'')::text AS error
FROM runtime_assets a JOIN nodes n ON n.id=a.node_id WHERE a.environment_id=$1 ORDER BY a.asset_id,a.instance_id
`

type ListRuntimeAssetStatesRow struct {
	EnvironmentID string
	AssetID       string
	InstanceID    string
	NodeID        string
	Current       bool
	ObservedAt    pgtype.Timestamptz
	State         string
	Error         string
}

func (q *Queries) ListRuntimeAssetStates(ctx context.Context, environmentID string) ([]ListRuntimeAssetStatesRow, error) {
	rows, err := q.db.Query(ctx, listRuntimeAssetStates, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeAssetStatesRow{}
	for rows.Next() {
		var i ListRuntimeAssetStatesRow
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.AssetID,
			&i.InstanceID,
			&i.NodeID,
			&i.Current,
			&i.ObservedAt,
			&i.State,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markObservedNodeOffline = `-- name: MarkObservedNodeOffline :exec
WITH changed AS (
 UPDATE nodes SET state='offline' WHERE id=$1 AND state<>'offline' RETURNING id
)
INSERT INTO events(environment_id,kind,payload)
SELECT DISTINCT a.environment_id,'runtime.changed',jsonb_build_object('nodeId',a.node_id)
FROM runtime_assets a JOIN changed n ON n.id=a.node_id WHERE a.current
`

func (q *Queries) MarkObservedNodeOffline(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markObservedNodeOffline, id)
	return err
}
