// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addEvent = `-- name: AddEvent :one
INSERT INTO events(environment_id,kind,payload) VALUES($1,$2,$3) RETURNING cursor
`

type AddEventParams struct {
	EnvironmentID *string
	Kind          string
	Payload       []byte
}

func (q *Queries) AddEvent(ctx context.Context, arg AddEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, addEvent, arg.EnvironmentID, arg.Kind, arg.Payload)
	var cursor int64
	err := row.Scan(&cursor)
	return cursor, err
}

const applyAssetResults = `-- name: ApplyAssetResults :exec
UPDATE runtime_assets a SET state=r.state,error=r.error,observed_at=r."observedAt"
FROM jsonb_to_recordset($1::jsonb) AS r("instanceId" text,state text,error text,"observedAt" timestamptz)
WHERE a.instance_id=r."instanceId" AND a.observed_at<=r."observedAt"
`

func (q *Queries) ApplyAssetResults(ctx context.Context, dollar_1 []byte) error {
	_, err := q.db.Exec(ctx, applyAssetResults, dollar_1)
	return err
}

const claimOperation = `-- name: ClaimOperation :one
WITH candidate AS (
 SELECT o.id FROM operations o WHERE (o.state='queued' OR (o.state='running' AND o.lease_until<now()))
 AND NOT EXISTS(SELECT 1 FROM operations live WHERE live.scope_kind=o.scope_kind AND live.scope_id=o.scope_id AND live.id<>o.id AND live.state='running')
 ORDER BY o.created_at FOR UPDATE SKIP LOCKED LIMIT 1
)
UPDATE operations o SET state='running',lease_owner=$1,lease_until=now()+interval '30 seconds',updated_at=now()
FROM candidate c WHERE o.id=c.id RETURNING o.id, o.environment_id, o.scope_kind, o.scope_id, o.kind, o.asset_id, o.state, o.phase, o.payload, o.results, o.error, o.expected_revision, o.lease_owner, o.lease_until, o.created_at, o.updated_at, o.client_request_id
`

func (q *Queries) ClaimOperation(ctx context.Context, leaseOwner *string) (Operation, error) {
	row := q.db.QueryRow(ctx, claimOperation, leaseOwner)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Kind,
		&i.AssetID,
		&i.State,
		&i.Phase,
		&i.Payload,
		&i.Results,
		&i.Error,
		&i.ExpectedRevision,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientRequestID,
	)
	return i, err
}

const clearCurrentAssets = `-- name: ClearCurrentAssets :exec
UPDATE runtime_assets SET current=false WHERE environment_id=$1 AND asset_id=ANY($2::text[])
`

type ClearCurrentAssetsParams struct {
	EnvironmentID string
	Column2       []string
}

func (q *Queries) ClearCurrentAssets(ctx context.Context, arg ClearCurrentAssetsParams) error {
	_, err := q.db.Exec(ctx, clearCurrentAssets, arg.EnvironmentID, arg.Column2)
	return err
}

const commitEnvironment = `-- name: CommitEnvironment :exec
UPDATE environments SET applied_spec=$2,spec=$2,revision=revision+1,status=$3,draft=NULL,error=$4,updated_at=now() WHERE id=$1
`

type CommitEnvironmentParams struct {
	ID          string
	AppliedSpec []byte
	Status      string
	Error       *string
}

func (q *Queries) CommitEnvironment(ctx context.Context, arg CommitEnvironmentParams) error {
	_, err := q.db.Exec(ctx, commitEnvironment,
		arg.ID,
		arg.AppliedSpec,
		arg.Status,
		arg.Error,
	)
	return err
}

const countPrincipals = `-- name: CountPrincipals :one
SELECT count(*) FROM principals
`

func (q *Queries) CountPrincipals(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPrincipals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCredential = `-- name: CreateCredential :exec
INSERT INTO credentials(hash,principal_id,expires_at) VALUES($1,$2,$3)
`

type CreateCredentialParams struct {
	Hash        []byte
	PrincipalID string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential, arg.Hash, arg.PrincipalID, arg.ExpiresAt)
	return err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments(id,project_id,owner_id,name,external_reference,spec,client_request_id)
VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id, project_id, owner_id, name, external_reference, revision, status, spec, applied_spec, view, draft, network_node_id, operation_id, error, client_request_id, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ID                string
	ProjectID         string
	OwnerID           *string
	Name              string
	ExternalReference *string
	Spec              []byte
	ClientRequestID   *string
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ID,
		arg.ProjectID,
		arg.OwnerID,
		arg.Name,
		arg.ExternalReference,
		arg.Spec,
		arg.ClientRequestID,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Name,
		&i.ExternalReference,
		&i.Revision,
		&i.Status,
		&i.Spec,
		&i.AppliedSpec,
		&i.View,
		&i.Draft,
		&i.NetworkNodeID,
		&i.OperationID,
		&i.Error,
		&i.ClientRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations(id,environment_id,scope_kind,scope_id,kind,asset_id,payload,expected_revision,client_request_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id, environment_id, scope_kind, scope_id, kind, asset_id, state, phase, payload, results, error, expected_revision, lease_owner, lease_until, created_at, updated_at, client_request_id
`

type CreateOperationParams struct {
	ID               string
	EnvironmentID    *string
	ScopeKind        string
	ScopeID          string
	Kind             string
	AssetID          *string
	Payload          []byte
	ExpectedRevision int32
	ClientRequestID  *string
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.ID,
		arg.EnvironmentID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.Kind,
		arg.AssetID,
		arg.Payload,
		arg.ExpectedRevision,
		arg.ClientRequestID,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Kind,
		&i.AssetID,
		&i.State,
		&i.Phase,
		&i.Payload,
		&i.Results,
		&i.Error,
		&i.ExpectedRevision,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientRequestID,
	)
	return i, err
}

const createPrincipal = `-- name: CreatePrincipal :exec
INSERT INTO principals(id,name,kind,password_hash,administrator) VALUES ($1,$2,$3,$4,$5)
`

type CreatePrincipalParams struct {
	ID            string
	Name          string
	Kind          string
	PasswordHash  []byte
	Administrator bool
}

func (q *Queries) CreatePrincipal(ctx context.Context, arg CreatePrincipalParams) error {
	_, err := q.db.Exec(ctx, createPrincipal,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.PasswordHash,
		arg.Administrator,
	)
	return err
}

const createTemplate = `-- name: CreateTemplate :exec
INSERT INTO templates(id,definition) VALUES($1,$2)
`

type CreateTemplateParams struct {
	ID         string
	Definition []byte
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) error {
	_, err := q.db.Exec(ctx, createTemplate, arg.ID, arg.Definition)
	return err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE hash=$1
`

func (q *Queries) DeleteCredential(ctx context.Context, hash []byte) error {
	_, err := q.db.Exec(ctx, deleteCredential, hash)
	return err
}

const finishOperation = `-- name: FinishOperation :execrows
UPDATE operations SET state=$3,phase=$4,results=$5,error=$6,lease_until=NULL,updated_at=now() WHERE id=$1 AND lease_owner=$2
`

type FinishOperationParams struct {
	ID         string
	LeaseOwner *string
	State      string
	Phase      string
	Results    []byte
	Error      *string
}

func (q *Queries) FinishOperation(ctx context.Context, arg FinishOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishOperation,
		arg.ID,
		arg.LeaseOwner,
		arg.State,
		arg.Phase,
		arg.Results,
		arg.Error,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCredential = `-- name: GetCredential :one
SELECT p.id, p.name, p.kind, p.password_hash, p.administrator FROM credentials c JOIN principals p ON p.id=c.principal_id WHERE c.hash=$1 AND (c.expires_at IS NULL OR c.expires_at>now())
`

func (q *Queries) GetCredential(ctx context.Context, hash []byte) (Principal, error) {
	row := q.db.QueryRow(ctx, getCredential, hash)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.PasswordHash,
		&i.Administrator,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, project_id, owner_id, name, external_reference, revision, status, spec, applied_spec, view, draft, network_node_id, operation_id, error, client_request_id, created_at, updated_at FROM environments WHERE id=$1
`

func (q *Queries) GetEnvironment(ctx context.Context, id string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Name,
		&i.ExternalReference,
		&i.Revision,
		&i.Status,
		&i.Spec,
		&i.AppliedSpec,
		&i.View,
		&i.Draft,
		&i.NetworkNodeID,
		&i.OperationID,
		&i.Error,
		&i.ClientRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironmentByRequest = `-- name: GetEnvironmentByRequest :one
SELECT id, project_id, owner_id, name, external_reference, revision, status, spec, applied_spec, view, draft, network_node_id, operation_id, error, client_request_id, created_at, updated_at FROM environments WHERE project_id=$1 AND client_request_id=$2
`

type GetEnvironmentByRequestParams struct {
	ProjectID       string
	ClientRequestID *string
}

func (q *Queries) GetEnvironmentByRequest(ctx context.Context, arg GetEnvironmentByRequestParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByRequest, arg.ProjectID, arg.ClientRequestID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Name,
		&i.ExternalReference,
		&i.Revision,
		&i.Status,
		&i.Spec,
		&i.AppliedSpec,
		&i.View,
		&i.Draft,
		&i.NetworkNodeID,
		&i.OperationID,
		&i.Error,
		&i.ClientRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGrants = `-- name: GetGrants :many
SELECT principal_id, scope_kind, scope_id, permissions FROM grants WHERE principal_id=$1
`

func (q *Queries) GetGrants(ctx context.Context, principalID string) ([]Grant, error) {
	rows, err := q.db.Query(ctx, getGrants, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Grant{}
	for rows.Next() {
		var i Grant
		if err := rows.Scan(
			&i.PrincipalID,
			&i.ScopeKind,
			&i.ScopeID,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOperation = `-- name: GetOperation :one
SELECT id, environment_id, scope_kind, scope_id, kind, asset_id, state, phase, payload, results, error, expected_revision, lease_owner, lease_until, created_at, updated_at, client_request_id FROM operations WHERE id=$1
`

func (q *Queries) GetOperation(ctx context.Context, id string) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Kind,
		&i.AssetID,
		&i.State,
		&i.Phase,
		&i.Payload,
		&i.Results,
		&i.Error,
		&i.ExpectedRevision,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientRequestID,
	)
	return i, err
}

const getOperationByRequest = `-- name: GetOperationByRequest :one
SELECT id, environment_id, scope_kind, scope_id, kind, asset_id, state, phase, payload, results, error, expected_revision, lease_owner, lease_until, created_at, updated_at, client_request_id FROM operations WHERE environment_id=$1 AND client_request_id=$2
`

type GetOperationByRequestParams struct {
	EnvironmentID   *string
	ClientRequestID *string
}

func (q *Queries) GetOperationByRequest(ctx context.Context, arg GetOperationByRequestParams) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationByRequest, arg.EnvironmentID, arg.ClientRequestID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Kind,
		&i.AssetID,
		&i.State,
		&i.Phase,
		&i.Payload,
		&i.Results,
		&i.Error,
		&i.ExpectedRevision,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientRequestID,
	)
	return i, err
}

const getPrincipalByName = `-- name: GetPrincipalByName :one
SELECT id, name, kind, password_hash, administrator FROM principals WHERE name=$1
`

func (q *Queries) GetPrincipalByName(ctx context.Context, name string) (Principal, error) {
	row := q.db.QueryRow(ctx, getPrincipalByName, name)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.PasswordHash,
		&i.Administrator,
	)
	return i, err
}

const getReservedResources = `-- name: GetReservedResources :one
SELECT COALESCE(sum(cpu),0)::bigint AS cpu,COALESCE(sum(memory_mib),0)::bigint AS memory_mib,COALESCE(sum(disk_gib),0)::bigint AS disk_gib FROM runtime_assets WHERE node_id=$1
`

type GetReservedResourcesRow struct {
	Cpu       int64
	MemoryMib int64
	DiskGib   int64
}

func (q *Queries) GetReservedResources(ctx context.Context, nodeID string) (GetReservedResourcesRow, error) {
	row := q.db.QueryRow(ctx, getReservedResources, nodeID)
	var i GetReservedResourcesRow
	err := row.Scan(&i.Cpu, &i.MemoryMib, &i.DiskGib)
	return i, err
}

const getTemplates = `-- name: GetTemplates :many
SELECT id, definition, created_at FROM templates WHERE id=ANY($1::text[])
`

func (q *Queries) GetTemplates(ctx context.Context, dollar_1 []string) ([]Template, error) {
	rows, err := q.db.Query(ctx, getTemplates, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(&i.ID, &i.Definition, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, project_id, owner_id, name, external_reference, revision, status, spec, applied_spec, view, draft, network_node_id, operation_id, error, client_request_id, created_at, updated_at FROM environments WHERE status<>'destroyed' AND
 ($1::boolean OR owner_id=$2 OR EXISTS
 (SELECT 1 FROM grants g WHERE g.principal_id=$2 AND 'read'=ANY(g.permissions) AND
 ((g.scope_kind='project' AND g.scope_id=project_id) OR (g.scope_kind='environment' AND g.scope_id=environments.id))))
 AND ($3::text='' OR id<$3) ORDER BY id DESC LIMIT $4
`

type ListEnvironmentsParams struct {
	IsAdmin     bool
	PrincipalID *string
	Cursor      string
	PageLimit   int32
}

func (q *Queries) ListEnvironments(ctx context.Context, arg ListEnvironmentsParams) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments,
		arg.IsAdmin,
		arg.PrincipalID,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OwnerID,
			&i.Name,
			&i.ExternalReference,
			&i.Revision,
			&i.Status,
			&i.Spec,
			&i.AppliedSpec,
			&i.View,
			&i.Draft,
			&i.NetworkNodeID,
			&i.OperationID,
			&i.Error,
			&i.ClientRequestID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT n.id, n.name, n.endpoint, n.info, n.capacity_override, n.state, n.observed_at,COALESCE(sum(a.cpu),0)::bigint AS reserved_cpu,COALESCE(sum(a.memory_mib),0)::bigint AS reserved_memory,COALESCE(sum(a.disk_gib),0)::bigint AS reserved_disk
FROM nodes n LEFT JOIN runtime_assets a ON a.node_id=n.id GROUP BY n.id ORDER BY n.id
`

type ListNodesRow struct {
	ID               string
	Name             string
	Endpoint         string
	Info             []byte
	CapacityOverride []byte
	State            string
	ObservedAt       pgtype.Timestamptz
	ReservedCpu      int64
	ReservedMemory   int64
	ReservedDisk     int64
}

func (q *Queries) ListNodes(ctx context.Context) ([]ListNodesRow, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodesRow{}
	for rows.Next() {
		var i ListNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.Info,
			&i.CapacityOverride,
			&i.State,
			&i.ObservedAt,
			&i.ReservedCpu,
			&i.ReservedMemory,
			&i.ReservedDisk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperations = `-- name: ListOperations :many
SELECT id, environment_id, scope_kind, scope_id, kind, asset_id, state, phase, payload, results, error, expected_revision, lease_owner, lease_until, created_at, updated_at, client_request_id FROM operations WHERE environment_id=$1 ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListOperations(ctx context.Context, environmentID *string) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listOperations, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.ScopeKind,
			&i.ScopeID,
			&i.Kind,
			&i.AssetID,
			&i.State,
			&i.Phase,
			&i.Payload,
			&i.Results,
			&i.Error,
			&i.ExpectedRevision,
			&i.LeaseOwner,
			&i.LeaseUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientRequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeAssets = `-- name: ListRuntimeAssets :many
SELECT environment_id, asset_id, instance_id, node_id, execution, state, cpu, memory_mib, disk_gib, current, error, observed_at FROM runtime_assets WHERE environment_id=$1 ORDER BY asset_id,instance_id
`

func (q *Queries) ListRuntimeAssets(ctx context.Context, environmentID string) ([]RuntimeAsset, error) {
	rows, err := q.db.Query(ctx, listRuntimeAssets, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeAsset{}
	for rows.Next() {
		var i RuntimeAsset
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.AssetID,
			&i.InstanceID,
			&i.NodeID,
			&i.Execution,
			&i.State,
			&i.Cpu,
			&i.MemoryMib,
			&i.DiskGib,
			&i.Current,
			&i.Error,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, definition, created_at FROM templates ORDER BY created_at DESC,id
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(&i.ID, &i.Definition, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEnvironment = `-- name: LockEnvironment :one
SELECT id, project_id, owner_id, name, external_reference, revision, status, spec, applied_spec, view, draft, network_node_id, operation_id, error, client_request_id, created_at, updated_at FROM environments WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockEnvironment(ctx context.Context, id string) (Environment, error) {
	row := q.db.QueryRow(ctx, lockEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Name,
		&i.ExternalReference,
		&i.Revision,
		&i.Status,
		&i.Spec,
		&i.AppliedSpec,
		&i.View,
		&i.Draft,
		&i.NetworkNodeID,
		&i.OperationID,
		&i.Error,
		&i.ClientRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockNode = `-- name: LockNode :one
SELECT id, name, endpoint, info, capacity_override, state, observed_at FROM nodes WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRow(ctx, lockNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Info,
		&i.CapacityOverride,
		&i.State,
		&i.ObservedAt,
	)
	return i, err
}

const lockNodes = `-- name: LockNodes :many
SELECT id, name, endpoint, info, capacity_override, state, observed_at FROM nodes WHERE id=ANY($1::text[]) ORDER BY id FOR UPDATE
`

func (q *Queries) LockNodes(ctx context.Context, dollar_1 []string) ([]Node, error) {
	rows, err := q.db.Query(ctx, lockNodes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.Info,
			&i.CapacityOverride,
			&i.State,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const makeCurrentAssets = `-- name: MakeCurrentAssets :exec
UPDATE runtime_assets SET current=true WHERE instance_id=ANY($1::text[])
`

func (q *Queries) MakeCurrentAssets(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, makeCurrentAssets, dollar_1)
	return err
}

const putGrant = `-- name: PutGrant :exec
INSERT INTO grants(principal_id,scope_kind,scope_id,permissions) VALUES($1,$2,$3,$4) ON CONFLICT(principal_id,scope_kind,scope_id) DO UPDATE SET permissions=EXCLUDED.permissions
`

type PutGrantParams struct {
	PrincipalID string
	ScopeKind   string
	ScopeID     string
	Permissions []string
}

func (q *Queries) PutGrant(ctx context.Context, arg PutGrantParams) error {
	_, err := q.db.Exec(ctx, putGrant,
		arg.PrincipalID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.Permissions,
	)
	return err
}

const putNode = `-- name: PutNode :exec
INSERT INTO nodes(id,name,endpoint,info) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,endpoint=EXCLUDED.endpoint,info=EXCLUDED.info,state='ready',observed_at=now()
`

type PutNodeParams struct {
	ID       string
	Name     string
	Endpoint string
	Info     []byte
}

func (q *Queries) PutNode(ctx context.Context, arg PutNodeParams) error {
	_, err := q.db.Exec(ctx, putNode,
		arg.ID,
		arg.Name,
		arg.Endpoint,
		arg.Info,
	)
	return err
}

const readEvents = `-- name: ReadEvents :many
SELECT cursor, environment_id, kind, payload, created_at FROM events WHERE environment_id=$1 AND cursor>$2 ORDER BY cursor LIMIT 200
`

type ReadEventsParams struct {
	EnvironmentID *string
	Cursor        int64
}

func (q *Queries) ReadEvents(ctx context.Context, arg ReadEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, readEvents, arg.EnvironmentID, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.Cursor,
			&i.EnvironmentID,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAsset = `-- name: ReleaseAsset :exec
DELETE FROM runtime_assets WHERE instance_id=$1
`

func (q *Queries) ReleaseAsset(ctx context.Context, instanceID string) error {
	_, err := q.db.Exec(ctx, releaseAsset, instanceID)
	return err
}

const releaseAssets = `-- name: ReleaseAssets :exec
DELETE FROM runtime_assets WHERE instance_id=ANY($1::text[])
`

func (q *Queries) ReleaseAssets(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, releaseAssets, dollar_1)
	return err
}

const renewLease = `-- name: RenewLease :execrows
UPDATE operations SET lease_until=now()+interval '30 seconds' WHERE id=$1 AND lease_owner=$2 AND state='running'
`

type RenewLeaseParams struct {
	ID         string
	LeaseOwner *string
}

func (q *Queries) RenewLease(ctx context.Context, arg RenewLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewLease, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveAsset = `-- name: ReserveAsset :exec
INSERT INTO runtime_assets(environment_id,asset_id,instance_id,node_id,execution,cpu,memory_mib,disk_gib)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type ReserveAssetParams struct {
	EnvironmentID string
	AssetID       string
	InstanceID    string
	NodeID        string
	Execution     []byte
	Cpu           int32
	MemoryMib     int64
	DiskGib       int64
}

func (q *Queries) ReserveAsset(ctx context.Context, arg ReserveAssetParams) error {
	_, err := q.db.Exec(ctx, reserveAsset,
		arg.EnvironmentID,
		arg.AssetID,
		arg.InstanceID,
		arg.NodeID,
		arg.Execution,
		arg.Cpu,
		arg.MemoryMib,
		arg.DiskGib,
	)
	return err
}

const reserveAssets = `-- name: ReserveAssets :exec
INSERT INTO runtime_assets(environment_id,asset_id,instance_id,node_id,execution,cpu,memory_mib,disk_gib)
SELECT r."environmentId",r."assetId",r."instanceId",r."nodeId",r.execution,r.cpu,r."memoryMiB",r."diskGiB"
FROM jsonb_to_recordset($1::jsonb) AS r("environmentId" text,"assetId" text,"instanceId" text,"nodeId" text,execution jsonb,cpu integer,"memoryMiB" bigint,"diskGiB" bigint)
`

func (q *Queries) ReserveAssets(ctx context.Context, dollar_1 []byte) error {
	_, err := q.db.Exec(ctx, reserveAssets, dollar_1)
	return err
}

const saveDesiredSpec = `-- name: SaveDesiredSpec :exec
UPDATE environments SET spec=$2,updated_at=now() WHERE id=$1
`

type SaveDesiredSpecParams struct {
	ID   string
	Spec []byte
}

func (q *Queries) SaveDesiredSpec(ctx context.Context, arg SaveDesiredSpecParams) error {
	_, err := q.db.Exec(ctx, saveDesiredSpec, arg.ID, arg.Spec)
	return err
}

const saveDraft = `-- name: SaveDraft :exec
UPDATE environments SET draft=$2,updated_at=now() WHERE id=$1
`

type SaveDraftParams struct {
	ID    string
	Draft []byte
}

func (q *Queries) SaveDraft(ctx context.Context, arg SaveDraftParams) error {
	_, err := q.db.Exec(ctx, saveDraft, arg.ID, arg.Draft)
	return err
}

const saveView = `-- name: SaveView :exec
UPDATE environments SET view=$2,updated_at=now() WHERE id=$1
`

type SaveViewParams struct {
	ID   string
	View []byte
}

func (q *Queries) SaveView(ctx context.Context, arg SaveViewParams) error {
	_, err := q.db.Exec(ctx, saveView, arg.ID, arg.View)
	return err
}

const setCurrentAsset = `-- name: SetCurrentAsset :exec
UPDATE runtime_assets SET current=(instance_id=$3) WHERE environment_id=$1 AND asset_id=$2
`

type SetCurrentAssetParams struct {
	EnvironmentID string
	AssetID       string
	InstanceID    string
}

func (q *Queries) SetCurrentAsset(ctx context.Context, arg SetCurrentAssetParams) error {
	_, err := q.db.Exec(ctx, setCurrentAsset, arg.EnvironmentID, arg.AssetID, arg.InstanceID)
	return err
}

const setEnvironmentOperation = `-- name: SetEnvironmentOperation :exec
UPDATE environments SET operation_id=$2,status=$3,error=NULL,updated_at=now() WHERE id=$1
`

type SetEnvironmentOperationParams struct {
	ID          string
	OperationID *string
	Status      string
}

func (q *Queries) SetEnvironmentOperation(ctx context.Context, arg SetEnvironmentOperationParams) error {
	_, err := q.db.Exec(ctx, setEnvironmentOperation, arg.ID, arg.OperationID, arg.Status)
	return err
}

const setEnvironmentState = `-- name: SetEnvironmentState :exec
UPDATE environments SET status=$2,error=$3,updated_at=now() WHERE id=$1
`

type SetEnvironmentStateParams struct {
	ID     string
	Status string
	Error  *string
}

func (q *Queries) SetEnvironmentState(ctx context.Context, arg SetEnvironmentStateParams) error {
	_, err := q.db.Exec(ctx, setEnvironmentState, arg.ID, arg.Status, arg.Error)
	return err
}

const setNetworkOwner = `-- name: SetNetworkOwner :exec
UPDATE environments SET network_node_id=$2 WHERE id=$1
`

type SetNetworkOwnerParams struct {
	ID            string
	NetworkNodeID *string
}

func (q *Queries) SetNetworkOwner(ctx context.Context, arg SetNetworkOwnerParams) error {
	_, err := q.db.Exec(ctx, setNetworkOwner, arg.ID, arg.NetworkNodeID)
	return err
}

const setNodeCapacity = `-- name: SetNodeCapacity :exec
UPDATE nodes SET capacity_override=$2 WHERE id=$1
`

type SetNodeCapacityParams struct {
	ID               string
	CapacityOverride []byte
}

func (q *Queries) SetNodeCapacity(ctx context.Context, arg SetNodeCapacityParams) error {
	_, err := q.db.Exec(ctx, setNodeCapacity, arg.ID, arg.CapacityOverride)
	return err
}

const setNodeState = `-- name: SetNodeState :exec
UPDATE nodes SET state=$2,observed_at=CASE WHEN $2='ready' THEN now() ELSE observed_at END WHERE id=$1
`

type SetNodeStateParams struct {
	ID    string
	State string
}

func (q *Queries) SetNodeState(ctx context.Context, arg SetNodeStateParams) error {
	_, err := q.db.Exec(ctx, setNodeState, arg.ID, arg.State)
	return err
}

const setOperationPhase = `-- name: SetOperationPhase :execrows
UPDATE operations SET phase=$3,payload=$4,updated_at=now() WHERE id=$1 AND lease_owner=$2
`

type SetOperationPhaseParams struct {
	ID         string
	LeaseOwner *string
	Phase      string
	Payload    []byte
}

func (q *Queries) SetOperationPhase(ctx context.Context, arg SetOperationPhaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOperationPhase,
		arg.ID,
		arg.LeaseOwner,
		arg.Phase,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAssetExecution = `-- name: UpdateAssetExecution :exec
UPDATE runtime_assets SET execution=$2,cpu=$3,memory_mib=$4,disk_gib=$5 WHERE instance_id=$1
`

type UpdateAssetExecutionParams struct {
	InstanceID string
	Execution  []byte
	Cpu        int32
	MemoryMib  int64
	DiskGib    int64
}

func (q *Queries) UpdateAssetExecution(ctx context.Context, arg UpdateAssetExecutionParams) error {
	_, err := q.db.Exec(ctx, updateAssetExecution,
		arg.InstanceID,
		arg.Execution,
		arg.Cpu,
		arg.MemoryMib,
		arg.DiskGib,
	)
	return err
}

const updateAssetResult = `-- name: UpdateAssetResult :exec
UPDATE runtime_assets SET state=$2,error=$3,observed_at=$4 WHERE instance_id=$1
`

type UpdateAssetResultParams struct {
	InstanceID string
	State      string
	Error      *string
	ObservedAt pgtype.Timestamptz
}

func (q *Queries) UpdateAssetResult(ctx context.Context, arg UpdateAssetResultParams) error {
	_, err := q.db.Exec(ctx, updateAssetResult,
		arg.InstanceID,
		arg.State,
		arg.Error,
		arg.ObservedAt,
	)
	return err
}

const updateExecutions = `-- name: UpdateExecutions :exec
UPDATE runtime_assets a SET execution=r.execution,cpu=r.cpu,memory_mib=r."memoryMiB",disk_gib=r."diskGiB"
FROM jsonb_to_recordset($1::jsonb) AS r("instanceId" text,execution jsonb,cpu integer,"memoryMiB" bigint,"diskGiB" bigint)
WHERE a.instance_id=r."instanceId"
`

func (q *Queries) UpdateExecutions(ctx context.Context, dollar_1 []byte) error {
	_, err := q.db.Exec(ctx, updateExecutions, dollar_1)
	return err
}

const updateTemplate = `-- name: UpdateTemplate :exec
UPDATE templates SET definition=$2 WHERE id=$1
`

type UpdateTemplateParams struct {
	ID         string
	Definition []byte
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.Exec(ctx, updateTemplate, arg.ID, arg.Definition)
	return err
}
