// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recovery.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeRecoveryPoint = `-- name: CompleteRecoveryPoint :exec
UPDATE recovery_points SET state=$2,definition=$3,size_bytes=$4 WHERE id=$1
`

type CompleteRecoveryPointParams struct {
	ID         string
	State      string
	Definition []byte
	SizeBytes  int64
}

func (q *Queries) CompleteRecoveryPoint(ctx context.Context, arg CompleteRecoveryPointParams) error {
	_, err := q.db.Exec(ctx, completeRecoveryPoint,
		arg.ID,
		arg.State,
		arg.Definition,
		arg.SizeBytes,
	)
	return err
}

const createRecoveryPoint = `-- name: CreateRecoveryPoint :exec
INSERT INTO recovery_points(id,environment_id,name,revision,definition,asset_count,operation_id) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type CreateRecoveryPointParams struct {
	ID            string
	EnvironmentID string
	Name          string
	Revision      int32
	Definition    []byte
	AssetCount    int32
	OperationID   string
}

func (q *Queries) CreateRecoveryPoint(ctx context.Context, arg CreateRecoveryPointParams) error {
	_, err := q.db.Exec(ctx, createRecoveryPoint,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.Revision,
		arg.Definition,
		arg.AssetCount,
		arg.OperationID,
	)
	return err
}

const deleteRecoveryPoint = `-- name: DeleteRecoveryPoint :exec
DELETE FROM recovery_points WHERE id=$1
`

func (q *Queries) DeleteRecoveryPoint(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRecoveryPoint, id)
	return err
}

const getRecoveryPoint = `-- name: GetRecoveryPoint :one
SELECT id, environment_id, name, revision, state, definition, asset_count, size_bytes, operation_id, created_at FROM recovery_points WHERE id=$1
`

func (q *Queries) GetRecoveryPoint(ctx context.Context, id string) (RecoveryPoint, error) {
	row := q.db.QueryRow(ctx, getRecoveryPoint, id)
	var i RecoveryPoint
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Revision,
		&i.State,
		&i.Definition,
		&i.AssetCount,
		&i.SizeBytes,
		&i.OperationID,
		&i.CreatedAt,
	)
	return i, err
}

const listRecoveryPoints = `-- name: ListRecoveryPoints :many
SELECT p.id,p.environment_id,p.name,p.revision,p.state,p.asset_count,p.size_bytes,p.operation_id,p.created_at,o.error,
CASE WHEN p.state='ready' AND p.definition->>'includeMemory'='true' THEN
  (SELECT count(*)::int FROM jsonb_array_elements(p.definition->'assets') a
   WHERE a->'execution'->'template'->>'kind'='vm' AND a->>'state' IN ('running','suspended'))
ELSE 0 END::int AS memory_asset_count
FROM recovery_points p JOIN operations o ON o.id=p.operation_id
WHERE p.environment_id=$1
AND ($2::text='' OR (p.created_at,p.id)<(SELECT created_at,id FROM recovery_points WHERE id=$2))
ORDER BY p.created_at DESC,p.id DESC LIMIT $3
`

type ListRecoveryPointsParams struct {
	EnvironmentID string
	Cursor        string
	PageLimit     int32
}

type ListRecoveryPointsRow struct {
	ID               string
	EnvironmentID    string
	Name             string
	Revision         int32
	State            string
	AssetCount       int32
	SizeBytes        int64
	OperationID      string
	CreatedAt        pgtype.Timestamptz
	Error            *string
	MemoryAssetCount int32
}

func (q *Queries) ListRecoveryPoints(ctx context.Context, arg ListRecoveryPointsParams) ([]ListRecoveryPointsRow, error) {
	rows, err := q.db.Query(ctx, listRecoveryPoints, arg.EnvironmentID, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecoveryPointsRow{}
	for rows.Next() {
		var i ListRecoveryPointsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Revision,
			&i.State,
			&i.AssetCount,
			&i.SizeBytes,
			&i.OperationID,
			&i.CreatedAt,
			&i.Error,
			&i.MemoryAssetCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRecoveryPoint = `-- name: LockRecoveryPoint :one
SELECT id, environment_id, name, revision, state, definition, asset_count, size_bytes, operation_id, created_at FROM recovery_points WHERE id=$1 AND environment_id=$2 FOR UPDATE
`

type LockRecoveryPointParams struct {
	ID            string
	EnvironmentID string
}

func (q *Queries) LockRecoveryPoint(ctx context.Context, arg LockRecoveryPointParams) (RecoveryPoint, error) {
	row := q.db.QueryRow(ctx, lockRecoveryPoint, arg.ID, arg.EnvironmentID)
	var i RecoveryPoint
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Revision,
		&i.State,
		&i.Definition,
		&i.AssetCount,
		&i.SizeBytes,
		&i.OperationID,
		&i.CreatedAt,
	)
	return i, err
}

const markRecoveryCapturing = `-- name: MarkRecoveryCapturing :exec
UPDATE recovery_points SET state='capturing' WHERE id=$1
`

func (q *Queries) MarkRecoveryCapturing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markRecoveryCapturing, id)
	return err
}

const markRecoveryDeleting = `-- name: MarkRecoveryDeleting :exec
UPDATE recovery_points SET state='deleting',operation_id=$2 WHERE id=$1
`

type MarkRecoveryDeletingParams struct {
	ID          string
	OperationID string
}

func (q *Queries) MarkRecoveryDeleting(ctx context.Context, arg MarkRecoveryDeletingParams) error {
	_, err := q.db.Exec(ctx, markRecoveryDeleting, arg.ID, arg.OperationID)
	return err
}

const recoveryPointInUse = `-- name: RecoveryPointInUse :one
SELECT EXISTS(SELECT 1 FROM operations o WHERE o.payload->'recovery'->>'id'=$1::text
AND (NOT (o.payload ? 'backupId') OR o.kind='create-backup')
AND (o.state IN ('queued','running') OR (o.phase IN ('rollback','cleanup') AND o.state IN ('failed','partially_applied'))
OR (o.kind='create-backup' AND o.state='failed' AND EXISTS(SELECT 1 FROM backups b WHERE b.operation_id=o.id))))
`

func (q *Queries) RecoveryPointInUse(ctx context.Context, dollar_1 string) (bool, error) {
	row := q.db.QueryRow(ctx, recoveryPointInUse, dollar_1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setRecoveryDeleteOperation = `-- name: SetRecoveryDeleteOperation :exec
UPDATE environments SET operation_id=$2,updated_at=now() WHERE id=$1
`

type SetRecoveryDeleteOperationParams struct {
	ID          string
	OperationID *string
}

func (q *Queries) SetRecoveryDeleteOperation(ctx context.Context, arg SetRecoveryDeleteOperationParams) error {
	_, err := q.db.Exec(ctx, setRecoveryDeleteOperation, arg.ID, arg.OperationID)
	return err
}
