// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: retirement.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelNodeRetirement = `-- name: CancelNodeRetirement :exec
UPDATE operations SET state='failed',phase='cancelled',error='已恢复节点调度',updated_at=now()
WHERE scope_kind='node' AND scope_id=$1 AND kind='retire-node' AND state IN ('queued','failed','partially_applied')
`

func (q *Queries) CancelNodeRetirement(ctx context.Context, scopeID string) error {
	_, err := q.db.Exec(ctx, cancelNodeRetirement, scopeID)
	return err
}

const claimOperationByID = `-- name: ClaimOperationByID :one
UPDATE operations o SET state='running',lease_owner=$1,lease_until=now()+interval '30 seconds',updated_at=now()
WHERE o.id=$2 AND (o.state='queued' OR o.state='running' AND o.lease_until<now())
AND NOT EXISTS(SELECT 1 FROM operations active WHERE active.id<>o.id AND active.scope_kind=o.scope_kind AND active.scope_id=o.scope_id AND active.state='running')
RETURNING id, environment_id, scope_kind, scope_id, kind, asset_id, state, phase, payload, results, error, expected_revision, lease_owner, lease_until, created_at, updated_at, client_request_id
`

type ClaimOperationByIDParams struct {
	Owner *string
	ID    string
}

func (q *Queries) ClaimOperationByID(ctx context.Context, arg ClaimOperationByIDParams) (Operation, error) {
	row := q.db.QueryRow(ctx, claimOperationByID, arg.Owner, arg.ID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Kind,
		&i.AssetID,
		&i.State,
		&i.Phase,
		&i.Payload,
		&i.Results,
		&i.Error,
		&i.ExpectedRevision,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientRequestID,
	)
	return i, err
}

const deleteRetiredNode = `-- name: DeleteRetiredNode :exec
WITH historical_environments AS (UPDATE environments SET network_node_id=NULL,gateway_address=NULL WHERE network_node_id=$1 AND status='destroyed')
DELETE FROM nodes n WHERE n.id=$1 AND n.retiring
`

func (q *Queries) DeleteRetiredNode(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRetiredNode, id)
	return err
}

const drainNode = `-- name: DrainNode :exec
UPDATE nodes SET retiring=true WHERE id=$1
`

func (q *Queries) DrainNode(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, drainNode, id)
	return err
}

const nodeArtifactTemplates = `-- name: NodeArtifactTemplates :many
SELECT DISTINCT definition::jsonb FROM (
 SELECT definition FROM templates
 UNION SELECT execution->'template' FROM runtime_assets
 UNION SELECT a->'execution'->'template' FROM recovery_points p CROSS JOIN LATERAL jsonb_array_elements(p.definition->'assets') a
 UNION SELECT a->'execution'->'template' FROM backups b CROSS JOIN LATERAL jsonb_array_elements(b.definition->'recovery'->'assets') a
 UNION SELECT t FROM operations o CROSS JOIN LATERAL jsonb_path_query(o.payload,'$.**.template') t WHERE o.phase NOT IN ('complete','rolled-back','cancelled')
) versions WHERE definition->>'artifactNodeId'=$1::text
`

func (q *Queries) NodeArtifactTemplates(ctx context.Context, dollar_1 string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, nodeArtifactTemplates, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var definition []byte
		if err := rows.Scan(&definition); err != nil {
			return nil, err
		}
		items = append(items, definition)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeAssets = `-- name: NodeAssets :many
SELECT a.environment_id, a.asset_id, a.instance_id, a.node_id, a.execution, a.state, a.cpu, a.memory_mib, a.disk_gib, a.current, a.error, a.observed_at,e.name AS environment_name,e.revision FROM runtime_assets a JOIN environments e ON e.id=a.environment_id
WHERE a.node_id=$1 ORDER BY a.environment_id,a.asset_id
`

type NodeAssetsRow struct {
	EnvironmentID   string
	AssetID         string
	InstanceID      string
	NodeID          string
	Execution       []byte
	State           string
	Cpu             int32
	MemoryMib       int64
	DiskGib         int64
	Current         bool
	Error           *string
	ObservedAt      pgtype.Timestamptz
	EnvironmentName string
	Revision        int32
}

func (q *Queries) NodeAssets(ctx context.Context, nodeID string) ([]NodeAssetsRow, error) {
	rows, err := q.db.Query(ctx, nodeAssets, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeAssetsRow{}
	for rows.Next() {
		var i NodeAssetsRow
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.AssetID,
			&i.InstanceID,
			&i.NodeID,
			&i.Execution,
			&i.State,
			&i.Cpu,
			&i.MemoryMib,
			&i.DiskGib,
			&i.Current,
			&i.Error,
			&i.ObservedAt,
			&i.EnvironmentName,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeDependencies = `-- name: NodeDependencies :many
SELECT name::text FROM (
 SELECT '外部 LAN：'||e.name AS name FROM external_network_leases x JOIN environments e ON e.id=x.environment_id WHERE x.node_id=$1::text
 UNION SELECT '备份仓库：'||name FROM backup_repositories WHERE node_id=$1
 UNION SELECT '抓包文件：'||e.name FROM capture_segments c JOIN environments e ON e.id=c.environment_id WHERE c.node_id=$1
 UNION SELECT '恢复点：'||p.name FROM recovery_points p CROSS JOIN LATERAL jsonb_array_elements(p.definition->'assets') a
 WHERE a->>'nodeId'=$1
 UNION SELECT '未挂载数据卷：'||v.name FROM persistent_volumes v WHERE v.node_id=$1
 AND NOT EXISTS(SELECT 1 FROM runtime_assets a WHERE a.current AND a.node_id=v.node_id
 AND EXISTS(SELECT 1 FROM jsonb_each(a.execution->'volumeSources') source WHERE source.value->>'id'=v.id))
 UNION SELECT '待完成操作：'||COALESCE(e.name,o.kind) FROM operations o LEFT JOIN environments e ON e.id=o.environment_id
 WHERE o.state IN ('queued','running') AND o.kind<>'retire-node' AND (
 (o.scope_kind='node' AND o.scope_id=$1) OR
 EXISTS(SELECT 1 FROM runtime_assets a WHERE a.environment_id=o.environment_id AND a.node_id=$1) OR
 e.network_node_id=$1 OR
 jsonb_path_exists(o.payload,'$.**.artifactNodeId ? (@ == $node)',jsonb_build_object('node',$1::text)) OR
 EXISTS(SELECT 1 FROM storage_pools p WHERE p.id=o.scope_id AND o.scope_kind='storage-pool' AND $1=ANY(p.node_ids)))
) dependencies ORDER BY name
`

func (q *Queries) NodeDependencies(ctx context.Context, nodeID string) ([]string, error) {
	rows, err := q.db.Query(ctx, nodeDependencies, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeNetworkEnvironments = `-- name: NodeNetworkEnvironments :many
SELECT id, project_id, owner_id, name, external_reference, revision, status, spec, applied_spec, view, draft, network_node_id, operation_id, error, client_request_id, created_at, updated_at, blueprint_version_id, gateway_address, vpn_public_key, vpn_mtu FROM environments e WHERE status<>'destroyed' AND (network_node_id=$1 OR EXISTS(
 SELECT 1 FROM operations o WHERE o.environment_id=e.id AND o.kind='move-network'
 AND o.payload->>'networkSource'=$1::text AND o.phase NOT IN ('complete','cancelled'))) ORDER BY id
`

func (q *Queries) NodeNetworkEnvironments(ctx context.Context, networkNodeID *string) ([]Environment, error) {
	rows, err := q.db.Query(ctx, nodeNetworkEnvironments, networkNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OwnerID,
			&i.Name,
			&i.ExternalReference,
			&i.Revision,
			&i.Status,
			&i.Spec,
			&i.AppliedSpec,
			&i.View,
			&i.Draft,
			&i.NetworkNodeID,
			&i.OperationID,
			&i.Error,
			&i.ClientRequestID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlueprintVersionID,
			&i.GatewayAddress,
			&i.VpnPublicKey,
			&i.VpnMtu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeOperation = `-- name: NodeOperation :one
SELECT id, environment_id, scope_kind, scope_id, kind, asset_id, state, phase, payload, results, error, expected_revision, lease_owner, lease_until, created_at, updated_at, client_request_id FROM operations WHERE scope_kind='node' AND scope_id=$1 ORDER BY created_at DESC,id DESC LIMIT 1
`

func (q *Queries) NodeOperation(ctx context.Context, scopeID string) (Operation, error) {
	row := q.db.QueryRow(ctx, nodeOperation, scopeID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Kind,
		&i.AssetID,
		&i.State,
		&i.Phase,
		&i.Payload,
		&i.Results,
		&i.Error,
		&i.ExpectedRevision,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientRequestID,
	)
	return i, err
}

const relocateTemplateArtifacts = `-- name: RelocateTemplateArtifacts :exec
WITH templates_updated AS (
 UPDATE templates SET definition=relocate_template_artifacts(definition,$1::text,$2::text) WHERE definition->>'artifactNodeId'=$1
), assets_updated AS (
 UPDATE runtime_assets SET execution=relocate_template_artifacts(execution,$1,$2) WHERE execution->'template'->>'artifactNodeId'=$1
), recoveries_updated AS (
 UPDATE recovery_points SET definition=relocate_template_artifacts(definition,$1,$2) WHERE jsonb_path_exists(definition,'$.**.artifactNodeId ? (@ == $node)',jsonb_build_object('node',$1::text))
), backups_updated AS (
 UPDATE backups SET definition=relocate_template_artifacts(definition,$1,$2) WHERE jsonb_path_exists(definition,'$.**.artifactNodeId ? (@ == $node)',jsonb_build_object('node',$1::text))
)
UPDATE operations SET payload=relocate_template_artifacts(payload,$1,$2) WHERE kind<>'retire-node' AND phase NOT IN ('complete','rolled-back','cancelled')
AND jsonb_path_exists(payload,'$.**.artifactNodeId ? (@ == $node)',jsonb_build_object('node',$1::text))
`

type RelocateTemplateArtifactsParams struct {
	Source string
	Target string
}

func (q *Queries) RelocateTemplateArtifacts(ctx context.Context, arg RelocateTemplateArtifactsParams) error {
	_, err := q.db.Exec(ctx, relocateTemplateArtifacts, arg.Source, arg.Target)
	return err
}

const resumeNode = `-- name: ResumeNode :exec
UPDATE nodes SET retiring=false WHERE id=$1
`

func (q *Queries) ResumeNode(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, resumeNode, id)
	return err
}
