// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: services.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyServicePorts = `-- name: ApplyServicePorts :exec
UPDATE service_ports p SET state='applied',port=b."listenPort",updated_at=now()
FROM jsonb_to_recordset($2::jsonb) AS b(id text,protocol text,"listenPort" integer)
WHERE p.environment_id=$1 AND b.id=p.service_id AND b.protocol=p.protocol AND (b."listenPort"=p.port OR p.port IS NULL)
`

type ApplyServicePortsParams struct {
	EnvironmentID string
	Bindings      []byte
}

func (q *Queries) ApplyServicePorts(ctx context.Context, arg ApplyServicePortsParams) error {
	_, err := q.db.Exec(ctx, applyServicePorts, arg.EnvironmentID, arg.Bindings)
	return err
}

const deleteUnusedServicePorts = `-- name: DeleteUnusedServicePorts :exec
DELETE FROM service_ports p WHERE p.environment_id=$1
 AND NOT EXISTS(SELECT 1 FROM jsonb_to_recordset($2::jsonb) AS b(id text,protocol text,"listenPort" integer)
 WHERE b.id=p.service_id AND b.protocol=p.protocol AND (b."listenPort"=p.port OR p.port IS NULL))
`

type DeleteUnusedServicePortsParams struct {
	EnvironmentID string
	Bindings      []byte
}

func (q *Queries) DeleteUnusedServicePorts(ctx context.Context, arg DeleteUnusedServicePortsParams) error {
	_, err := q.db.Exec(ctx, deleteUnusedServicePorts, arg.EnvironmentID, arg.Bindings)
	return err
}

const getAppliedServicePorts = `-- name: GetAppliedServicePorts :many
SELECT p.id, p.node_id, p.protocol, p.port, p.environment_id, p.service_id, p.operation_id, p.state, p.updated_at,n.endpoint FROM service_ports p JOIN nodes n ON n.id=p.node_id WHERE p.environment_id=$1 AND p.state='applied' ORDER BY p.service_id
`

type GetAppliedServicePortsRow struct {
	ID            int64
	NodeID        string
	Protocol      string
	Port          *int32
	EnvironmentID string
	ServiceID     string
	OperationID   string
	State         string
	UpdatedAt     pgtype.Timestamptz
	Endpoint      string
}

func (q *Queries) GetAppliedServicePorts(ctx context.Context, environmentID string) ([]GetAppliedServicePortsRow, error) {
	rows, err := q.db.Query(ctx, getAppliedServicePorts, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAppliedServicePortsRow{}
	for rows.Next() {
		var i GetAppliedServicePortsRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Protocol,
			&i.Port,
			&i.EnvironmentID,
			&i.ServiceID,
			&i.OperationID,
			&i.State,
			&i.UpdatedAt,
			&i.Endpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServicePorts = `-- name: GetServicePorts :many
SELECT id, node_id, protocol, port, environment_id, service_id, operation_id, state, updated_at FROM service_ports WHERE environment_id=$1 ORDER BY service_id,protocol,port
`

func (q *Queries) GetServicePorts(ctx context.Context, environmentID string) ([]ServicePort, error) {
	rows, err := q.db.Query(ctx, getServicePorts, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServicePort{}
	for rows.Next() {
		var i ServicePort
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Protocol,
			&i.Port,
			&i.EnvironmentID,
			&i.ServiceID,
			&i.OperationID,
			&i.State,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayAddresses = `-- name: ListGatewayAddresses :many
SELECT host(gateway_address)::text AS address FROM environments WHERE network_node_id=$1 AND gateway_address IS NOT NULL
`

func (q *Queries) ListGatewayAddresses(ctx context.Context, networkNodeID *string) ([]string, error) {
	rows, err := q.db.Query(ctx, listGatewayAddresses, networkNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseServicePorts = `-- name: ReleaseServicePorts :exec
DELETE FROM service_ports WHERE environment_id=$1
`

func (q *Queries) ReleaseServicePorts(ctx context.Context, environmentID string) error {
	_, err := q.db.Exec(ctx, releaseServicePorts, environmentID)
	return err
}

const reserveAppliedServicePorts = `-- name: ReserveAppliedServicePorts :exec
UPDATE service_ports SET state='reserved',operation_id=$1 WHERE environment_id=$2
 AND service_id=ANY($3::text[])
`

type ReserveAppliedServicePortsParams struct {
	OperationID   string
	EnvironmentID string
	ServiceIds    []string
}

func (q *Queries) ReserveAppliedServicePorts(ctx context.Context, arg ReserveAppliedServicePortsParams) error {
	_, err := q.db.Exec(ctx, reserveAppliedServicePorts, arg.OperationID, arg.EnvironmentID, arg.ServiceIds)
	return err
}

const reserveServicePort = `-- name: ReserveServicePort :one
INSERT INTO service_ports(node_id,protocol,port,environment_id,service_id,operation_id,state)
VALUES($1,$2,NULLIF($3::integer,0),$4,$5,$6,'reserved') RETURNING id, node_id, protocol, port, environment_id, service_id, operation_id, state, updated_at
`

type ReserveServicePortParams struct {
	NodeID        string
	Protocol      string
	RequestedPort int32
	EnvironmentID string
	ServiceID     string
	OperationID   string
}

func (q *Queries) ReserveServicePort(ctx context.Context, arg ReserveServicePortParams) (ServicePort, error) {
	row := q.db.QueryRow(ctx, reserveServicePort,
		arg.NodeID,
		arg.Protocol,
		arg.RequestedPort,
		arg.EnvironmentID,
		arg.ServiceID,
		arg.OperationID,
	)
	var i ServicePort
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Protocol,
		&i.Port,
		&i.EnvironmentID,
		&i.ServiceID,
		&i.OperationID,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const setGatewayAddress = `-- name: SetGatewayAddress :exec
UPDATE environments SET gateway_address=$1::inet WHERE id=$2
`

type SetGatewayAddressParams struct {
	Address       *netip.Addr
	EnvironmentID string
}

func (q *Queries) SetGatewayAddress(ctx context.Context, arg SetGatewayAddressParams) error {
	_, err := q.db.Exec(ctx, setGatewayAddress, arg.Address, arg.EnvironmentID)
	return err
}
