// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: storage.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStoragePool = `-- name: CreateStoragePool :exec
INSERT INTO storage_pools(id,node_id,name,directory,path) VALUES($1,$2,$3,$4,$5)
`

type CreateStoragePoolParams struct {
	ID        string
	NodeID    string
	Name      string
	Directory string
	Path      string
}

func (q *Queries) CreateStoragePool(ctx context.Context, arg CreateStoragePoolParams) error {
	_, err := q.db.Exec(ctx, createStoragePool,
		arg.ID,
		arg.NodeID,
		arg.Name,
		arg.Directory,
		arg.Path,
	)
	return err
}

const deleteStoragePool = `-- name: DeleteStoragePool :exec
DELETE FROM storage_pools WHERE id=$1
`

func (q *Queries) DeleteStoragePool(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteStoragePool, id)
	return err
}

const getStoragePool = `-- name: GetStoragePool :one
SELECT id, node_id, name, directory, path, state, operation_id, created_at FROM storage_pools WHERE id=$1
`

func (q *Queries) GetStoragePool(ctx context.Context, id string) (StoragePool, error) {
	row := q.db.QueryRow(ctx, getStoragePool, id)
	var i StoragePool
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Directory,
		&i.Path,
		&i.State,
		&i.OperationID,
		&i.CreatedAt,
	)
	return i, err
}

const listStoragePools = `-- name: ListStoragePools :many
SELECT s.id, s.node_id, s.name, s.directory, s.path, s.state, s.operation_id, s.created_at,o.error AS operation_error FROM storage_pools s LEFT JOIN operations o ON o.id=s.operation_id ORDER BY s.node_id,s.id
`

type ListStoragePoolsRow struct {
	ID             string
	NodeID         string
	Name           string
	Directory      string
	Path           string
	State          string
	OperationID    *string
	CreatedAt      pgtype.Timestamptz
	OperationError *string
}

func (q *Queries) ListStoragePools(ctx context.Context) ([]ListStoragePoolsRow, error) {
	rows, err := q.db.Query(ctx, listStoragePools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoragePoolsRow{}
	for rows.Next() {
		var i ListStoragePoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Directory,
			&i.Path,
			&i.State,
			&i.OperationID,
			&i.CreatedAt,
			&i.OperationError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStoragePool = `-- name: LockStoragePool :one
SELECT id, node_id, name, directory, path, state, operation_id, created_at FROM storage_pools WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockStoragePool(ctx context.Context, id string) (StoragePool, error) {
	row := q.db.QueryRow(ctx, lockStoragePool, id)
	var i StoragePool
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Directory,
		&i.Path,
		&i.State,
		&i.OperationID,
		&i.CreatedAt,
	)
	return i, err
}

const lockStoragePools = `-- name: LockStoragePools :many
SELECT id, node_id, name, directory, path, state, operation_id, created_at FROM storage_pools WHERE id=ANY($1::text[]) ORDER BY id FOR KEY SHARE
`

func (q *Queries) LockStoragePools(ctx context.Context, dollar_1 []string) ([]StoragePool, error) {
	rows, err := q.db.Query(ctx, lockStoragePools, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoragePool{}
	for rows.Next() {
		var i StoragePool
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Directory,
			&i.Path,
			&i.State,
			&i.OperationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStorageDeleting = `-- name: MarkStorageDeleting :exec
UPDATE storage_pools SET state='deleting',operation_id=$2 WHERE id=$1
`

type MarkStorageDeletingParams struct {
	ID          string
	OperationID *string
}

func (q *Queries) MarkStorageDeleting(ctx context.Context, arg MarkStorageDeletingParams) error {
	_, err := q.db.Exec(ctx, markStorageDeleting, arg.ID, arg.OperationID)
	return err
}

const storageReferences = `-- name: StorageReferences :many
SELECT name::text FROM (
 SELECT '环境：'||e.name AS name FROM environments e WHERE e.status<>'destroyed' AND (
  e.spec @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('storagePoolId',$1::text))) OR
  e.applied_spec @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('storagePoolId',$1::text))) OR
  e.draft->'spec' @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('storagePoolId',$1::text))))
 UNION SELECT '运行资产：'||e.name FROM runtime_assets a JOIN environments e ON e.id=a.environment_id
 WHERE a.execution->>'storagePoolId'=$1
 UNION SELECT '环境模板：'||b.name||' v'||v.version::text FROM blueprint_versions v JOIN blueprints b ON b.id=v.blueprint_id
 WHERE v.spec @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('storagePoolId',$1::text)))
 UNION SELECT '恢复点：'||p.name FROM recovery_points p
 CROSS JOIN LATERAL jsonb_array_elements(p.definition->'assets') a(value)
 WHERE a.value->'execution'->>'storagePoolId'=$1
 UNION SELECT '待执行任务：'||COALESCE(e.name,o.kind) FROM operations o LEFT JOIN environments e ON e.id=o.environment_id
 WHERE o.state IN ('queued','running') AND (
  o.payload->'spec' @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('storagePoolId',$1::text))) OR
  o.payload->'beforeSpec' @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('storagePoolId',$1::text))))
) refs ORDER BY name
`

func (q *Queries) StorageReferences(ctx context.Context, poolID string) ([]string, error) {
	rows, err := q.db.Query(ctx, storageReferences, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storageReservations = `-- name: StorageReservations :many
WITH assets AS (
 SELECT node_id,environment_id,asset_id,execution,disk_gib,COALESCE(execution->>'storagePoolId','')::text AS pool_id
 FROM runtime_assets WHERE node_id=ANY($1::text[])
), allocations AS (
 SELECT node_id,pool_id,sum(disk_gib)::bigint AS disk_gib FROM assets GROUP BY node_id,pool_id
 UNION ALL
 SELECT node_id,pool_id,-sum(reused)::bigint FROM (
  SELECT a.node_id,a.pool_id,a.environment_id,a.asset_id,v->>'id' AS volume_id,sum((v->>'sizeGiB')::bigint)-max((v->>'sizeGiB')::bigint) AS reused
  FROM assets a CROSS JOIN LATERAL jsonb_array_elements(a.execution->'asset'->'volumes') v
  GROUP BY a.node_id,a.pool_id,a.environment_id,a.asset_id,COALESCE(a.execution->>'dataSetId',''),v->>'id'
 ) volumes GROUP BY node_id,pool_id
)
SELECT node_id,pool_id,sum(disk_gib)::bigint AS disk_gib FROM allocations GROUP BY node_id,pool_id
`

type StorageReservationsRow struct {
	NodeID  string
	PoolID  string
	DiskGib int64
}

func (q *Queries) StorageReservations(ctx context.Context, dollar_1 []string) ([]StorageReservationsRow, error) {
	rows, err := q.db.Query(ctx, storageReservations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageReservationsRow{}
	for rows.Next() {
		var i StorageReservationsRow
		if err := rows.Scan(&i.NodeID, &i.PoolID, &i.DiskGib); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
