// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: storage.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const configureManagedStorage = `-- name: ConfigureManagedStorage :exec
UPDATE storage_pools SET operation_id=$2 WHERE id=$1
`

type ConfigureManagedStorageParams struct {
	ID          string
	OperationID *string
}

func (q *Queries) ConfigureManagedStorage(ctx context.Context, arg ConfigureManagedStorageParams) error {
	_, err := q.db.Exec(ctx, configureManagedStorage, arg.ID, arg.OperationID)
	return err
}

const createManagedStorage = `-- name: CreateManagedStorage :exec
INSERT INTO storage_pools(id,node_ids,name,driver,directory,path,state,operation_id,managed)
VALUES($1,$2,'共享存储','rbd','','','preparing',$3,true)
`

type CreateManagedStorageParams struct {
	ID          string
	NodeIds     []string
	OperationID *string
}

func (q *Queries) CreateManagedStorage(ctx context.Context, arg CreateManagedStorageParams) error {
	_, err := q.db.Exec(ctx, createManagedStorage, arg.ID, arg.NodeIds, arg.OperationID)
	return err
}

const createStoragePool = `-- name: CreateStoragePool :exec
INSERT INTO storage_pools(id,node_ids,name,driver,directory,path) VALUES($1,$2,$3,$4,$5,$6)
`

type CreateStoragePoolParams struct {
	ID        string
	NodeIds   []string
	Name      string
	Driver    string
	Directory string
	Path      string
}

func (q *Queries) CreateStoragePool(ctx context.Context, arg CreateStoragePoolParams) error {
	_, err := q.db.Exec(ctx, createStoragePool,
		arg.ID,
		arg.NodeIds,
		arg.Name,
		arg.Driver,
		arg.Directory,
		arg.Path,
	)
	return err
}

const deleteStoragePool = `-- name: DeleteStoragePool :exec
DELETE FROM storage_pools WHERE id=$1
`

func (q *Queries) DeleteStoragePool(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteStoragePool, id)
	return err
}

const finishManagedStorage = `-- name: FinishManagedStorage :exec
UPDATE storage_pools SET node_ids=$2,path=$3,state='ready' WHERE id=$1
`

type FinishManagedStorageParams struct {
	ID      string
	NodeIds []string
	Path    string
}

func (q *Queries) FinishManagedStorage(ctx context.Context, arg FinishManagedStorageParams) error {
	_, err := q.db.Exec(ctx, finishManagedStorage, arg.ID, arg.NodeIds, arg.Path)
	return err
}

const getStoragePool = `-- name: GetStoragePool :one
SELECT id, name, directory, path, state, operation_id, created_at, node_ids, driver, managed FROM storage_pools WHERE id=$1
`

func (q *Queries) GetStoragePool(ctx context.Context, id string) (StoragePool, error) {
	row := q.db.QueryRow(ctx, getStoragePool, id)
	var i StoragePool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Directory,
		&i.Path,
		&i.State,
		&i.OperationID,
		&i.CreatedAt,
		&i.NodeIds,
		&i.Driver,
		&i.Managed,
	)
	return i, err
}

const listStoragePools = `-- name: ListStoragePools :many
SELECT s.id, s.name, s.directory, s.path, s.state, s.operation_id, s.created_at, s.node_ids, s.driver, s.managed,o.error AS operation_error,o.state AS operation_state FROM storage_pools s LEFT JOIN operations o ON o.id=s.operation_id ORDER BY s.id
`

type ListStoragePoolsRow struct {
	ID             string
	Name           string
	Directory      string
	Path           string
	State          string
	OperationID    *string
	CreatedAt      pgtype.Timestamptz
	NodeIds        []string
	Driver         string
	Managed        bool
	OperationError *string
	OperationState *string
}

func (q *Queries) ListStoragePools(ctx context.Context) ([]ListStoragePoolsRow, error) {
	rows, err := q.db.Query(ctx, listStoragePools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoragePoolsRow{}
	for rows.Next() {
		var i ListStoragePoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Directory,
			&i.Path,
			&i.State,
			&i.OperationID,
			&i.CreatedAt,
			&i.NodeIds,
			&i.Driver,
			&i.Managed,
			&i.OperationError,
			&i.OperationState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStoragePool = `-- name: LockStoragePool :one
SELECT id, name, directory, path, state, operation_id, created_at, node_ids, driver, managed FROM storage_pools WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockStoragePool(ctx context.Context, id string) (StoragePool, error) {
	row := q.db.QueryRow(ctx, lockStoragePool, id)
	var i StoragePool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Directory,
		&i.Path,
		&i.State,
		&i.OperationID,
		&i.CreatedAt,
		&i.NodeIds,
		&i.Driver,
		&i.Managed,
	)
	return i, err
}

const lockStoragePools = `-- name: LockStoragePools :many
SELECT id, name, directory, path, state, operation_id, created_at, node_ids, driver, managed FROM storage_pools WHERE id=ANY($1::text[]) ORDER BY id FOR KEY SHARE
`

func (q *Queries) LockStoragePools(ctx context.Context, dollar_1 []string) ([]StoragePool, error) {
	rows, err := q.db.Query(ctx, lockStoragePools, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoragePool{}
	for rows.Next() {
		var i StoragePool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Directory,
			&i.Path,
			&i.State,
			&i.OperationID,
			&i.CreatedAt,
			&i.NodeIds,
			&i.Driver,
			&i.Managed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStorageDeleting = `-- name: MarkStorageDeleting :exec
UPDATE storage_pools SET state='deleting',operation_id=$2 WHERE id=$1
`

type MarkStorageDeletingParams struct {
	ID          string
	OperationID *string
}

func (q *Queries) MarkStorageDeleting(ctx context.Context, arg MarkStorageDeletingParams) error {
	_, err := q.db.Exec(ctx, markStorageDeleting, arg.ID, arg.OperationID)
	return err
}

const nodeStorageOperation = `-- name: NodeStorageOperation :one
SELECT id, environment_id, scope_kind, scope_id, kind, asset_id, state, phase, payload, results, error, expected_revision, lease_owner, lease_until, created_at, updated_at, client_request_id FROM operations WHERE scope_kind='node' AND scope_id=$1 AND kind='configure-node-storage' ORDER BY created_at DESC,id DESC LIMIT 1
`

func (q *Queries) NodeStorageOperation(ctx context.Context, scopeID string) (Operation, error) {
	row := q.db.QueryRow(ctx, nodeStorageOperation, scopeID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Kind,
		&i.AssetID,
		&i.State,
		&i.Phase,
		&i.Payload,
		&i.Results,
		&i.Error,
		&i.ExpectedRevision,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientRequestID,
	)
	return i, err
}

const storagePoolAssets = `-- name: StoragePoolAssets :many
SELECT e.id AS environment_id,e.name AS environment_name,e.revision,a.asset_id,
(a.execution->'asset'->>'name')::text AS asset_name,a.node_id,a.disk_gib AS size_gib,a.state
FROM runtime_assets a JOIN environments e ON e.id=a.environment_id
WHERE a.current AND COALESCE(a.execution->>'storagePoolId','default:'||a.node_id)=$1::text
ORDER BY e.name,a.asset_id
`

type StoragePoolAssetsRow struct {
	EnvironmentID   string
	EnvironmentName string
	Revision        int32
	AssetID         string
	AssetName       string
	NodeID          string
	SizeGib         int64
	State           string
}

func (q *Queries) StoragePoolAssets(ctx context.Context, poolID string) ([]StoragePoolAssetsRow, error) {
	rows, err := q.db.Query(ctx, storagePoolAssets, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoragePoolAssetsRow{}
	for rows.Next() {
		var i StoragePoolAssetsRow
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.Revision,
			&i.AssetID,
			&i.AssetName,
			&i.NodeID,
			&i.SizeGib,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storageReferences = `-- name: StorageReferences :many
SELECT name::text FROM (
 SELECT '环境：'||e.name AS name FROM environments e WHERE e.status<>'destroyed' AND (
  e.spec @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('storagePoolId',$1::text))) OR
  e.applied_spec @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('storagePoolId',$1::text))) OR
  e.draft->'spec' @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('storagePoolId',$1::text))))
 UNION SELECT '运行资产：'||e.name FROM runtime_assets a JOIN environments e ON e.id=a.environment_id
 WHERE a.execution->>'storagePoolId'=$1
 UNION SELECT '环境模板：'||b.name||' v'||v.version::text FROM blueprint_versions v JOIN blueprints b ON b.id=v.blueprint_id
 WHERE v.spec @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('storagePoolId',$1::text)))
 UNION SELECT '恢复点：'||p.name FROM recovery_points p
 CROSS JOIN LATERAL jsonb_array_elements(p.definition->'assets') a(value)
 WHERE a.value->'execution'->>'storagePoolId'=$1
 UNION SELECT '持久卷：'||v.name FROM persistent_volumes v WHERE v.storage_pool_id=$1
 UNION SELECT '迁移任务：'||e.name FROM operations o JOIN environments e ON e.id=o.environment_id
 CROSS JOIN LATERAL jsonb_array_elements(COALESCE(o.payload->'before','[]')||jsonb_build_array(o.payload->'migration'->'target')) t
 WHERE o.kind='migrate' AND o.phase NOT IN ('complete','rolled-back') AND (
  t->'execution'->>'storagePoolId'=$1 OR EXISTS(
   SELECT 1 FROM jsonb_each(t->'execution'->'volumeSources') volume
   WHERE volume.value->'storage'->'rbd'->>'secretId'=$1))
 UNION SELECT '待执行任务：'||COALESCE(e.name,o.kind) FROM operations o LEFT JOIN environments e ON e.id=o.environment_id
 WHERE o.state IN ('queued','running') AND (
  o.payload->'spec' @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('storagePoolId',$1::text))) OR
  o.payload->'beforeSpec' @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('storagePoolId',$1::text))))
) refs ORDER BY name
`

func (q *Queries) StorageReferences(ctx context.Context, poolID string) ([]string, error) {
	rows, err := q.db.Query(ctx, storageReferences, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storageReservations = `-- name: StorageReservations :many
WITH assets AS (
 SELECT node_id,environment_id,asset_id,execution,disk_gib,COALESCE(execution->>'storagePoolId','')::text AS pool_id
 FROM runtime_assets WHERE node_id=ANY($1::text[])
), allocations AS (
 SELECT node_id,pool_id,sum(disk_gib)::bigint AS disk_gib FROM assets GROUP BY node_id,pool_id
 UNION ALL
 SELECT node_id,COALESCE(execution->>'storagePoolId','')::text,(disk_gib+volume_gib)::bigint
 FROM migration_asset_reservations WHERE node_id=ANY($1::text[])
 UNION ALL
 SELECT node_id,pool_id,-sum(reused)::bigint FROM (
  SELECT a.node_id,a.pool_id,a.environment_id,a.asset_id,v->>'id' AS volume_id,sum((v->>'sizeGiB')::bigint)-max((v->>'sizeGiB')::bigint) AS reused
  FROM assets a CROSS JOIN LATERAL jsonb_array_elements(a.execution->'asset'->'volumes') v WHERE v->>'persistentVolumeId' IS NULL
  GROUP BY a.node_id,a.pool_id,a.environment_id,a.asset_id,COALESCE(a.execution->>'dataSetId',''),v->>'id'
 ) volumes GROUP BY node_id,pool_id
 UNION ALL SELECT v.node_id,CASE WHEN v.storage_pool_id LIKE 'default:%' THEN '' ELSE v.storage_pool_id END,
 sum(CASE WHEN o.kind='resize-volume' AND v.state<>'ready' THEN GREATEST(v.size_gib,(o.payload->'volume'->>'sizeGiB')::bigint) ELSE v.size_gib END)::bigint
 FROM persistent_volumes v LEFT JOIN operations o ON o.id=v.operation_id
 WHERE v.node_id=ANY($1::text[]) GROUP BY v.node_id,v.storage_pool_id
)
SELECT node_id,pool_id,sum(disk_gib)::bigint AS disk_gib FROM allocations GROUP BY node_id,pool_id
`

type StorageReservationsRow struct {
	NodeID  string
	PoolID  string
	DiskGib int64
}

func (q *Queries) StorageReservations(ctx context.Context, dollar_1 []string) ([]StorageReservationsRow, error) {
	rows, err := q.db.Query(ctx, storageReservations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageReservationsRow{}
	for rows.Next() {
		var i StorageReservationsRow
		if err := rows.Scan(&i.NodeID, &i.PoolID, &i.DiskGib); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
