// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: volumes.sql

package queries

import (
	"context"
)

const createPersistentVolume = `-- name: CreatePersistentVolume :exec
INSERT INTO persistent_volumes(id,node_id,storage_pool_id,name,kind,size_gib,state,operation_id) VALUES($1,$2,$3,$4,$5,$6,'creating',$7)
`

type CreatePersistentVolumeParams struct {
	ID            string
	NodeID        string
	StoragePoolID string
	Name          string
	Kind          string
	SizeGib       int64
	OperationID   *string
}

func (q *Queries) CreatePersistentVolume(ctx context.Context, arg CreatePersistentVolumeParams) error {
	_, err := q.db.Exec(ctx, createPersistentVolume,
		arg.ID,
		arg.NodeID,
		arg.StoragePoolID,
		arg.Name,
		arg.Kind,
		arg.SizeGib,
		arg.OperationID,
	)
	return err
}

const deletePersistentVolume = `-- name: DeletePersistentVolume :exec
DELETE FROM persistent_volumes WHERE id=$1
`

func (q *Queries) DeletePersistentVolume(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePersistentVolume, id)
	return err
}

const finishVolume = `-- name: FinishVolume :exec
UPDATE persistent_volumes SET state=$2,size_gib=$3 WHERE id=$1
`

type FinishVolumeParams struct {
	ID      string
	State   string
	SizeGib int64
}

func (q *Queries) FinishVolume(ctx context.Context, arg FinishVolumeParams) error {
	_, err := q.db.Exec(ctx, finishVolume, arg.ID, arg.State, arg.SizeGib)
	return err
}

const getPersistentVolume = `-- name: GetPersistentVolume :one
SELECT id, node_id, storage_pool_id, name, kind, size_gib, state, operation_id FROM persistent_volumes WHERE id=$1
`

func (q *Queries) GetPersistentVolume(ctx context.Context, id string) (PersistentVolume, error) {
	row := q.db.QueryRow(ctx, getPersistentVolume, id)
	var i PersistentVolume
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.StoragePoolID,
		&i.Name,
		&i.Kind,
		&i.SizeGib,
		&i.State,
		&i.OperationID,
	)
	return i, err
}

const getPersistentVolumes = `-- name: GetPersistentVolumes :many
SELECT id, node_id, storage_pool_id, name, kind, size_gib, state, operation_id FROM persistent_volumes WHERE id=ANY($1::text[])
`

func (q *Queries) GetPersistentVolumes(ctx context.Context, dollar_1 []string) ([]PersistentVolume, error) {
	rows, err := q.db.Query(ctx, getPersistentVolumes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersistentVolume{}
	for rows.Next() {
		var i PersistentVolume
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.StoragePoolID,
			&i.Name,
			&i.Kind,
			&i.SizeGib,
			&i.State,
			&i.OperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersistentVolumes = `-- name: ListPersistentVolumes :many
SELECT v.id, v.node_id, v.storage_pool_id, v.name, v.kind, v.size_gib, v.state, v.operation_id,o.error AS operation_error FROM persistent_volumes v LEFT JOIN operations o ON o.id=v.operation_id
WHERE $1::text='' OR v.id=$1 ORDER BY v.name,v.id
`

type ListPersistentVolumesRow struct {
	ID             string
	NodeID         string
	StoragePoolID  string
	Name           string
	Kind           string
	SizeGib        int64
	State          string
	OperationID    *string
	OperationError *string
}

func (q *Queries) ListPersistentVolumes(ctx context.Context, volumeID string) ([]ListPersistentVolumesRow, error) {
	rows, err := q.db.Query(ctx, listPersistentVolumes, volumeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersistentVolumesRow{}
	for rows.Next() {
		var i ListPersistentVolumesRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.StoragePoolID,
			&i.Name,
			&i.Kind,
			&i.SizeGib,
			&i.State,
			&i.OperationID,
			&i.OperationError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPersistentVolumes = `-- name: LockPersistentVolumes :many
SELECT id, node_id, storage_pool_id, name, kind, size_gib, state, operation_id FROM persistent_volumes WHERE id=ANY($1::text[]) ORDER BY id FOR UPDATE
`

func (q *Queries) LockPersistentVolumes(ctx context.Context, dollar_1 []string) ([]PersistentVolume, error) {
	rows, err := q.db.Query(ctx, lockPersistentVolumes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersistentVolume{}
	for rows.Next() {
		var i PersistentVolume
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.StoragePoolID,
			&i.Name,
			&i.Kind,
			&i.SizeGib,
			&i.State,
			&i.OperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const persistentVolumeReferences = `-- name: PersistentVolumeReferences :many
WITH volumes AS (SELECT id FROM persistent_volumes WHERE id=ANY($1::text[]))
SELECT DISTINCT volume_id,name::text FROM (
 SELECT v.id AS volume_id,'环境：'||e.name AS name FROM volumes v JOIN environments e ON e.status<>'destroyed' AND (
 e.spec @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('volumes',jsonb_build_array(jsonb_build_object('persistentVolumeId',v.id))))) OR
 e.applied_spec @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('volumes',jsonb_build_array(jsonb_build_object('persistentVolumeId',v.id))))) OR
 e.draft->'spec' @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('volumes',jsonb_build_array(jsonb_build_object('persistentVolumeId',v.id))))))
 UNION SELECT v.id,'环境：'||e.name FROM volumes v JOIN runtime_assets a ON
 a.execution->'asset' @> jsonb_build_object('volumes',jsonb_build_array(jsonb_build_object('persistentVolumeId',v.id))) JOIN environments e ON e.id=a.environment_id
 UNION SELECT v.id,'环境：'||e.name FROM volumes v JOIN operations o ON o.state IN ('queued','running') AND
 o.payload->'spec' @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('volumes',jsonb_build_array(jsonb_build_object('persistentVolumeId',v.id))))) JOIN environments e ON e.id=o.environment_id
 UNION SELECT v.id,'恢复点：'||p.name FROM volumes v JOIN recovery_points p ON
 p.definition @> jsonb_build_object('assets',jsonb_build_array(jsonb_build_object('execution',jsonb_build_object('asset',jsonb_build_object('volumes',jsonb_build_array(jsonb_build_object('persistentVolumeId',v.id)))))))
) refs ORDER BY volume_id,name
`

type PersistentVolumeReferencesRow struct {
	VolumeID string
	Name     string
}

func (q *Queries) PersistentVolumeReferences(ctx context.Context, dollar_1 []string) ([]PersistentVolumeReferencesRow, error) {
	rows, err := q.db.Query(ctx, persistentVolumeReferences, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersistentVolumeReferencesRow{}
	for rows.Next() {
		var i PersistentVolumeReferencesRow
		if err := rows.Scan(&i.VolumeID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const persistentVolumeUses = `-- name: PersistentVolumeUses :many
WITH volumes AS (SELECT id FROM persistent_volumes WHERE id=ANY($1::text[]))
SELECT DISTINCT volume_id,environment_id,asset_id FROM (
 SELECT v.id AS volume_id,a.environment_id,a.asset_id FROM volumes v JOIN runtime_assets a ON
 a.execution->'asset' @> jsonb_build_object('volumes',jsonb_build_array(jsonb_build_object('persistentVolumeId',v.id)))
 UNION SELECT v.id,o.environment_id,a.value->>'id' AS asset_id FROM volumes v CROSS JOIN operations o
 CROSS JOIN LATERAL jsonb_path_query(o.payload,'$.spec.assets[*] ? (@.volumes[*].persistentVolumeId == $volume)',jsonb_build_object('volume',v.id)) a(value)
 WHERE o.state IN ('queued','running') AND o.scope_kind='environment'
) uses
`

type PersistentVolumeUsesRow struct {
	VolumeID      string
	EnvironmentID string
	AssetID       string
}

func (q *Queries) PersistentVolumeUses(ctx context.Context, dollar_1 []string) ([]PersistentVolumeUsesRow, error) {
	rows, err := q.db.Query(ctx, persistentVolumeUses, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersistentVolumeUsesRow{}
	for rows.Next() {
		var i PersistentVolumeUsesRow
		if err := rows.Scan(&i.VolumeID, &i.EnvironmentID, &i.AssetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVolumeOperation = `-- name: SetVolumeOperation :exec
UPDATE persistent_volumes SET state=$2,operation_id=$3 WHERE id=$1
`

type SetVolumeOperationParams struct {
	ID          string
	State       string
	OperationID *string
}

func (q *Queries) SetVolumeOperation(ctx context.Context, arg SetVolumeOperationParams) error {
	_, err := q.db.Exec(ctx, setVolumeOperation, arg.ID, arg.State, arg.OperationID)
	return err
}
