// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vpn.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyVPNAccess = `-- name: ApplyVPNAccess :exec
UPDATE vpn_access SET definition=$3,addresses=$4,applied=true WHERE environment_id=$1 AND id=$2
`

type ApplyVPNAccessParams struct {
	EnvironmentID string
	ID            string
	Definition    []byte
	Addresses     []netip.Addr
}

func (q *Queries) ApplyVPNAccess(ctx context.Context, arg ApplyVPNAccessParams) error {
	_, err := q.db.Exec(ctx, applyVPNAccess,
		arg.EnvironmentID,
		arg.ID,
		arg.Definition,
		arg.Addresses,
	)
	return err
}

const applyVPNPort = `-- name: ApplyVPNPort :exec
UPDATE service_ports SET port=$2,state='applied',updated_at=now() WHERE environment_id=$1 AND purpose='vpn'
`

type ApplyVPNPortParams struct {
	EnvironmentID string
	Port          *int32
}

func (q *Queries) ApplyVPNPort(ctx context.Context, arg ApplyVPNPortParams) error {
	_, err := q.db.Exec(ctx, applyVPNPort, arg.EnvironmentID, arg.Port)
	return err
}

const createVPNAccess = `-- name: CreateVPNAccess :exec
INSERT INTO vpn_access(id,environment_id,definition,operation_id) VALUES($1,$2,$3,$4)
`

type CreateVPNAccessParams struct {
	ID            string
	EnvironmentID string
	Definition    []byte
	OperationID   string
}

func (q *Queries) CreateVPNAccess(ctx context.Context, arg CreateVPNAccessParams) error {
	_, err := q.db.Exec(ctx, createVPNAccess,
		arg.ID,
		arg.EnvironmentID,
		arg.Definition,
		arg.OperationID,
	)
	return err
}

const deleteEnvironmentVPN = `-- name: DeleteEnvironmentVPN :exec
WITH peers AS (DELETE FROM vpn_access WHERE environment_id=$1), aliases AS (DELETE FROM vpn_aliases WHERE environment_id=$1)
UPDATE environments e SET vpn_public_key=NULL,vpn_mtu=NULL WHERE e.id=$1
`

func (q *Queries) DeleteEnvironmentVPN(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentVPN, id)
	return err
}

const deleteUnusedVPNAliases = `-- name: DeleteUnusedVPNAliases :exec
DELETE FROM vpn_aliases a WHERE a.environment_id=$1 AND NOT EXISTS (
  SELECT 1 FROM vpn_access v,jsonb_array_elements(v.definition->'routes') r
  WHERE v.environment_id=a.environment_id AND r->>'accessCidr'=a.prefix::text
)
`

func (q *Queries) DeleteUnusedVPNAliases(ctx context.Context, environmentID string) error {
	_, err := q.db.Exec(ctx, deleteUnusedVPNAliases, environmentID)
	return err
}

const deleteVPNAccess = `-- name: DeleteVPNAccess :exec
DELETE FROM vpn_access WHERE environment_id=$1 AND id=$2
`

type DeleteVPNAccessParams struct {
	EnvironmentID string
	ID            string
}

func (q *Queries) DeleteVPNAccess(ctx context.Context, arg DeleteVPNAccessParams) error {
	_, err := q.db.Exec(ctx, deleteVPNAccess, arg.EnvironmentID, arg.ID)
	return err
}

const deleteVPNPort = `-- name: DeleteVPNPort :exec
DELETE FROM service_ports WHERE environment_id=$1 AND purpose='vpn'
`

func (q *Queries) DeleteVPNPort(ctx context.Context, environmentID string) error {
	_, err := q.db.Exec(ctx, deleteVPNPort, environmentID)
	return err
}

const getVPNAccess = `-- name: GetVPNAccess :one
SELECT id, environment_id, definition, addresses, applied, operation_id, created_at FROM vpn_access WHERE environment_id=$1 AND id=$2
`

type GetVPNAccessParams struct {
	EnvironmentID string
	ID            string
}

func (q *Queries) GetVPNAccess(ctx context.Context, arg GetVPNAccessParams) (VpnAccess, error) {
	row := q.db.QueryRow(ctx, getVPNAccess, arg.EnvironmentID, arg.ID)
	var i VpnAccess
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Definition,
		&i.Addresses,
		&i.Applied,
		&i.OperationID,
		&i.CreatedAt,
	)
	return i, err
}

const getVPNPort = `-- name: GetVPNPort :one
SELECT p.id, p.node_id, p.protocol, p.port, p.environment_id, p.service_id, p.operation_id, p.state, p.updated_at, p.purpose,n.endpoint,n.info FROM service_ports p JOIN nodes n ON n.id=p.node_id
WHERE p.environment_id=$1 AND p.purpose='vpn'
`

type GetVPNPortRow struct {
	ID            int64
	NodeID        string
	Protocol      string
	Port          *int32
	EnvironmentID string
	ServiceID     string
	OperationID   string
	State         string
	UpdatedAt     pgtype.Timestamptz
	Purpose       string
	Endpoint      string
	Info          []byte
}

func (q *Queries) GetVPNPort(ctx context.Context, environmentID string) (GetVPNPortRow, error) {
	row := q.db.QueryRow(ctx, getVPNPort, environmentID)
	var i GetVPNPortRow
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Protocol,
		&i.Port,
		&i.EnvironmentID,
		&i.ServiceID,
		&i.OperationID,
		&i.State,
		&i.UpdatedAt,
		&i.Purpose,
		&i.Endpoint,
		&i.Info,
	)
	return i, err
}

const listVPNAccess = `-- name: ListVPNAccess :many
SELECT v.id, v.environment_id, v.definition, v.addresses, v.applied, v.operation_id, v.created_at,o.kind AS operation_kind,o.state AS operation_state,o.error AS operation_error
FROM vpn_access v JOIN operations o ON o.id=v.operation_id
WHERE v.environment_id=$1 ORDER BY v.created_at,v.id
`

type ListVPNAccessRow struct {
	ID             string
	EnvironmentID  string
	Definition     []byte
	Addresses      []netip.Addr
	Applied        bool
	OperationID    string
	CreatedAt      pgtype.Timestamptz
	OperationKind  string
	OperationState string
	OperationError *string
}

func (q *Queries) ListVPNAccess(ctx context.Context, environmentID string) ([]ListVPNAccessRow, error) {
	rows, err := q.db.Query(ctx, listVPNAccess, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVPNAccessRow{}
	for rows.Next() {
		var i ListVPNAccessRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Definition,
			&i.Addresses,
			&i.Applied,
			&i.OperationID,
			&i.CreatedAt,
			&i.OperationKind,
			&i.OperationState,
			&i.OperationError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVPNAliases = `-- name: ListVPNAliases :many
SELECT environment_id, network_id, prefix FROM vpn_aliases ORDER BY prefix
`

func (q *Queries) ListVPNAliases(ctx context.Context) ([]VpnAlias, error) {
	rows, err := q.db.Query(ctx, listVPNAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VpnAlias{}
	for rows.Next() {
		var i VpnAlias
		if err := rows.Scan(&i.EnvironmentID, &i.NetworkID, &i.Prefix); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAllAccessPorts = `-- name: ReleaseAllAccessPorts :exec
DELETE FROM service_ports WHERE environment_id=$1
`

func (q *Queries) ReleaseAllAccessPorts(ctx context.Context, environmentID string) error {
	_, err := q.db.Exec(ctx, releaseAllAccessPorts, environmentID)
	return err
}

const reserveVPNAlias = `-- name: ReserveVPNAlias :exec
INSERT INTO vpn_aliases(environment_id,network_id,prefix) VALUES($1,$2,$3)
`

type ReserveVPNAliasParams struct {
	EnvironmentID string
	NetworkID     string
	Prefix        netip.Prefix
}

func (q *Queries) ReserveVPNAlias(ctx context.Context, arg ReserveVPNAliasParams) error {
	_, err := q.db.Exec(ctx, reserveVPNAlias, arg.EnvironmentID, arg.NetworkID, arg.Prefix)
	return err
}

const reserveVPNPort = `-- name: ReserveVPNPort :exec
INSERT INTO service_ports(node_id,protocol,environment_id,service_id,operation_id,state,purpose)
VALUES($1,'udp',$2,'vpn',$3,'reserved','vpn')
`

type ReserveVPNPortParams struct {
	NodeID        string
	EnvironmentID string
	OperationID   string
}

func (q *Queries) ReserveVPNPort(ctx context.Context, arg ReserveVPNPortParams) error {
	_, err := q.db.Exec(ctx, reserveVPNPort, arg.NodeID, arg.EnvironmentID, arg.OperationID)
	return err
}

const setVPNAccessOperation = `-- name: SetVPNAccessOperation :exec
UPDATE vpn_access SET operation_id=$3 WHERE environment_id=$1 AND id=$2
`

type SetVPNAccessOperationParams struct {
	EnvironmentID string
	ID            string
	OperationID   string
}

func (q *Queries) SetVPNAccessOperation(ctx context.Context, arg SetVPNAccessOperationParams) error {
	_, err := q.db.Exec(ctx, setVPNAccessOperation, arg.EnvironmentID, arg.ID, arg.OperationID)
	return err
}

const setVPNGateway = `-- name: SetVPNGateway :exec
UPDATE environments SET vpn_public_key=$2,vpn_mtu=$3 WHERE id=$1
`

type SetVPNGatewayParams struct {
	ID           string
	VpnPublicKey *string
	VpnMtu       *int32
}

func (q *Queries) SetVPNGateway(ctx context.Context, arg SetVPNGatewayParams) error {
	_, err := q.db.Exec(ctx, setVPNGateway, arg.ID, arg.VpnPublicKey, arg.VpnMtu)
	return err
}
