// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Defines values for ActionRequestAction.
const (
	ActionRequestActionDestroy   ActionRequestAction = "destroy"
	ActionRequestActionForceStop ActionRequestAction = "force-stop"
	ActionRequestActionReboot    ActionRequestAction = "reboot"
	ActionRequestActionRebuild   ActionRequestAction = "rebuild"
	ActionRequestActionResume    ActionRequestAction = "resume"
	ActionRequestActionStart     ActionRequestAction = "start"
	ActionRequestActionStop      ActionRequestAction = "stop"
	ActionRequestActionSuspend   ActionRequestAction = "suspend"
)

// Defines values for ChangeItemEffect.
const (
	Add     ChangeItemEffect = "add"
	Remove  ChangeItemEffect = "remove"
	Replace ChangeItemEffect = "replace"
	Update  ChangeItemEffect = "update"
)

// Defines values for ChangeItemKind.
const (
	ChangeItemKindAsset   ChangeItemKind = "asset"
	ChangeItemKindNetwork ChangeItemKind = "network"
)

// Defines values for EnvironmentStatus.
const (
	EnvironmentStatusChanging   EnvironmentStatus = "changing"
	EnvironmentStatusDeploying  EnvironmentStatus = "deploying"
	EnvironmentStatusDestroyed  EnvironmentStatus = "destroyed"
	EnvironmentStatusDestroying EnvironmentStatus = "destroying"
	EnvironmentStatusDraft      EnvironmentStatus = "draft"
	EnvironmentStatusFailed     EnvironmentStatus = "failed"
	EnvironmentStatusRunning    EnvironmentStatus = "running"
	EnvironmentStatusStopped    EnvironmentStatus = "stopped"
	EnvironmentStatusSuspended  EnvironmentStatus = "suspended"
	EnvironmentStatusUnknown    EnvironmentStatus = "unknown"
)

// Defines values for HardwareDiskBus.
const (
	HardwareDiskBusIde    HardwareDiskBus = "ide"
	HardwareDiskBusSata   HardwareDiskBus = "sata"
	HardwareDiskBusScsi   HardwareDiskBus = "scsi"
	HardwareDiskBusVirtio HardwareDiskBus = "virtio"
)

// Defines values for HardwareFirmware.
const (
	Bios HardwareFirmware = "bios"
	Uefi HardwareFirmware = "uefi"
)

// Defines values for HardwareNicModel.
const (
	HardwareNicModelE1000   HardwareNicModel = "e1000"
	HardwareNicModelE1000e  HardwareNicModel = "e1000e"
	HardwareNicModelRtl8139 HardwareNicModel = "rtl8139"
	HardwareNicModelVirtio  HardwareNicModel = "virtio"
)

// Defines values for NodePlanPhase.
const (
	NodePlanPhaseActivate       NodePlanPhase = "activate"
	NodePlanPhaseCleanupVolumes NodePlanPhase = "cleanup-volumes"
	NodePlanPhaseDestroy        NodePlanPhase = "destroy"
	NodePlanPhaseForceStop      NodePlanPhase = "force-stop"
	NodePlanPhaseInspect        NodePlanPhase = "inspect"
	NodePlanPhaseNetwork        NodePlanPhase = "network"
	NodePlanPhasePrepare        NodePlanPhase = "prepare"
	NodePlanPhaseReboot         NodePlanPhase = "reboot"
	NodePlanPhaseRemoveNetwork  NodePlanPhase = "remove-network"
	NodePlanPhaseResume         NodePlanPhase = "resume"
	NodePlanPhaseStart          NodePlanPhase = "start"
	NodePlanPhaseStop           NodePlanPhase = "stop"
	NodePlanPhaseSuspend        NodePlanPhase = "suspend"
	NodePlanPhaseUpdate         NodePlanPhase = "update"
)

// Defines values for OperationState.
const (
	OperationStateFailed           OperationState = "failed"
	OperationStatePartiallyApplied OperationState = "partially_applied"
	OperationStateQueued           OperationState = "queued"
	OperationStateRunning          OperationState = "running"
	OperationStateSucceeded        OperationState = "succeeded"
)

// Defines values for PolicyAction.
const (
	Allow PolicyAction = "allow"
	Deny  PolicyAction = "deny"
	Shape PolicyAction = "shape"
)

// Defines values for PolicyDirection.
const (
	Both    PolicyDirection = "both"
	Egress  PolicyDirection = "egress"
	Ingress PolicyDirection = "ingress"
)

// Defines values for TemplateFormat.
const (
	Docker TemplateFormat = "docker"
	Iso    TemplateFormat = "iso"
	Oci    TemplateFormat = "oci"
	Ova    TemplateFormat = "ova"
	Qcow2  TemplateFormat = "qcow2"
	Raw    TemplateFormat = "raw"
	Vmdk   TemplateFormat = "vmdk"
)

// Defines values for TemplateKind.
const (
	Container TemplateKind = "container"
	Vm        TemplateKind = "vm"
)

// Defines values for TemplateState.
const (
	Failed    TemplateState = "failed"
	Importing TemplateState = "importing"
	Ready     TemplateState = "ready"
)

// ActionRequest defines model for ActionRequest.
type ActionRequest struct {
	Action           ActionRequestAction `json:"action"`
	ClientRequestId  *string             `json:"clientRequestId,omitempty"`
	ExpectedRevision *int                `json:"expectedRevision,omitempty"`
}

// ActionRequestAction defines model for ActionRequest.Action.
type ActionRequestAction string

// Asset defines model for Asset.
type Asset struct {
	Id         string             `json:"id"`
	Interfaces []Interface        `json:"interfaces"`
	Name       string             `json:"name"`
	Parameters *map[string]string `json:"parameters,omitempty"`
	Resources  Resources          `json:"resources"`
	TemplateId string             `json:"templateId"`
	Volumes    *[]Volume          `json:"volumes,omitempty"`
}

// AssetExecution defines model for AssetExecution.
type AssetExecution struct {
	Asset              Asset               `json:"asset"`
	InstanceId         string              `json:"instanceId"`
	Interfaces         []ResolvedInterface `json:"interfaces"`
	PreviousInstanceId *string             `json:"previousInstanceId,omitempty"`
	Template           Template            `json:"template"`
}

// AssetState defines model for AssetState.
type AssetState struct {
	AssetId    string    `json:"assetId"`
	Error      *string   `json:"error,omitempty"`
	InstanceId string    `json:"instanceId"`
	NodeId     string    `json:"nodeId"`
	ObservedAt time.Time `json:"observedAt"`
	State      string    `json:"state"`
}

// CanvasView defines model for CanvasView.
type CanvasView struct {
	Collapsed *[]string         `json:"collapsed,omitempty"`
	Positions *map[string]Point `json:"positions,omitempty"`
}

// ChangeItem defines model for ChangeItem.
type ChangeItem struct {
	DataEffect   *string          `json:"dataEffect,omitempty"`
	Effect       ChangeItemEffect `json:"effect"`
	Id           string           `json:"id"`
	Kind         ChangeItemKind   `json:"kind"`
	Name         string           `json:"name"`
	RequiresStop *bool            `json:"requiresStop,omitempty"`
}

// ChangeItemEffect defines model for ChangeItem.Effect.
type ChangeItemEffect string

// ChangeItemKind defines model for ChangeItem.Kind.
type ChangeItemKind string

// ChangePreview defines model for ChangePreview.
type ChangePreview struct {
	Changes  []ChangeItem `json:"changes"`
	Revision int          `json:"revision"`
}

// ChangeRequest defines model for ChangeRequest.
type ChangeRequest struct {
	Apply            bool            `json:"apply"`
	ClientRequestId  *string         `json:"clientRequestId,omitempty"`
	ExpectedRevision int             `json:"expectedRevision"`
	Spec             EnvironmentSpec `json:"spec"`
}

// CreateEnvironment defines model for CreateEnvironment.
type CreateEnvironment struct {
	BlueprintVersionId *string         `json:"blueprintVersionId,omitempty"`
	ClientRequestId    *string         `json:"clientRequestId,omitempty"`
	ExternalReference  *string         `json:"externalReference,omitempty"`
	Name               string          `json:"name"`
	ProjectId          *string         `json:"projectId,omitempty"`
	Run                *bool           `json:"run,omitempty"`
	Spec               EnvironmentSpec `json:"spec"`
}

// Draft defines model for Draft.
type Draft struct {
	BaseRevision int             `json:"baseRevision"`
	Spec         EnvironmentSpec `json:"spec"`
}

// Environment defines model for Environment.
type Environment struct {
	AppliedSpec       *EnvironmentSpec  `json:"appliedSpec,omitempty"`
	CreatedAt         time.Time         `json:"createdAt"`
	Draft             *Draft            `json:"draft,omitempty"`
	Error             *string           `json:"error,omitempty"`
	ExternalReference *string           `json:"externalReference,omitempty"`
	Id                string            `json:"id"`
	Name              string            `json:"name"`
	OperationId       *string           `json:"operationId,omitempty"`
	ProjectId         string            `json:"projectId"`
	Revision          int               `json:"revision"`
	Spec              EnvironmentSpec   `json:"spec"`
	Status            EnvironmentStatus `json:"status"`
	UpdatedAt         time.Time         `json:"updatedAt"`
	View              CanvasView        `json:"view"`
}

// EnvironmentStatus defines model for Environment.Status.
type EnvironmentStatus string

// EnvironmentSpec defines model for EnvironmentSpec.
type EnvironmentSpec struct {
	Assets   []Asset   `json:"assets"`
	Networks []Network `json:"networks"`
	Policies *[]Policy `json:"policies,omitempty"`
	Routes   *[]Route  `json:"routes,omitempty"`
}

// EnvironmentState defines model for EnvironmentState.
type EnvironmentState struct {
	Assets    []AssetState `json:"assets"`
	Id        string       `json:"id"`
	Operation *Operation   `json:"operation,omitempty"`
	Revision  int          `json:"revision"`
	Status    string       `json:"status"`
	UpdatedAt time.Time    `json:"updatedAt"`
}

// ExecutionResult defines model for ExecutionResult.
type ExecutionResult struct {
	AssetId    string          `json:"assetId"`
	Error      *string         `json:"error,omitempty"`
	Execution  *AssetExecution `json:"execution,omitempty"`
	InstanceId string          `json:"instanceId"`
	ObservedAt time.Time       `json:"observedAt"`
	State      string          `json:"state"`
}

// Hardware defines model for Hardware.
type Hardware struct {
	CpuModel     *string          `json:"cpuModel,omitempty"`
	DiskBus      HardwareDiskBus  `json:"diskBus"`
	Firmware     HardwareFirmware `json:"firmware"`
	FirmwareCode *string          `json:"firmwareCode,omitempty"`
	FirmwareVars *string          `json:"firmwareVars,omitempty"`
	GuestAgent   *bool            `json:"guestAgent,omitempty"`
	Machine      string           `json:"machine"`
	NicModel     HardwareNicModel `json:"nicModel"`
	SecureBoot   *bool            `json:"secureBoot,omitempty"`
	Tpm          *bool            `json:"tpm,omitempty"`
}

// HardwareDiskBus defines model for Hardware.DiskBus.
type HardwareDiskBus string

// HardwareFirmware defines model for Hardware.Firmware.
type HardwareFirmware string

// HardwareNicModel defines model for Hardware.NicModel.
type HardwareNicModel string

// Identity defines model for Identity.
type Identity struct {
	Administrator bool   `json:"administrator"`
	Id            string `json:"id"`
	Name          string `json:"name"`
}

// Interface defines model for Interface.
type Interface struct {
	Address   string `json:"address"`
	Id        string `json:"id"`
	Mac       string `json:"mac"`
	NetworkId string `json:"networkId"`
	Primary   bool   `json:"primary"`
}

// Login defines model for Login.
type Login struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

// Network defines model for Network.
type Network struct {
	Cidr       string    `json:"cidr"`
	DnsAssetId *string   `json:"dnsAssetId,omitempty"`
	DnsServers *[]string `json:"dnsServers,omitempty"`
	Gateway    *string   `json:"gateway,omitempty"`
	Id         string    `json:"id"`
	Mtu        *int      `json:"mtu,omitempty"`
	Name       string    `json:"name"`
}

// Node defines model for Node.
type Node struct {
	Capabilities []string   `json:"capabilities"`
	Capacity     Resources  `json:"capacity"`
	Endpoint     string     `json:"endpoint"`
	Id           string     `json:"id"`
	Name         string     `json:"name"`
	ObservedAt   time.Time  `json:"observedAt"`
	Override     *Resources `json:"override,omitempty"`
	Reserved     Resources  `json:"reserved"`
	Slots        int        `json:"slots"`
	State        *string    `json:"state,omitempty"`
}

// NodeInfo defines model for NodeInfo.
type NodeInfo struct {
	Capabilities []string  `json:"capabilities"`
	Capacity     Resources `json:"capacity"`
	Firmware     *[]string `json:"firmware,omitempty"`
	Id           string    `json:"id"`
	Name         string    `json:"name"`
	Slots        int       `json:"slots"`
}

// NodePlan defines model for NodePlan.
type NodePlan struct {
	Assets        []AssetExecution `json:"assets"`
	EnvironmentId string           `json:"environmentId"`
	OperationId   string           `json:"operationId"`
	Phase         NodePlanPhase    `json:"phase"`
	Spec          EnvironmentSpec  `json:"spec"`
}

// NodePlanPhase defines model for NodePlan.Phase.
type NodePlanPhase string

// NodeRegistration defines model for NodeRegistration.
type NodeRegistration struct {
	Endpoint string `json:"endpoint"`
	Name     string `json:"name"`
}

// NodeResult defines model for NodeResult.
type NodeResult struct {
	Error   *string           `json:"error,omitempty"`
	Results []ExecutionResult `json:"results"`
}

// Operation defines model for Operation.
type Operation struct {
	Completed     int                `json:"completed"`
	CreatedAt     time.Time          `json:"createdAt"`
	EnvironmentId *string            `json:"environmentId,omitempty"`
	Error         *string            `json:"error,omitempty"`
	Id            string             `json:"id"`
	Kind          string             `json:"kind"`
	Phase         string             `json:"phase"`
	Results       *[]ExecutionResult `json:"results,omitempty"`
	State         OperationState     `json:"state"`
	Total         int                `json:"total"`
	UpdatedAt     time.Time          `json:"updatedAt"`
}

// OperationState defines model for Operation.State.
type OperationState string

// Point defines model for Point.
type Point struct {
	X float32 `json:"x"`
	Y float32 `json:"y"`
}

// Policy defines model for Policy.
type Policy struct {
	Action        PolicyAction    `json:"action"`
	BandwidthKbps *int            `json:"bandwidthKbps,omitempty"`
	DelayMs       *int            `json:"delayMs,omitempty"`
	Destination   *string         `json:"destination,omitempty"`
	Direction     PolicyDirection `json:"direction"`
	Id            string          `json:"id"`
	LossPercent   *float32        `json:"lossPercent,omitempty"`
	NetworkId     string          `json:"networkId"`
	Protocol      *string         `json:"protocol,omitempty"`
	Source        *string         `json:"source,omitempty"`
}

// PolicyAction defines model for Policy.Action.
type PolicyAction string

// PolicyDirection defines model for Policy.Direction.
type PolicyDirection string

// Problem defines model for Problem.
type Problem struct {
	Detail string `json:"detail"`
	Status int    `json:"status"`
	Title  string `json:"title"`
}

// ResolvedInterface defines model for ResolvedInterface.
type ResolvedInterface struct {
	Address   string    `json:"address"`
	Dns       *[]string `json:"dns,omitempty"`
	Gateway   *string   `json:"gateway,omitempty"`
	Id        string    `json:"id"`
	Mac       string    `json:"mac"`
	Mtu       int       `json:"mtu"`
	NetworkId string    `json:"networkId"`
	PortName  string    `json:"portName"`
	Prefix    int       `json:"prefix"`
	Primary   bool      `json:"primary"`
}

// Resources defines model for Resources.
type Resources struct {
	Cpu       int   `json:"cpu"`
	DiskGiB   int64 `json:"diskGiB"`
	MemoryMiB int64 `json:"memoryMiB"`
}

// Route defines model for Route.
type Route struct {
	Destination string `json:"destination"`
	NetworkId   string `json:"networkId"`
	NextHop     string `json:"nextHop"`
}

// Template defines model for Template.
type Template struct {
	Error     *string         `json:"error,omitempty"`
	Format    *TemplateFormat `json:"format,omitempty"`
	Hardware  *Hardware       `json:"hardware,omitempty"`
	Id        string          `json:"id"`
	Kind      TemplateKind    `json:"kind"`
	Name      string          `json:"name"`
	Os        string          `json:"os"`
	Resources Resources       `json:"resources"`
	Source    string          `json:"source"`
	State     *TemplateState  `json:"state,omitempty"`
	Version   int             `json:"version"`
	Volumes   *[]Volume       `json:"volumes,omitempty"`
}

// TemplateFormat defines model for Template.Format.
type TemplateFormat string

// TemplateKind defines model for Template.Kind.
type TemplateKind string

// TemplateState defines model for Template.State.
type TemplateState string

// Volume defines model for Volume.
type Volume struct {
	Id        string `json:"id"`
	MountPath string `json:"mountPath"`
	Retain    *bool  `json:"retain,omitempty"`
	SizeGiB   int64  `json:"sizeGiB"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Id defines model for Id.
type Id = string

// Limit defines model for Limit.
type Limit = int

// Accepted defines model for Accepted.
type Accepted = Operation

// ListEnvironmentsParams defines parameters for ListEnvironments.
type ListEnvironmentsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// EnvironmentEventsParams defines parameters for EnvironmentEvents.
type EnvironmentEventsParams struct {
	LastEventID *int64 `json:"Last-Event-ID,omitempty"`
}

// ListNodesParams defines parameters for ListNodes.
type ListNodesParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListOperationsParams defines parameters for ListOperations.
type ListOperationsParams struct {
	EnvironmentId *string `form:"environmentId,omitempty" json:"environmentId,omitempty"`
	Cursor        *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit         *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListTemplatesParams defines parameters for ListTemplates.
type ListTemplatesParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateEnvironmentJSONRequestBody defines body for CreateEnvironment for application/json ContentType.
type CreateEnvironmentJSONRequestBody = CreateEnvironment

// EnvironmentActionJSONRequestBody defines body for EnvironmentAction for application/json ContentType.
type EnvironmentActionJSONRequestBody = ActionRequest

// AssetActionJSONRequestBody defines body for AssetAction for application/json ContentType.
type AssetActionJSONRequestBody = ActionRequest

// ChangeEnvironmentJSONRequestBody defines body for ChangeEnvironment for application/json ContentType.
type ChangeEnvironmentJSONRequestBody = ChangeRequest

// SaveDraftJSONRequestBody defines body for SaveDraft for application/json ContentType.
type SaveDraftJSONRequestBody = Draft

// SaveViewJSONRequestBody defines body for SaveView for application/json ContentType.
type SaveViewJSONRequestBody = CanvasView

// RegisterNodeJSONRequestBody defines body for RegisterNode for application/json ContentType.
type RegisterNodeJSONRequestBody = NodeRegistration

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = Login

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = Template
