// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Defines values for ActionRequestAction.
const (
	ActionRequestActionDestroy   ActionRequestAction = "destroy"
	ActionRequestActionForceStop ActionRequestAction = "force-stop"
	ActionRequestActionReboot    ActionRequestAction = "reboot"
	ActionRequestActionRebuild   ActionRequestAction = "rebuild"
	ActionRequestActionResume    ActionRequestAction = "resume"
	ActionRequestActionStart     ActionRequestAction = "start"
	ActionRequestActionStop      ActionRequestAction = "stop"
	ActionRequestActionSuspend   ActionRequestAction = "suspend"
)

// Defines values for BackupRepositoryState.
const (
	BackupRepositoryStateConnecting BackupRepositoryState = "connecting"
	BackupRepositoryStateFailed     BackupRepositoryState = "failed"
	BackupRepositoryStateReady      BackupRepositoryState = "ready"
)

// Defines values for BackupSummaryState.
const (
	BackupSummaryStateCreating BackupSummaryState = "creating"
	BackupSummaryStateDeleting BackupSummaryState = "deleting"
	BackupSummaryStateFailed   BackupSummaryState = "failed"
	BackupSummaryStateReady    BackupSummaryState = "ready"
)

// Defines values for ChangeItemEffect.
const (
	Add     ChangeItemEffect = "add"
	Remove  ChangeItemEffect = "remove"
	Replace ChangeItemEffect = "replace"
	Update  ChangeItemEffect = "update"
)

// Defines values for ChangeItemKind.
const (
	ChangeItemKindAsset   ChangeItemKind = "asset"
	ChangeItemKindNetwork ChangeItemKind = "network"
	ChangeItemKindService ChangeItemKind = "service"
)

// Defines values for ConsoleKind.
const (
	Rdp      ConsoleKind = "rdp"
	Serial   ConsoleKind = "serial"
	Ssh      ConsoleKind = "ssh"
	Terminal ConsoleKind = "terminal"
	Vnc      ConsoleKind = "vnc"
)

// Defines values for EnvironmentStatus.
const (
	EnvironmentStatusChanging   EnvironmentStatus = "changing"
	EnvironmentStatusDeploying  EnvironmentStatus = "deploying"
	EnvironmentStatusDestroyed  EnvironmentStatus = "destroyed"
	EnvironmentStatusDestroying EnvironmentStatus = "destroying"
	EnvironmentStatusDraft      EnvironmentStatus = "draft"
	EnvironmentStatusFailed     EnvironmentStatus = "failed"
	EnvironmentStatusRunning    EnvironmentStatus = "running"
	EnvironmentStatusStopped    EnvironmentStatus = "stopped"
	EnvironmentStatusSuspended  EnvironmentStatus = "suspended"
	EnvironmentStatusUnknown    EnvironmentStatus = "unknown"
)

// Defines values for ExternalInterfaceKind.
const (
	Ethernet    ExternalInterfaceKind = "ethernet"
	LinuxBridge ExternalInterfaceKind = "linux-bridge"
	OvsBridge   ExternalInterfaceKind = "ovs-bridge"
)

// Defines values for FileCommandAction.
const (
	FileMkdir  FileCommandAction = "mkdir"
	FileRemove FileCommandAction = "remove"
	FileRename FileCommandAction = "rename"
)

// Defines values for FileEntryKind.
const (
	FileDirectory FileEntryKind = "directory"
	FileLink      FileEntryKind = "link"
	FileOther     FileEntryKind = "other"
	FileRegular   FileEntryKind = "file"
)

// Defines values for HardwareDiskBus.
const (
	HardwareDiskBusIde    HardwareDiskBus = "ide"
	HardwareDiskBusSata   HardwareDiskBus = "sata"
	HardwareDiskBusScsi   HardwareDiskBus = "scsi"
	HardwareDiskBusVirtio HardwareDiskBus = "virtio"
)

// Defines values for HardwareFirmware.
const (
	Bios HardwareFirmware = "bios"
	Uefi HardwareFirmware = "uefi"
)

// Defines values for HardwareNicModel.
const (
	HardwareNicModelE1000   HardwareNicModel = "e1000"
	HardwareNicModelE1000e  HardwareNicModel = "e1000e"
	HardwareNicModelRtl8139 HardwareNicModel = "rtl8139"
	HardwareNicModelVirtio  HardwareNicModel = "virtio"
	HardwareNicModelVmxnet3 HardwareNicModel = "vmxnet3"
)

// Defines values for LogChunkStream.
const (
	LogChunkStreamStderr LogChunkStream = "stderr"
	LogChunkStreamStdout LogChunkStream = "stdout"
)

// Defines values for MetricSeriesMetric.
const (
	Cpu             MetricSeriesMetric = "cpu"
	DiskRead        MetricSeriesMetric = "disk_read"
	DiskWrite       MetricSeriesMetric = "disk_write"
	Memory          MetricSeriesMetric = "memory"
	Receive         MetricSeriesMetric = "receive"
	ReceiveDrops    MetricSeriesMetric = "receive_drops"
	ReceivePackets  MetricSeriesMetric = "receive_packets"
	Transmit        MetricSeriesMetric = "transmit"
	TransmitDrops   MetricSeriesMetric = "transmit_drops"
	TransmitPackets MetricSeriesMetric = "transmit_packets"
)

// Defines values for NodePlanPhase.
const (
	NodePlanPhaseApplyRecovery       NodePlanPhase = "apply-recovery"
	NodePlanPhaseCaptureRecovery     NodePlanPhase = "capture-recovery"
	NodePlanPhaseCleanupRecovery     NodePlanPhase = "cleanup-recovery"
	NodePlanPhaseCleanupVolumes      NodePlanPhase = "cleanup-volumes"
	NodePlanPhaseDeleteRecovery      NodePlanPhase = "delete-recovery"
	NodePlanPhaseDestroy             NodePlanPhase = "destroy"
	NodePlanPhaseExternalAttachments NodePlanPhase = "external-attachments"
	NodePlanPhaseForceStop           NodePlanPhase = "force-stop"
	NodePlanPhaseInspect             NodePlanPhase = "inspect"
	NodePlanPhaseNetwork             NodePlanPhase = "network"
	NodePlanPhasePolicies            NodePlanPhase = "policies"
	NodePlanPhasePrepare             NodePlanPhase = "prepare"
	NodePlanPhasePrepareRecovery     NodePlanPhase = "prepare-recovery"
	NodePlanPhaseRemoveNetwork       NodePlanPhase = "remove-network"
	NodePlanPhaseResume              NodePlanPhase = "resume"
	NodePlanPhaseRollbackRecovery    NodePlanPhase = "rollback-recovery"
	NodePlanPhaseServices            NodePlanPhase = "services"
	NodePlanPhaseStart               NodePlanPhase = "start"
	NodePlanPhaseStop                NodePlanPhase = "stop"
	NodePlanPhaseSuspend             NodePlanPhase = "suspend"
	NodePlanPhaseUpdate              NodePlanPhase = "update"
	NodePlanPhaseVpn                 NodePlanPhase = "vpn"
)

// Defines values for OperationState.
const (
	OperationStateFailed           OperationState = "failed"
	OperationStatePartiallyApplied OperationState = "partially_applied"
	OperationStateQueued           OperationState = "queued"
	OperationStateRunning          OperationState = "running"
	OperationStateSucceeded        OperationState = "succeeded"
)

// Defines values for Permission.
const (
	PermissionAccess  Permission = "access"
	PermissionCompose Permission = "compose"
	PermissionFile    Permission = "file"
	PermissionManage  Permission = "manage"
	PermissionNetwork Permission = "network"
	PermissionObserve Permission = "observe"
	PermissionOperate Permission = "operate"
	PermissionRead    Permission = "read"
	PermissionSession Permission = "session"
)

// Defines values for PolicyAction.
const (
	Allow PolicyAction = "allow"
	Deny  PolicyAction = "deny"
	Shape PolicyAction = "shape"
)

// Defines values for PolicyDirection.
const (
	Both    PolicyDirection = "both"
	Egress  PolicyDirection = "egress"
	Ingress PolicyDirection = "ingress"
)

// Defines values for PrincipalKind.
const (
	PrincipalKindToken PrincipalKind = "token"
	PrincipalKindUser  PrincipalKind = "user"
)

// Defines values for RecoveryConsistency.
const (
	Application RecoveryConsistency = "application"
	Crash       RecoveryConsistency = "crash"
	Filesystem  RecoveryConsistency = "filesystem"
)

// Defines values for RecoveryPointSummaryState.
const (
	RecoveryPointSummaryStateCapturing RecoveryPointSummaryState = "capturing"
	RecoveryPointSummaryStateDeleting  RecoveryPointSummaryState = "deleting"
	RecoveryPointSummaryStateFailed    RecoveryPointSummaryState = "failed"
	RecoveryPointSummaryStateReady     RecoveryPointSummaryState = "ready"
)

// Defines values for RestartPolicy.
const (
	Always    RestartPolicy = "always"
	Never     RestartPolicy = "never"
	OnFailure RestartPolicy = "on-failure"
)

// Defines values for RolePresetKey.
const (
	Manager  RolePresetKey = "manager"
	Operator RolePresetKey = "operator"
	Viewer   RolePresetKey = "viewer"
)

// Defines values for SSHSettingsAuthKind.
const (
	SSHKey      SSHSettingsAuthKind = "key"
	SSHPassword SSHSettingsAuthKind = "password"
)

// Defines values for ScopeGrantScopeKind.
const (
	ScopeGrantScopeKindAsset       ScopeGrantScopeKind = "asset"
	ScopeGrantScopeKindEnvironment ScopeGrantScopeKind = "environment"
	ScopeGrantScopeKindProject     ScopeGrantScopeKind = "project"
)

// Defines values for ServiceProtocol.
const (
	Tcp ServiceProtocol = "tcp"
	Udp ServiceProtocol = "udp"
)

// Defines values for StoragePoolDriver.
const (
	Directory StoragePoolDriver = "directory"
)

// Defines values for StoragePoolState.
const (
	StoragePoolStateDeleting StoragePoolState = "deleting"
	StoragePoolStateReady    StoragePoolState = "ready"
)

// Defines values for TemplateDiskBus.
const (
	Ide    TemplateDiskBus = "ide"
	Sata   TemplateDiskBus = "sata"
	Scsi   TemplateDiskBus = "scsi"
	Virtio TemplateDiskBus = "virtio"
)

// Defines values for TemplateFormat.
const (
	Docker TemplateFormat = "docker"
	Iso    TemplateFormat = "iso"
	Oci    TemplateFormat = "oci"
	Ova    TemplateFormat = "ova"
	Ovf    TemplateFormat = "ovf"
	Qcow2  TemplateFormat = "qcow2"
	Raw    TemplateFormat = "raw"
	Vmdk   TemplateFormat = "vmdk"
)

// Defines values for TemplateInitialization.
const (
	CloudInit     TemplateInitialization = "cloud-init"
	CloudbaseInit TemplateInitialization = "cloudbase-init"
	None          TemplateInitialization = "none"
)

// Defines values for TemplateKind.
const (
	Container TemplateKind = "container"
	Vm        TemplateKind = "vm"
)

// Defines values for TemplateState.
const (
	TemplateStateDeleting  TemplateState = "deleting"
	TemplateStateFailed    TemplateState = "failed"
	TemplateStateImporting TemplateState = "importing"
	TemplateStateReady     TemplateState = "ready"
)

// Defines values for UpdateActivityPhase.
const (
	Downloading UpdateActivityPhase = "downloading"
	Failed      UpdateActivityPhase = "failed"
	Installing  UpdateActivityPhase = "installing"
	Queued      UpdateActivityPhase = "queued"
	Restarting  UpdateActivityPhase = "restarting"
	Succeeded   UpdateActivityPhase = "succeeded"
)

// Defines values for VPNAccessState.
const (
	VPNAccessStateActive   VPNAccessState = "active"
	VPNAccessStateFailed   VPNAccessState = "failed"
	VPNAccessStatePending  VPNAccessState = "pending"
	VPNAccessStateRevoking VPNAccessState = "revoking"
)

// Defines values for VPNMode.
const (
	Original   VPNMode = "original"
	Translated VPNMode = "translated"
)

// Defines values for AssetLogsParamsStream.
const (
	AssetLogsParamsStreamAll    AssetLogsParamsStream = "all"
	AssetLogsParamsStreamStderr AssetLogsParamsStream = "stderr"
	AssetLogsParamsStreamStdout AssetLogsParamsStream = "stdout"
)

// Defines values for ListPrincipalsParamsKind.
const (
	ListPrincipalsParamsKindToken ListPrincipalsParamsKind = "token"
	ListPrincipalsParamsKindUser  ListPrincipalsParamsKind = "user"
)

// ActionRequest defines model for ActionRequest.
type ActionRequest struct {
	Action           ActionRequestAction `json:"action"`
	ClientRequestId  *string             `json:"clientRequestId,omitempty"`
	ExpectedRevision *int                `json:"expectedRevision,omitempty"`
}

// ActionRequestAction defines model for ActionRequest.Action.
type ActionRequestAction string

// ApplySystemUpdate defines model for ApplySystemUpdate.
type ApplySystemUpdate struct {
	Version string `json:"version"`
}

// Asset defines model for Asset.
type Asset struct {
	Guest      *GuestSettings `json:"guest,omitempty"`
	Id         string         `json:"id"`
	Interfaces []Interface    `json:"interfaces"`

	// Media Attached template media IDs. Omitted attaches all; an empty array ejects all.
	Media      *[]string          `json:"media,omitempty"`
	Name       string             `json:"name"`
	Parameters *map[string]string `json:"parameters,omitempty"`
	Resources  Resources          `json:"resources"`

	// RestartPolicy Restart unexpected exits only. Explicit stop remains stopped, including across node restarts.
	RestartPolicy *RestartPolicy `json:"restartPolicy,omitempty"`

	// StoragePoolId Omitted selects storage automatically; an existing asset keeps its storage until migrated.
	StoragePoolId *string   `json:"storagePoolId,omitempty"`
	TemplateId    string    `json:"templateId"`
	Volumes       *[]Volume `json:"volumes,omitempty"`
}

// AssetExecution defines model for AssetExecution.
type AssetExecution struct {
	Asset Asset `json:"asset"`

	// DataSetId Actual writable data set; retained across ordinary rebuilds
	DataSetId          string              `json:"dataSetId,omitempty"`
	InstanceId         string              `json:"instanceId"`
	Interfaces         []ResolvedInterface `json:"interfaces"`
	PreviousInstanceId *string             `json:"previousInstanceId,omitempty"`

	// StorageFilesystem Physical filesystem reservation identity
	StorageFilesystem *string `json:"storageFilesystem,omitempty"`

	// StoragePath Node-local managed storage selected by the scheduler
	StoragePath *string `json:"storagePath,omitempty"`

	// StoragePoolId Actual selected pool; omitted for node default storage
	StoragePoolId *string  `json:"storagePoolId,omitempty"`
	Template      Template `json:"template"`
}

// AssetState defines model for AssetState.
type AssetState struct {
	AssetId       string    `json:"assetId"`
	Error         *string   `json:"error,omitempty"`
	InstanceId    string    `json:"instanceId"`
	NodeId        string    `json:"nodeId"`
	ObservedAt    time.Time `json:"observedAt"`
	State         string    `json:"state"`
	StoragePoolId *string   `json:"storagePoolId,omitempty"`
}

// BackupCredentials defines model for BackupCredentials.
type BackupCredentials struct {
	AccessKey *string `json:"accessKey,omitempty"`
	Password  string  `json:"password"`
	Region    *string `json:"region,omitempty"`
	SecretKey *string `json:"secretKey,omitempty"`
}

// BackupRepository defines model for BackupRepository.
type BackupRepository struct {
	Error       *string               `json:"error,omitempty"`
	Id          string                `json:"id"`
	Location    *string               `json:"location,omitempty"`
	Name        string                `json:"name"`
	NodeId      string                `json:"nodeId"`
	OperationId *string               `json:"operationId,omitempty"`
	State       BackupRepositoryState `json:"state"`
}

// BackupRepositoryState defines model for BackupRepository.State.
type BackupRepositoryState string

// BackupSummary defines model for BackupSummary.
type BackupSummary struct {
	CreatedAt     time.Time          `json:"createdAt"`
	EnvironmentId *string            `json:"environmentId,omitempty"`
	Error         *string            `json:"error,omitempty"`
	Id            string             `json:"id"`
	Name          string             `json:"name"`
	OperationId   *string            `json:"operationId,omitempty"`
	RepositoryId  string             `json:"repositoryId"`
	SizeBytes     int64              `json:"sizeBytes"`
	State         BackupSummaryState `json:"state"`
}

// BackupSummaryState defines model for BackupSummary.State.
type BackupSummaryState string

// Blueprint defines model for Blueprint.
type Blueprint struct {
	AssetCount      int           `json:"assetCount"`
	CreatedAt       time.Time     `json:"createdAt"`
	Id              string        `json:"id"`
	LatestVersion   int           `json:"latestVersion"`
	LatestVersionId string        `json:"latestVersionId"`
	Name            string        `json:"name"`
	NetworkCount    int           `json:"networkCount"`
	Permissions     *[]Permission `json:"permissions,omitempty"`
	ProjectId       string        `json:"projectId"`
	UpdatedAt       time.Time     `json:"updatedAt"`
}

// BlueprintVersion defines model for BlueprintVersion.
type BlueprintVersion struct {
	AssetCount          int             `json:"assetCount"`
	BlueprintId         string          `json:"blueprintId"`
	CreatedAt           time.Time       `json:"createdAt"`
	Id                  string          `json:"id"`
	NetworkCount        int             `json:"networkCount"`
	SourceEnvironmentId string          `json:"sourceEnvironmentId"`
	SourceRevision      int             `json:"sourceRevision"`
	Spec                EnvironmentSpec `json:"spec"`
	Version             int             `json:"version"`
	View                CanvasView      `json:"view"`
}

// BlueprintVersionSummary defines model for BlueprintVersionSummary.
type BlueprintVersionSummary struct {
	AssetCount   int       `json:"assetCount"`
	BlueprintId  string    `json:"blueprintId"`
	CreatedAt    time.Time `json:"createdAt"`
	Id           string    `json:"id"`
	NetworkCount int       `json:"networkCount"`
	Version      int       `json:"version"`
}

// CanvasView defines model for CanvasView.
type CanvasView struct {
	Collapsed *[]string         `json:"collapsed,omitempty"`
	Positions *map[string]Point `json:"positions,omitempty"`
}

// CaptureRecoveryPoint defines model for CaptureRecoveryPoint.
type CaptureRecoveryPoint struct {
	ExpectedRevision int    `json:"expectedRevision"`
	IncludeMemory    bool   `json:"includeMemory,omitempty"`
	Name             string `json:"name"`
}

// CaptureTemplate defines model for CaptureTemplate.
type CaptureTemplate struct {
	ExpectedRevision int                     `json:"expectedRevision"`
	Initialization   *TemplateInitialization `json:"initialization,omitempty"`
	Name             string                  `json:"name"`
}

// ChangeItem defines model for ChangeItem.
type ChangeItem struct {
	DataEffect   *string          `json:"dataEffect,omitempty"`
	Effect       ChangeItemEffect `json:"effect"`
	Id           string           `json:"id"`
	Kind         ChangeItemKind   `json:"kind"`
	Name         string           `json:"name"`
	RequiresStop *bool            `json:"requiresStop,omitempty"`
}

// ChangeItemEffect defines model for ChangeItem.Effect.
type ChangeItemEffect string

// ChangeItemKind defines model for ChangeItem.Kind.
type ChangeItemKind string

// ChangePreview defines model for ChangePreview.
type ChangePreview struct {
	Changes  []ChangeItem `json:"changes"`
	Revision int          `json:"revision"`
}

// ChangeRequest defines model for ChangeRequest.
type ChangeRequest struct {
	Apply            bool            `json:"apply"`
	ClientRequestId  *string         `json:"clientRequestId,omitempty"`
	ExpectedRevision int             `json:"expectedRevision"`
	Spec             EnvironmentSpec `json:"spec"`
}

// ConsoleKind defines model for ConsoleKind.
type ConsoleKind string

// ConsoleResize defines model for ConsoleResize.
type ConsoleResize struct {
	Cols int `json:"cols"`
	Rows int `json:"rows"`
}

// CreateBackup defines model for CreateBackup.
type CreateBackup struct {
	Name            string `json:"name"`
	RecoveryPointId string `json:"recoveryPointId"`
	RepositoryId    string `json:"repositoryId"`
}

// CreateBackupRepository defines model for CreateBackupRepository.
type CreateBackupRepository struct {
	AccessKey  *string `json:"accessKey,omitempty"`
	Initialize *bool   `json:"initialize,omitempty"`

	// Location Absolute directory or s3:https://endpoint/bucket/path
	Location  string  `json:"location"`
	Name      string  `json:"name"`
	NodeId    string  `json:"nodeId"`
	Password  *string `json:"password,omitempty"`
	Region    *string `json:"region,omitempty"`
	SecretKey *string `json:"secretKey,omitempty"`
}

// CreateEnvironment defines model for CreateEnvironment.
type CreateEnvironment struct {
	// BackupId Restore an independent environment from this backup; run defaults to false
	BackupId           *string `json:"backupId,omitempty"`
	BlueprintVersionId *string `json:"blueprintVersionId,omitempty"`
	ClientRequestId    *string `json:"clientRequestId,omitempty"`
	ExternalReference  *string `json:"externalReference,omitempty"`
	Name               string  `json:"name"`
	ProjectId          *string `json:"projectId,omitempty"`

	// RecoveryPointId Create an independent copy of this recovery point; run defaults to false
	RecoveryPointId *string          `json:"recoveryPointId,omitempty"`
	Run             *bool            `json:"run,omitempty"`
	Spec            *EnvironmentSpec `json:"spec,omitempty"`
}

// CreateService defines model for CreateService.
type CreateService struct {
	ClientRequestId  *string         `json:"clientRequestId,omitempty"`
	ExpectedRevision int             `json:"expectedRevision"`
	InterfaceId      *string         `json:"interfaceId,omitempty"`
	ListenPort       *int            `json:"listenPort,omitempty"`
	Protocol         ServiceProtocol `json:"protocol"`
	TargetPort       int             `json:"targetPort"`
}

// CreateServiceToken defines model for CreateServiceToken.
type CreateServiceToken struct {
	ExpiresAt *time.Time   `json:"expiresAt,omitempty"`
	Grants    []ScopeGrant `json:"grants"`
	Name      string       `json:"name"`
}

// CreateStoragePool defines model for CreateStoragePool.
type CreateStoragePool struct {
	// Directory Existing directory or mounted filesystem on this node
	Directory string `json:"directory"`
	Name      string `json:"name"`
	NodeId    string `json:"nodeId"`
}

// CreateUser defines model for CreateUser.
type CreateUser struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

// CreateVPNAccess defines model for CreateVPNAccess.
type CreateVPNAccess struct {
	ClientRequestId  *string  `json:"clientRequestId,omitempty"`
	ExpectedRevision int      `json:"expectedRevision"`
	Mode             *VPNMode `json:"mode,omitempty"`
	Name             string   `json:"name"`
	NetworkIds       []string `json:"networkIds"`
	PublicKey        string   `json:"publicKey"`
}

// Draft defines model for Draft.
type Draft struct {
	BaseRevision int             `json:"baseRevision"`
	Spec         EnvironmentSpec `json:"spec"`
}

// Environment defines model for Environment.
type Environment struct {
	AppliedSpec        *EnvironmentSpec         `json:"appliedSpec,omitempty"`
	AssetPermissions   *map[string][]Permission `json:"assetPermissions,omitempty"`
	BlueprintVersionId *string                  `json:"blueprintVersionId,omitempty"`
	CreatedAt          time.Time                `json:"createdAt"`
	Draft              *Draft                   `json:"draft,omitempty"`
	Error              *string                  `json:"error,omitempty"`
	ExternalReference  *string                  `json:"externalReference,omitempty"`
	Id                 string                   `json:"id"`
	Name               string                   `json:"name"`
	OperationId        *string                  `json:"operationId,omitempty"`
	Permissions        *[]Permission            `json:"permissions,omitempty"`
	ProjectId          string                   `json:"projectId"`
	Revision           int                      `json:"revision"`
	Spec               EnvironmentSpec          `json:"spec"`
	Status             EnvironmentStatus        `json:"status"`
	UpdatedAt          time.Time                `json:"updatedAt"`
	View               CanvasView               `json:"view"`
}

// EnvironmentGrant defines model for EnvironmentGrant.
type EnvironmentGrant struct {
	AssetIds    *[]string    `json:"assetIds,omitempty"`
	Permissions []Permission `json:"permissions"`
	PrincipalId string       `json:"principalId"`
}

// EnvironmentSharing defines model for EnvironmentSharing.
type EnvironmentSharing struct {
	Grants    []EnvironmentGrant `json:"grants"`
	Inherited []EnvironmentGrant `json:"inherited"`
	OwnerId   *string            `json:"ownerId,omitempty"`
	Subjects  []Principal        `json:"subjects"`
}

// EnvironmentSpec defines model for EnvironmentSpec.
type EnvironmentSpec struct {
	Assets   []Asset            `json:"assets"`
	Networks []Network          `json:"networks"`
	Policies *[]Policy          `json:"policies,omitempty"`
	Routes   *[]Route           `json:"routes,omitempty"`
	Services *[]ServiceExposure `json:"services,omitempty"`
}

// EnvironmentState defines model for EnvironmentState.
type EnvironmentState struct {
	Assets    []AssetState `json:"assets"`
	Id        string       `json:"id"`
	Operation *Operation   `json:"operation,omitempty"`
	Revision  int          `json:"revision"`
	Status    string       `json:"status"`
	UpdatedAt time.Time    `json:"updatedAt"`
}

// EnvironmentStatus defines model for EnvironmentStatus.
type EnvironmentStatus string

// EnvironmentSummary defines model for EnvironmentSummary.
type EnvironmentSummary struct {
	AssetCount        int               `json:"assetCount"`
	CreatedAt         time.Time         `json:"createdAt"`
	ExternalReference *string           `json:"externalReference,omitempty"`
	Id                string            `json:"id"`
	Name              string            `json:"name"`
	NetworkCount      int               `json:"networkCount"`
	ProjectId         string            `json:"projectId"`
	Revision          int               `json:"revision"`
	Status            EnvironmentStatus `json:"status"`
	UpdatedAt         time.Time         `json:"updatedAt"`
}

// ExecutionResult defines model for ExecutionResult.
type ExecutionResult struct {
	AssetId       string           `json:"assetId"`
	EnvironmentId *string          `json:"environmentId,omitempty"`
	Error         *string          `json:"error,omitempty"`
	Execution     *AssetExecution  `json:"execution,omitempty"`
	InstanceId    string           `json:"instanceId"`
	ObservedAt    time.Time        `json:"observedAt"`
	Recovery      *RecoveryCapture `json:"recovery,omitempty"`
	State         string           `json:"state"`
}

// ExternalAttachment defines model for ExternalAttachment.
type ExternalAttachment struct {
	Interface string `json:"interface"`
	NodeId    string `json:"nodeId"`
	Vlan      *int   `json:"vlan,omitempty"`
}

// ExternalInterface defines model for ExternalInterface.
type ExternalInterface struct {
	Addresses []string              `json:"addresses"`
	Available bool                  `json:"available"`
	Kind      ExternalInterfaceKind `json:"kind"`
	Mac       string                `json:"mac"`
	Mtu       int                   `json:"mtu"`
	Name      string                `json:"name"`
}

// ExternalInterfaceKind defines model for ExternalInterface.Kind.
type ExternalInterfaceKind string

// FileCommand defines model for FileCommand.
type FileCommand struct {
	Action      FileCommandAction `json:"action"`
	Destination *string           `json:"destination,omitempty"`
}

// FileCommandAction defines model for FileCommand.Action.
type FileCommandAction string

// FileEntry defines model for FileEntry.
type FileEntry struct {
	Kind       FileEntryKind `json:"kind"`
	Mode       string        `json:"mode"`
	ModifiedAt time.Time     `json:"modifiedAt"`
	Name       string        `json:"name"`
	Size       int64         `json:"size"`
}

// FileEntryKind defines model for FileEntry.Kind.
type FileEntryKind string

// GuestSettings defines model for GuestSettings.
type GuestSettings struct {
	Hostname          *string   `json:"hostname,omitempty"`
	SshAuthorizedKeys *[]string `json:"sshAuthorizedKeys,omitempty"`
	Username          *string   `json:"username,omitempty"`
}

// Hardware defines model for Hardware.
type Hardware struct {
	CpuModel       *string          `json:"cpuModel,omitempty"`
	DiskBus        HardwareDiskBus  `json:"diskBus"`
	DiskController *string          `json:"diskController,omitempty"`
	Firmware       HardwareFirmware `json:"firmware"`
	FirmwareCode   *string          `json:"firmwareCode,omitempty"`
	FirmwareVars   *string          `json:"firmwareVars,omitempty"`
	GuestAgent     *bool            `json:"guestAgent,omitempty"`
	Machine        string           `json:"machine"`
	NicModel       HardwareNicModel `json:"nicModel"`
	SecureBoot     *bool            `json:"secureBoot,omitempty"`
	Tpm            *bool            `json:"tpm,omitempty"`
}

// HardwareDiskBus defines model for Hardware.DiskBus.
type HardwareDiskBus string

// HardwareFirmware defines model for Hardware.Firmware.
type HardwareFirmware string

// HardwareNicModel defines model for Hardware.NicModel.
type HardwareNicModel string

// Identity defines model for Identity.
type Identity struct {
	Administrator bool          `json:"administrator"`
	Grants        *[]ScopeGrant `json:"grants,omitempty"`
	Id            string        `json:"id"`
	Name          string        `json:"name"`
	Roles         *[]RolePreset `json:"roles,omitempty"`
}

// Interface defines model for Interface.
type Interface struct {
	Address   string `json:"address"`
	Id        string `json:"id"`
	Mac       string `json:"mac"`
	NetworkId string `json:"networkId"`
	Primary   bool   `json:"primary"`
}

// IssuedServiceToken defines model for IssuedServiceToken.
type IssuedServiceToken struct {
	Principal Principal `json:"principal"`
	Token     string    `json:"token"`
}

// LogChunk defines model for LogChunk.
type LogChunk struct {
	Data   string         `json:"data"`
	Stream LogChunkStream `json:"stream"`
}

// LogChunkStream defines model for LogChunk.Stream.
type LogChunkStream string

// Login defines model for Login.
type Login struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

// MetricHistory defines model for MetricHistory.
type MetricHistory struct {
	End         time.Time      `json:"end"`
	Series      []MetricSeries `json:"series"`
	Start       time.Time      `json:"start"`
	StepSeconds int            `json:"stepSeconds"`
}

// MetricPoint defines model for MetricPoint.
type MetricPoint struct {
	Time  time.Time `json:"time"`
	Value float64   `json:"value"`
}

// MetricSeries defines model for MetricSeries.
type MetricSeries struct {
	AssetId     string             `json:"assetId"`
	InstanceId  string             `json:"instanceId"`
	InterfaceId *string            `json:"interfaceId,omitempty"`
	Metric      MetricSeriesMetric `json:"metric"`
	NodeId      string             `json:"nodeId"`
	Points      []MetricPoint      `json:"points"`
}

// MetricSeriesMetric defines model for MetricSeries.Metric.
type MetricSeriesMetric string

// Network defines model for Network.
type Network struct {
	// AllocationPool Address prefix reserved for Netlab on an existing LAN
	AllocationPool *string             `json:"allocationPool,omitempty"`
	Cidr           string              `json:"cidr"`
	DnsAssetId     *string             `json:"dnsAssetId,omitempty"`
	DnsServers     *[]string           `json:"dnsServers,omitempty"`
	External       *ExternalAttachment `json:"external,omitempty"`
	Gateway        *string             `json:"gateway,omitempty"`
	Id             string              `json:"id"`
	Mtu            *int                `json:"mtu,omitempty"`
	Name           string              `json:"name"`
}

// Node defines model for Node.
type Node struct {
	Capabilities []string    `json:"capabilities"`
	Capacity     Resources   `json:"capacity"`
	Endpoint     string      `json:"endpoint"`
	Id           string      `json:"id"`
	Name         string      `json:"name"`
	ObservedAt   time.Time   `json:"observedAt"`
	Override     *Resources  `json:"override,omitempty"`
	Reserved     Resources   `json:"reserved"`
	Slots        int         `json:"slots"`
	State        *string     `json:"state,omitempty"`
	VmHardware   *VmHardware `json:"vmHardware,omitempty"`
}

// NodeBackupManifest defines model for NodeBackupManifest.
type NodeBackupManifest struct {
	CreatedAt  time.Time                 `json:"createdAt"`
	Definition json.RawMessage           `json:"definition"`
	Id         string                    `json:"id"`
	Name       string                    `json:"name"`
	Parts      map[string]NodeBackupPart `json:"parts"`
	SnapshotId *string                   `json:"snapshotId,omitempty"`
	Templates  map[string]NodeBackupPart `json:"templates"`
}

// NodeBackupPart defines model for NodeBackupPart.
type NodeBackupPart struct {
	SizeBytes  int64  `json:"sizeBytes"`
	SnapshotId string `json:"snapshotId"`
}

// NodeBackupPlan defines model for NodeBackupPlan.
type NodeBackupPlan struct {
	CreatedAt       time.Time            `json:"createdAt"`
	Definition      json.RawMessage      `json:"definition"`
	Name            string               `json:"name"`
	RecoveryPointId string               `json:"recoveryPointId"`
	Repository      NodeBackupRepository `json:"repository"`
	Sources         []NodeRecoverySource `json:"sources"`
}

// NodeBackupRepository defines model for NodeBackupRepository.
type NodeBackupRepository struct {
	AccessKey *string `json:"accessKey,omitempty"`
	Location  string  `json:"location"`
	Password  string  `json:"password"`
	Region    *string `json:"region,omitempty"`
	SecretKey *string `json:"secretKey,omitempty"`
}

// NodeBackupResult defines model for NodeBackupResult.
type NodeBackupResult struct {
	ManifestSnapshotId string                    `json:"manifestSnapshotId"`
	Parts              map[string]NodeBackupPart `json:"parts"`
	Templates          map[string]NodeBackupPart `json:"templates"`
}

// NodeBackupSource defines model for NodeBackupSource.
type NodeBackupSource struct {
	Repository NodeBackupRepository `json:"repository"`
	SizeBytes  int64                `json:"sizeBytes"`
	SnapshotId string               `json:"snapshotId"`
}

// NodeInfo defines model for NodeInfo.
type NodeInfo struct {
	AccessAddress      *string              `json:"accessAddress,omitempty"`
	Capabilities       []string             `json:"capabilities"`
	Capacity           Resources            `json:"capacity"`
	ExternalInterfaces *[]ExternalInterface `json:"externalInterfaces,omitempty"`
	Id                 string               `json:"id"`
	Name               string               `json:"name"`
	NetworkChassis     *string              `json:"networkChassis,omitempty"`
	ServiceNetwork     *ServiceNetwork      `json:"serviceNetwork,omitempty"`
	Slots              int                  `json:"slots"`
	Storage            *StorageInfo         `json:"storage,omitempty"`
	VmHardware         *VmHardware          `json:"vmHardware,omitempty"`
}

// NodeObservation defines model for NodeObservation.
type NodeObservation struct {
	NodeId     string            `json:"nodeId"`
	ObservedAt time.Time         `json:"observedAt"`
	Results    []ExecutionResult `json:"results"`
	Snapshot   bool              `json:"snapshot"`
}

// NodePlan defines model for NodePlan.
type NodePlan struct {
	ArtifactEndpoints *map[string]string             `json:"artifactEndpoints,omitempty"`
	Assets            []AssetExecution               `json:"assets"`
	Attachments       *[]ExternalAttachment          `json:"attachments,omitempty"`
	CaptureStates     *map[string]string             `json:"captureStates,omitempty"`
	EnvironmentId     string                         `json:"environmentId"`
	ExternalChassis   *map[string]string             `json:"externalChassis,omitempty"`
	Gateway           *ServiceGateway                `json:"gateway,omitempty"`
	IncludeMemory     bool                           `json:"includeMemory,omitempty"`
	OperationId       string                         `json:"operationId"`
	Phase             NodePlanPhase                  `json:"phase"`
	RecoveryPointId   *string                        `json:"recoveryPointId,omitempty"`
	RecoverySources   *map[string]NodeRecoverySource `json:"recoverySources,omitempty"`
	Services          *[]NodeServiceBinding          `json:"services,omitempty"`
	Spec              EnvironmentSpec                `json:"spec"`
	Vpn               *NodeVPNPlan                   `json:"vpn,omitempty"`
}

// NodePlanPhase defines model for NodePlan.Phase.
type NodePlanPhase string

// NodeRDP defines model for NodeRDP.
type NodeRDP struct {
	Address  string      `json:"address"`
	Settings RDPSettings `json:"settings"`
}

// NodeRecoverySource defines model for NodeRecoverySource.
type NodeRecoverySource struct {
	Backup        *NodeBackupSource `json:"backup,omitempty"`
	Endpoint      string            `json:"endpoint"`
	EnvironmentId string            `json:"environmentId"`
	Execution     AssetExecution    `json:"execution"`
	NodeId        string            `json:"nodeId"`
}

// NodeRegistration defines model for NodeRegistration.
type NodeRegistration struct {
	Endpoint string `json:"endpoint"`
	Name     string `json:"name"`
}

// NodeRestoreBackupTemplate defines model for NodeRestoreBackupTemplate.
type NodeRestoreBackupTemplate struct {
	Source   NodeBackupSource `json:"source"`
	Template Template         `json:"template"`
}

// NodeResult defines model for NodeResult.
type NodeResult struct {
	Error    *string               `json:"error,omitempty"`
	Results  []ExecutionResult     `json:"results"`
	Services *[]NodeServiceBinding `json:"services,omitempty"`
	Vpn      *NodeVPNResult        `json:"vpn,omitempty"`
}

// NodeSSH defines model for NodeSSH.
type NodeSSH struct {
	Address  string      `json:"address"`
	Settings SSHSettings `json:"settings"`
}

// NodeServiceBinding defines model for NodeServiceBinding.
type NodeServiceBinding struct {
	AssetId       string          `json:"assetId"`
	Id            string          `json:"id"`
	InterfaceId   string          `json:"interfaceId"`
	ListenPort    int             `json:"listenPort"`
	Protocol      ServiceProtocol `json:"protocol"`
	TargetAddress string          `json:"targetAddress"`
	TargetPort    int             `json:"targetPort"`
}

// NodeTemplatePreparation defines model for NodeTemplatePreparation.
type NodeTemplatePreparation struct {
	ArtifactEndpoint *string                `json:"artifactEndpoint,omitempty"`
	Capture          *TemplateCaptureSource `json:"capture,omitempty"`
	Registry         *RegistryCredentials   `json:"registry,omitempty"`
	Template         Template               `json:"template"`
}

// NodeVPNPeer defines model for NodeVPNPeer.
type NodeVPNPeer struct {
	Addresses []string `json:"addresses"`
	Id        string   `json:"id"`
}

// NodeVPNPlan defines model for NodeVPNPlan.
type NodeVPNPlan struct {
	ListenPort int       `json:"listenPort"`
	Peers      []VPNPeer `json:"peers"`
}

// NodeVPNResult defines model for NodeVPNResult.
type NodeVPNResult struct {
	ListenPort int           `json:"listenPort"`
	Mtu        int           `json:"mtu"`
	Peers      []NodeVPNPeer `json:"peers"`
	PublicKey  string        `json:"publicKey"`
}

// Operation defines model for Operation.
type Operation struct {
	Completed     int                `json:"completed"`
	CreatedAt     time.Time          `json:"createdAt"`
	EnvironmentId *string            `json:"environmentId,omitempty"`
	Error         *string            `json:"error,omitempty"`
	Id            string             `json:"id"`
	Kind          string             `json:"kind"`
	Phase         string             `json:"phase"`
	Results       *[]ExecutionResult `json:"results,omitempty"`
	Retryable     bool               `json:"retryable"`
	State         OperationState     `json:"state"`
	Total         int                `json:"total"`
	UpdatedAt     time.Time          `json:"updatedAt"`
}

// OperationState defines model for Operation.State.
type OperationState string

// Permission defines model for Permission.
type Permission string

// Point defines model for Point.
type Point struct {
	X float32 `json:"x"`
	Y float32 `json:"y"`
}

// Policy defines model for Policy.
type Policy struct {
	Action        PolicyAction    `json:"action"`
	BandwidthKbps *int            `json:"bandwidthKbps,omitempty"`
	DelayMs       *int            `json:"delayMs,omitempty"`
	Destination   *string         `json:"destination,omitempty"`
	Direction     PolicyDirection `json:"direction"`
	Id            string          `json:"id"`
	LossPercent   *float32        `json:"lossPercent,omitempty"`
	NetworkId     string          `json:"networkId"`
	Protocol      *string         `json:"protocol,omitempty"`
	Source        *string         `json:"source,omitempty"`
}

// PolicyAction defines model for Policy.Action.
type PolicyAction string

// PolicyDirection defines model for Policy.Direction.
type PolicyDirection string

// Principal defines model for Principal.
type Principal struct {
	Administrator bool          `json:"administrator"`
	CreatedAt     time.Time     `json:"createdAt"`
	Disabled      bool          `json:"disabled"`
	ExpiresAt     *time.Time    `json:"expiresAt,omitempty"`
	Id            string        `json:"id"`
	Kind          PrincipalKind `json:"kind"`
	Name          string        `json:"name"`
}

// PrincipalKind defines model for Principal.Kind.
type PrincipalKind string

// Problem defines model for Problem.
type Problem struct {
	Detail string `json:"detail"`
	Status int    `json:"status"`
	Title  string `json:"title"`
}

// RDPSettings defines model for RDPSettings.
type RDPSettings struct {
	// Certificate Confirmed sha256 certificate fingerprint in FreeRDP format
	Certificate string  `json:"certificate"`
	Domain      *string `json:"domain,omitempty"`
	InterfaceId *string `json:"interfaceId,omitempty"`
	Password    *string `json:"password,omitempty"`
	Port        int     `json:"port"`
	Username    string  `json:"username"`
}

// RecoveryCapture defines model for RecoveryCapture.
type RecoveryCapture struct {
	Consistency RecoveryConsistency `json:"consistency"`
	Memory      bool                `json:"memory"`
	SizeBytes   int64               `json:"sizeBytes"`
}

// RecoveryConsistency defines model for RecoveryConsistency.
type RecoveryConsistency string

// RecoveryPointSummary defines model for RecoveryPointSummary.
type RecoveryPointSummary struct {
	AssetCount       int                       `json:"assetCount"`
	Consistency      *RecoveryConsistency      `json:"consistency,omitempty"`
	CreatedAt        time.Time                 `json:"createdAt"`
	EnvironmentId    string                    `json:"environmentId"`
	Error            *string                   `json:"error,omitempty"`
	Id               string                    `json:"id"`
	MemoryAssetCount int                       `json:"memoryAssetCount,omitempty"`
	Name             string                    `json:"name"`
	OperationId      *string                   `json:"operationId,omitempty"`
	Revision         int                       `json:"revision"`
	SizeBytes        int64                     `json:"sizeBytes"`
	State            RecoveryPointSummaryState `json:"state"`
}

// RecoveryPointSummaryState defines model for RecoveryPointSummary.State.
type RecoveryPointSummaryState string

// RegistryCredentials defines model for RegistryCredentials.
type RegistryCredentials struct {
	Password *string `json:"password,omitempty"`

	// PlainHttp Explicitly connect to this registry over HTTP
	PlainHttp *bool   `json:"plainHttp,omitempty"`
	Username  *string `json:"username,omitempty"`
}

// ResolvedInterface defines model for ResolvedInterface.
type ResolvedInterface struct {
	Address   string    `json:"address"`
	Dns       *[]string `json:"dns,omitempty"`
	Gateway   *string   `json:"gateway,omitempty"`
	Id        string    `json:"id"`
	Mac       string    `json:"mac"`
	Mtu       int       `json:"mtu"`
	NetworkId string    `json:"networkId"`
	PortName  string    `json:"portName"`
	Prefix    int       `json:"prefix"`
	Primary   bool      `json:"primary"`
}

// Resources defines model for Resources.
type Resources struct {
	Cpu       int   `json:"cpu"`
	DiskGiB   int64 `json:"diskGiB"`
	MemoryMiB int64 `json:"memoryMiB"`
}

// RestartPolicy Restart unexpected exits only. Explicit stop remains stopped, including across node restarts.
type RestartPolicy string

// RestoreRecoveryPoint defines model for RestoreRecoveryPoint.
type RestoreRecoveryPoint struct {
	ExpectedRevision int `json:"expectedRevision"`
}

// RolePreset defines model for RolePreset.
type RolePreset struct {
	Key         RolePresetKey `json:"key"`
	Name        string        `json:"name"`
	Permissions []Permission  `json:"permissions"`
}

// RolePresetKey defines model for RolePreset.Key.
type RolePresetKey string

// Route defines model for Route.
type Route struct {
	Destination string `json:"destination"`
	NetworkId   string `json:"networkId"`
	NextHop     string `json:"nextHop"`
}

// SSHProbe defines model for SSHProbe.
type SSHProbe struct {
	InterfaceId *string `json:"interfaceId,omitempty"`
	Port        int     `json:"port"`
}

// SSHSettings defines model for SSHSettings.
type SSHSettings struct {
	AuthKind SSHSettingsAuthKind `json:"authKind"`

	// HostKey Confirmed SHA256 host-key fingerprint
	HostKey     string  `json:"hostKey"`
	InterfaceId *string `json:"interfaceId,omitempty"`
	Passphrase  *string `json:"passphrase,omitempty"`
	Password    *string `json:"password,omitempty"`
	Port        int     `json:"port"`
	PrivateKey  *string `json:"privateKey,omitempty"`
	Username    string  `json:"username"`
}

// SSHSettingsAuthKind defines model for SSHSettings.AuthKind.
type SSHSettingsAuthKind string

// SaveBlueprint defines model for SaveBlueprint.
type SaveBlueprint struct {
	ExpectedRevision int             `json:"expectedRevision"`
	Name             string          `json:"name"`
	Spec             EnvironmentSpec `json:"spec"`
}

// SaveBlueprintVersion defines model for SaveBlueprintVersion.
type SaveBlueprintVersion struct {
	EnvironmentId    string          `json:"environmentId"`
	ExpectedRevision int             `json:"expectedRevision"`
	Spec             EnvironmentSpec `json:"spec"`
}

// ScopeGrant defines model for ScopeGrant.
type ScopeGrant struct {
	Permissions []Permission        `json:"permissions"`
	ScopeId     string              `json:"scopeId"`
	ScopeKind   ScopeGrantScopeKind `json:"scopeKind"`
}

// ScopeGrantScopeKind defines model for ScopeGrant.ScopeKind.
type ScopeGrantScopeKind string

// ServiceEndpoint defines model for ServiceEndpoint.
type ServiceEndpoint struct {
	Address     string          `json:"address"`
	AssetId     string          `json:"assetId"`
	Id          string          `json:"id"`
	InterfaceId string          `json:"interfaceId"`
	ListenPort  *int            `json:"listenPort,omitempty"`
	Port        int             `json:"port"`
	Protocol    ServiceProtocol `json:"protocol"`
	TargetPort  int             `json:"targetPort"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

// ServiceExposure defines model for ServiceExposure.
type ServiceExposure struct {
	AssetId     string          `json:"assetId"`
	Id          string          `json:"id"`
	InterfaceId string          `json:"interfaceId"`
	ListenPort  *int            `json:"listenPort,omitempty"`
	Protocol    ServiceProtocol `json:"protocol"`
	TargetPort  int             `json:"targetPort"`
}

// ServiceGateway defines model for ServiceGateway.
type ServiceGateway struct {
	Address string `json:"address"`
	NodeId  string `json:"nodeId"`
}

// ServiceNetwork defines model for ServiceNetwork.
type ServiceNetwork struct {
	Address string `json:"address"`
	Cidr    string `json:"cidr"`
}

// ServiceProtocol defines model for ServiceProtocol.
type ServiceProtocol string

// StorageInfo defines model for StorageInfo.
type StorageInfo struct {
	AvailableBytes int64  `json:"availableBytes"`
	CapacityBytes  int64  `json:"capacityBytes"`
	Filesystem     string `json:"filesystem"`
	Path           string `json:"path"`
}

// StoragePool defines model for StoragePool.
type StoragePool struct {
	AllocatedGiB int64    `json:"allocatedGiB"`
	Capabilities []string `json:"capabilities"`
	Default      bool     `json:"default"`

	// Directory Original node storage location; visible to administrators
	Directory   *string           `json:"directory,omitempty"`
	Driver      StoragePoolDriver `json:"driver"`
	Error       *string           `json:"error,omitempty"`
	Id          string            `json:"id"`
	Name        string            `json:"name"`
	NodeId      string            `json:"nodeId"`
	OperationId *string           `json:"operationId,omitempty"`
	State       *StoragePoolState `json:"state,omitempty"`
	Storage     *StorageInfo      `json:"storage,omitempty"`
}

// StoragePoolDriver defines model for StoragePool.Driver.
type StoragePoolDriver string

// StoragePoolState defines model for StoragePool.State.
type StoragePoolState string

// SystemUpdate defines model for SystemUpdate.
type SystemUpdate struct {
	Activity       *UpdateActivity `json:"activity,omitempty"`
	Available      bool            `json:"available"`
	CanApply       bool            `json:"canApply"`
	CheckError     *string         `json:"checkError,omitempty"`
	CheckedAt      *time.Time      `json:"checkedAt,omitempty"`
	CurrentVersion string          `json:"currentVersion"`
	Latest         *UpdateRelease  `json:"latest,omitempty"`
}

// Template defines model for Template.
type Template struct {
	ArtifactNodeId *string                 `json:"artifactNodeId,omitempty"`
	Disks          *[]TemplateDisk         `json:"disks,omitempty"`
	Error          *string                 `json:"error,omitempty"`
	Format         *TemplateFormat         `json:"format,omitempty"`
	Hardware       *Hardware               `json:"hardware,omitempty"`
	Id             string                  `json:"id"`
	Initialization *TemplateInitialization `json:"initialization,omitempty"`
	Kind           TemplateKind            `json:"kind"`
	Media          *[]TemplateMedia        `json:"media,omitempty"`
	Name           string                  `json:"name"`
	NicModels      *[]string               `json:"nicModels,omitempty"`
	OperationId    *string                 `json:"operationId,omitempty"`
	Os             string                  `json:"os"`
	Resources      Resources               `json:"resources"`
	Source         string                  `json:"source"`
	State          *TemplateState          `json:"state,omitempty"`
	StateFiles     *[]string               `json:"stateFiles,omitempty"`
	Version        int                     `json:"version"`
	Volumes        *[]Volume               `json:"volumes,omitempty"`
}

// TemplateCaptureSource defines model for TemplateCaptureSource.
type TemplateCaptureSource struct {
	AssetId       string `json:"assetId"`
	EnvironmentId string `json:"environmentId"`
	InstanceId    string `json:"instanceId"`
}

// TemplateDisk defines model for TemplateDisk.
type TemplateDisk struct {
	BootOrder       int             `json:"bootOrder"`
	Bus             TemplateDiskBus `json:"bus"`
	ControllerIndex *int            `json:"controllerIndex,omitempty"`
	ControllerModel *string         `json:"controllerModel,omitempty"`
	ControllerUnit  *int            `json:"controllerUnit,omitempty"`
	Id              string          `json:"id"`
	SizeGiB         int64           `json:"sizeGiB"`
}

// TemplateDiskBus defines model for TemplateDisk.Bus.
type TemplateDiskBus string

// TemplateFormat defines model for TemplateFormat.
type TemplateFormat string

// TemplateImport defines model for TemplateImport.
type TemplateImport struct {
	ArtifactNodeId *string                 `json:"artifactNodeId,omitempty"`
	Disks          *[]TemplateDisk         `json:"disks,omitempty"`
	Error          *string                 `json:"error,omitempty"`
	Format         *TemplateFormat         `json:"format,omitempty"`
	Hardware       *Hardware               `json:"hardware,omitempty"`
	Id             string                  `json:"id"`
	Initialization *TemplateInitialization `json:"initialization,omitempty"`
	Kind           TemplateKind            `json:"kind"`
	Media          *[]TemplateMedia        `json:"media,omitempty"`
	Name           string                  `json:"name"`
	NicModels      *[]string               `json:"nicModels,omitempty"`
	OperationId    *string                 `json:"operationId,omitempty"`
	Os             string                  `json:"os"`
	Registry       *RegistryCredentials    `json:"registry,omitempty"`
	Resources      Resources               `json:"resources"`
	Source         string                  `json:"source"`
	State          *TemplateState          `json:"state,omitempty"`
	StateFiles     *[]string               `json:"stateFiles,omitempty"`
	Version        int                     `json:"version"`
	Volumes        *[]Volume               `json:"volumes,omitempty"`
}

// TemplateInitialization defines model for TemplateInitialization.
type TemplateInitialization string

// TemplateKind defines model for TemplateKind.
type TemplateKind string

// TemplateMedia defines model for TemplateMedia.
type TemplateMedia struct {
	Id     string `json:"id"`
	Source string `json:"source"`
}

// TemplateState defines model for TemplateState.
type TemplateState string

// UpdateActivity defines model for UpdateActivity.
type UpdateActivity struct {
	Error     *string             `json:"error,omitempty"`
	Phase     UpdateActivityPhase `json:"phase"`
	UpdatedAt time.Time           `json:"updatedAt"`
	Version   string              `json:"version"`
}

// UpdateActivityPhase defines model for UpdateActivity.Phase.
type UpdateActivityPhase string

// UpdateRelease defines model for UpdateRelease.
type UpdateRelease struct {
	Name        string    `json:"name"`
	Notes       string    `json:"notes"`
	PublishedAt time.Time `json:"publishedAt"`
	Url         string    `json:"url"`
	Version     string    `json:"version"`
}

// UpdateUser defines model for UpdateUser.
type UpdateUser struct {
	Disabled bool    `json:"disabled"`
	Name     string  `json:"name"`
	Password *string `json:"password,omitempty"`
}

// VPNAccess defines model for VPNAccess.
type VPNAccess struct {
	Addresses   *[]string      `json:"addresses,omitempty"`
	CreatedAt   time.Time      `json:"createdAt"`
	Error       *string        `json:"error,omitempty"`
	Id          string         `json:"id"`
	Mode        VPNMode        `json:"mode"`
	Name        string         `json:"name"`
	OperationId string         `json:"operationId"`
	PublicKey   string         `json:"publicKey"`
	Routes      []VPNRoute     `json:"routes"`
	State       VPNAccessState `json:"state"`
}

// VPNAccessState defines model for VPNAccess.State.
type VPNAccessState string

// VPNConnection defines model for VPNConnection.
type VPNConnection struct {
	Addresses  []string `json:"addresses"`
	AllowedIPs []string `json:"allowedIPs"`
	Endpoint   string   `json:"endpoint"`
	Mtu        int      `json:"mtu"`
	PublicKey  string   `json:"publicKey"`
}

// VPNMode defines model for VPNMode.
type VPNMode string

// VPNPeer defines model for VPNPeer.
type VPNPeer struct {
	Addresses *[]string  `json:"addresses,omitempty"`
	Id        string     `json:"id"`
	Mode      VPNMode    `json:"mode"`
	Name      string     `json:"name"`
	PublicKey string     `json:"publicKey"`
	Routes    []VPNRoute `json:"routes"`
}

// VPNRoute defines model for VPNRoute.
type VPNRoute struct {
	AccessCidr string `json:"accessCidr"`
	Cidr       string `json:"cidr"`
	NetworkId  string `json:"networkId"`
}

// VmHardware defines model for VmHardware.
type VmHardware struct {
	CpuModels       []string    `json:"cpuModels"`
	CpuModes        []string    `json:"cpuModes"`
	DiskControllers []string    `json:"diskControllers"`
	Machines        []VmMachine `json:"machines"`
	NicModels       []string    `json:"nicModels"`
}

// VmMachine defines model for VmMachine.
type VmMachine struct {
	Aliases       []string `json:"aliases"`
	DiskBuses     []string `json:"diskBuses"`
	Firmware      []string `json:"firmware"`
	FirmwareFiles []string `json:"firmwareFiles"`
	MaxVcpus      int      `json:"maxVcpus"`
	Name          string   `json:"name"`
	SecureBoot    bool     `json:"secureBoot"`
	Tpm2          bool     `json:"tpm2"`
}

// Volume defines model for Volume.
type Volume struct {
	Id        string `json:"id"`
	MountPath string `json:"mountPath"`
	Retain    *bool  `json:"retain,omitempty"`
	SizeGiB   int64  `json:"sizeGiB"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Id defines model for Id.
type Id = string

// Limit defines model for Limit.
type Limit = int

// Search defines model for Search.
type Search = string

// Accepted defines model for Accepted.
type Accepted = Operation

// ListRepositoryBackupsParams defines parameters for ListRepositoryBackups.
type ListRepositoryBackupsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListBlueprintsParams defines parameters for ListBlueprints.
type ListBlueprintsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`
}

// ListBlueprintVersionsParams defines parameters for ListBlueprintVersions.
type ListBlueprintVersionsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListEnvironmentsParams defines parameters for ListEnvironments.
type ListEnvironmentsParams struct {
	Cursor *Cursor            `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit             `form:"limit,omitempty" json:"limit,omitempty"`
	Search *Search            `form:"search,omitempty" json:"search,omitempty"`
	Status *EnvironmentStatus `form:"status,omitempty" json:"status,omitempty"`
}

// AssetConsoleParams defines parameters for AssetConsole.
type AssetConsoleParams struct {
	Kind ConsoleKind `form:"kind" json:"kind"`
}

// AssetFilesParams defines parameters for AssetFiles.
type AssetFilesParams struct {
	Path string `form:"path" json:"path"`
}

// ChangeAssetFilesParams defines parameters for ChangeAssetFiles.
type ChangeAssetFilesParams struct {
	Path string `form:"path" json:"path"`
}

// DownloadAssetFileParams defines parameters for DownloadAssetFile.
type DownloadAssetFileParams struct {
	Path string `form:"path" json:"path"`
}

// UploadAssetFileParams defines parameters for UploadAssetFile.
type UploadAssetFileParams struct {
	Path string `form:"path" json:"path"`
}

// AssetLogsParams defines parameters for AssetLogs.
type AssetLogsParams struct {
	Tail   *int                   `form:"tail,omitempty" json:"tail,omitempty"`
	Stream *AssetLogsParamsStream `form:"stream,omitempty" json:"stream,omitempty"`
	Follow *bool                  `form:"follow,omitempty" json:"follow,omitempty"`
}

// AssetLogsParamsStream defines parameters for AssetLogs.
type AssetLogsParamsStream string

// ListBackupsParams defines parameters for ListBackups.
type ListBackupsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// EnvironmentEventsParams defines parameters for EnvironmentEvents.
type EnvironmentEventsParams struct {
	LastEventID *int64 `json:"Last-Event-ID,omitempty"`
}

// ReplaceEnvironmentGrantsJSONBody defines parameters for ReplaceEnvironmentGrants.
type ReplaceEnvironmentGrantsJSONBody = []EnvironmentGrant

// GetEnvironmentMetricsParams defines parameters for GetEnvironmentMetrics.
type GetEnvironmentMetricsParams struct {
	AssetId *string `form:"assetId,omitempty" json:"assetId,omitempty"`

	// Range Relative time window in seconds; start overrides this window
	Range *int       `form:"range,omitempty" json:"range,omitempty"`
	Start *time.Time `form:"start,omitempty" json:"start,omitempty"`
	End   *time.Time `form:"end,omitempty" json:"end,omitempty"`

	// Step Seconds between points; defaults to at most 600 points
	Step *int `form:"step,omitempty" json:"step,omitempty"`
}

// ListRecoveryPointsParams defines parameters for ListRecoveryPoints.
type ListRecoveryPointsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// RevokeServiceParams defines parameters for RevokeService.
type RevokeServiceParams struct {
	ExpectedRevision int     `form:"expectedRevision" json:"expectedRevision"`
	ClientRequestId  *string `form:"clientRequestId,omitempty" json:"clientRequestId,omitempty"`
}

// RevokeVPNAccessParams defines parameters for RevokeVPNAccess.
type RevokeVPNAccessParams struct {
	ExpectedRevision int     `form:"expectedRevision" json:"expectedRevision"`
	ClientRequestId  *string `form:"clientRequestId,omitempty" json:"clientRequestId,omitempty"`
}

// ListNodesParams defines parameters for ListNodes.
type ListNodesParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`
}

// ListOperationsParams defines parameters for ListOperations.
type ListOperationsParams struct {
	EnvironmentId *string `form:"environmentId,omitempty" json:"environmentId,omitempty"`
	Cursor        *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit         *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListPrincipalsParams defines parameters for ListPrincipals.
type ListPrincipalsParams struct {
	Cursor *Cursor                   `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit                    `form:"limit,omitempty" json:"limit,omitempty"`
	Search *Search                   `form:"search,omitempty" json:"search,omitempty"`
	Kind   *ListPrincipalsParamsKind `form:"kind,omitempty" json:"kind,omitempty"`
}

// ListPrincipalsParamsKind defines parameters for ListPrincipals.
type ListPrincipalsParamsKind string

// ListTemplatesParams defines parameters for ListTemplates.
type ListTemplatesParams struct {
	Cursor *Cursor       `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit        `form:"limit,omitempty" json:"limit,omitempty"`
	Search *Search       `form:"search,omitempty" json:"search,omitempty"`
	Kind   *TemplateKind `form:"kind,omitempty" json:"kind,omitempty"`
	Ids    *[]string     `form:"ids,omitempty" json:"ids,omitempty"`
}

// CreateTemplateMultipartBody defines parameters for CreateTemplate.
type CreateTemplateMultipartBody struct {
	Files    []openapi_types.File `json:"files"`
	Template TemplateImport       `json:"template"`
}

// CreateBackupRepositoryJSONRequestBody defines body for CreateBackupRepository for application/json ContentType.
type CreateBackupRepositoryJSONRequestBody = CreateBackupRepository

// SaveBlueprintVersionJSONRequestBody defines body for SaveBlueprintVersion for application/json ContentType.
type SaveBlueprintVersionJSONRequestBody = SaveBlueprintVersion

// CreateEnvironmentJSONRequestBody defines body for CreateEnvironment for application/json ContentType.
type CreateEnvironmentJSONRequestBody = CreateEnvironment

// EnvironmentActionJSONRequestBody defines body for EnvironmentAction for application/json ContentType.
type EnvironmentActionJSONRequestBody = ActionRequest

// AssetActionJSONRequestBody defines body for AssetAction for application/json ContentType.
type AssetActionJSONRequestBody = ActionRequest

// ChangeAssetFilesJSONRequestBody defines body for ChangeAssetFiles for application/json ContentType.
type ChangeAssetFilesJSONRequestBody = FileCommand

// SaveAssetRDPSettingsJSONRequestBody defines body for SaveAssetRDPSettings for application/json ContentType.
type SaveAssetRDPSettingsJSONRequestBody = RDPSettings

// AssetRDPCertificateJSONRequestBody defines body for AssetRDPCertificate for application/json ContentType.
type AssetRDPCertificateJSONRequestBody = SSHProbe

// ExposeAssetServiceJSONRequestBody defines body for ExposeAssetService for application/json ContentType.
type ExposeAssetServiceJSONRequestBody = CreateService

// SaveAssetSSHSettingsJSONRequestBody defines body for SaveAssetSSHSettings for application/json ContentType.
type SaveAssetSSHSettingsJSONRequestBody = SSHSettings

// AssetSSHHostKeyJSONRequestBody defines body for AssetSSHHostKey for application/json ContentType.
type AssetSSHHostKeyJSONRequestBody = SSHProbe

// CaptureAssetTemplateJSONRequestBody defines body for CaptureAssetTemplate for application/json ContentType.
type CaptureAssetTemplateJSONRequestBody = CaptureTemplate

// CreateBackupJSONRequestBody defines body for CreateBackup for application/json ContentType.
type CreateBackupJSONRequestBody = CreateBackup

// RestoreBackupJSONRequestBody defines body for RestoreBackup for application/json ContentType.
type RestoreBackupJSONRequestBody = RestoreRecoveryPoint

// SaveEnvironmentBlueprintJSONRequestBody defines body for SaveEnvironmentBlueprint for application/json ContentType.
type SaveEnvironmentBlueprintJSONRequestBody = SaveBlueprint

// ChangeEnvironmentJSONRequestBody defines body for ChangeEnvironment for application/json ContentType.
type ChangeEnvironmentJSONRequestBody = ChangeRequest

// SaveDraftJSONRequestBody defines body for SaveDraft for application/json ContentType.
type SaveDraftJSONRequestBody = Draft

// ReplaceEnvironmentGrantsJSONRequestBody defines body for ReplaceEnvironmentGrants for application/json ContentType.
type ReplaceEnvironmentGrantsJSONRequestBody = ReplaceEnvironmentGrantsJSONBody

// CaptureRecoveryPointJSONRequestBody defines body for CaptureRecoveryPoint for application/json ContentType.
type CaptureRecoveryPointJSONRequestBody = CaptureRecoveryPoint

// RestoreRecoveryPointJSONRequestBody defines body for RestoreRecoveryPoint for application/json ContentType.
type RestoreRecoveryPointJSONRequestBody = RestoreRecoveryPoint

// SaveViewJSONRequestBody defines body for SaveView for application/json ContentType.
type SaveViewJSONRequestBody = CanvasView

// CreateVPNAccessJSONRequestBody defines body for CreateVPNAccess for application/json ContentType.
type CreateVPNAccessJSONRequestBody = CreateVPNAccess

// RegisterNodeJSONRequestBody defines body for RegisterNode for application/json ContentType.
type RegisterNodeJSONRequestBody = NodeRegistration

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUser

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUser

// CreateServiceTokenJSONRequestBody defines body for CreateServiceToken for application/json ContentType.
type CreateServiceTokenJSONRequestBody = CreateServiceToken

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = Login

// CreateStoragePoolJSONRequestBody defines body for CreateStoragePool for application/json ContentType.
type CreateStoragePoolJSONRequestBody = CreateStoragePool

// ApplySystemUpdateJSONRequestBody defines body for ApplySystemUpdate for application/json ContentType.
type ApplySystemUpdateJSONRequestBody = ApplySystemUpdate

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = TemplateImport

// CreateTemplateMultipartRequestBody defines body for CreateTemplate for multipart/form-data ContentType.
type CreateTemplateMultipartRequestBody CreateTemplateMultipartBody
